### ISSUE TITLE
触摸板会不顺畅

### ISSUE THREAD

**Issue by foxzzu** [Caldis/Mos#1]
感谢作者发布的实用app。Mos使用起来，效果很好，外接鼠标滚动顺滑了。我系统Sierra，使用Mos时发现一个现象，就是当软件打开运行后，使用触摸板上下滑动会有失灵现象。关闭软件就好了。

**Comment by Caldis** [comment]
方便提供一下机器型号吗? 
我手上只有2016年款的RMBP, 暂时没啥问题 可能还需要一些数据才能保证大部分的机器不会误判

**Comment by Caldis** [comment]
可以提供一下打开滚动界面后, 使用触摸板操作和使用鼠标滚轮操作的录屏吗?

目前判断逻辑是根据触摸板/鼠标滚轮数据的一些数据特征来判断的, 具体代码在这一段:
https://github.com/Caldis/Mos/blob/master/Mos/ScrollCore.swift#L161
