### ISSUE TITLE
部分鼠标具有的左右滚动功能

### ISSUE THREAD

**Issue by satellitemx** [Caldis/Mos#10]
部分鼠标支持横向滚动，例如向左或向右拨动滚轮时进行横向的滚动。
iTunes 商店的页面中有很多这样的超宽元素设计，需要进行横向滚动时，使用这些鼠标进行滚动时就需要反向拨动，并且也没有 Mos 的平滑效果。

希望能够在未来版本支持这一功能，谢谢。

**Comment by Caldis** [comment]
这个接口之前已经留了， 不过暂时还没有完善，后续慢慢加上

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/releases/tag/1.7.0
已新增该特性
