### ISSUE TITLE
Keep scrolling hwen moving cursor over another window

### ISSUE THREAD

**Issue by BakaPhoenix** [Caldis/Mos#101]
When i stop my mouse scroller wheel and immediatly move my mouse cursor over another window the scrolling continue in the new window even if the scrolling wheel is stopped.
I suppose the smoothed scrolling animation move over to the new window.
I hope there is an easy fix for this problem.
Thanks

**Comment by Caldis** [comment]
Fixed: https://github.com/Caldis/Mos/releases/tag/3.3.1
