### ISSUE TITLE
钉钉聊天中，图片缩放一滚动就会放大到最大，一收缩就会缩到最小。开特例就可以避免这个情况正常使用，但还是希望改进！

### ISSUE THREAD

**Issue by liyang-bsy** [Caldis/Mos#102]
**Describe the bug | 问题描述**
钉钉聊天中，图片缩放一滚动就会放大到最大，一收缩就会缩到最小。开特例就可以避免这个情况正常使用，但还是希望改进！

**To Reproduce | 如何重现**
钉钉聊天中，对图片的用滚轮的缩放动作

**Expected behavior | 期望结果**
正常缩放

**Screenshots | 相关截图**
N/A

**System Info | 系统信息:**
阿里的钉钉，mac 多版本都有这情况。

**Additional context | 额外说明**
N/A

**Comment by Caldis** [comment]
这个没办法, 除非钉钉的图片查看器用的是独立进程, 不然没法检测出来
