### ISSUE TITLE
水瓶滚动被锁定，按切换键才是竖直滚动

### ISSUE THREAD

**Issue by Alitec-sg** [Caldis/Mos#103]
- 问题描述 | Issue description:

Set optiona key to switch horizons scrolling 

Press option scrolling and released option key scrolling  few times . Without press option key scrolling become horizontal scrolling 
Have to quit and re-open app
- 如何重现 | How to reproduce it:

Same as above 
- 期望结果 | What is expected:

- 实际结果 | What is actually happening:

- 软件版本 | Application version:

2.30
- 系统版本 | System version:

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:

BTT

**Comment by Caldis** [comment]
这个是已知问题, 如果开 App 的时候按住 Shift 键, 后续的识别很可能就会整个反过来

一般重启即可解决

**Comment by godly-devotion** [comment]
Same here too. I had to eventually disable the Shift Toggle key as it would often reverse the normal scroll direction.

**Comment by Alitec-sg** [comment]
> Same here too. I had to eventually disable the Shift Toggle key as it would often reverse the normal scroll direction.

are you using BTT or other tools for keyboard short cuts?

**Comment by godly-devotion** [comment]
@Alitec-sg Nope.
