### ISSUE TITLE
 mos 默认设置有些过于顺滑了，希望能调整默认配置

### ISSUE THREAD

**Issue by awking** [Caldis/Mos#104]
**Describe the bug | 问题描述**
A clear and concise description of what the bug is. | 清晰简洁的问题描述问题所在
对比 smothscroll 而言，mos 动画持续时间过长，使用久了有些眩晕
**To Reproduce | 如何重现**
Steps to reproduce the behavior | 重现问题的步骤
分别打开 smothscroll 或者不开启 mos时与 开启 mos 进行比较
**Expected behavior | 期望结果**
A clear and concise description of what you expected to happen. | 简单描述问题解决后您所希望的结果
修改 mos 默认配置，降低动画时长，以及滚动效果
个人目前配置如下:
最短步长 25.00
速度增益:2.00
持续时间:1.5s
**Screenshots | 相关截图**
If applicable, add screenshots to help explain your problem. | 如果有, 可以帮助我们快速定位问题

**System Info | 系统信息:**
 - OS: [e.g. iOS]  mac mojave
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] mojvae 70
-  Application [e.g. Safari, Chrome, Whole System] any

**Additional context | 额外说明**
Add any other context about the problem here. | 任何说明都可以
并非 mos，只是希望调整配置，不确定是否由升级mojave 后导致。但反复对比关闭 mos 开启 smothscrooll ，始终觉得 mos 默认效果不是特别理想。

**Comment by Caldis** [comment]
可以尝试调整一下偏好设置里面的参数, 这个感受因人而异吧 ...
