### ISSUE TITLE
停止滚轮后，动画跨窗口继续滑动问题

### ISSUE THREAD

**Issue by realMavLee** [Caldis/Mos#106]
**Describe the bug | 问题描述**
当前页面的滑动可以通过「快速移动鼠标」而被带到其他页面。
**To Reproduce | 如何重现**
任意地方滑动滚轮，停止滚轮立马移动鼠标，鼠标所经过的可滑动页面都会产生滑动
**Expected behavior | 期望结果**
在如上情况下，其他页面不延续滑动。最好的结果是被移除鼠标的页面继续平滑滚动，因为我看现在当鼠标移除了该页面，滚动就停止的很生硬。
**Screenshots | 相关截图**
个人测试效果
![demo](https://ws2.sinaimg.cn/large/006tNbRwgy1fwenpjeimtg311r0nsnmq.gif)
**System Info | 系统信息:**
我不是 Mac 开发者，所以描述可能不当。个人感觉这个问题跟系统无关，像是动画执行这里没有考虑鼠标可能移入其他可滑动页面的情况。
**Additional context | 额外说明**
这里有关于该问题的另一份描述
> #101

**Comment by Caldis** [comment]
这个判断虽然不麻烦, 但是考虑到窗口的频繁切换, 会增加 Mos 的系统占用及电量消耗

这个也并不是特别影响使用的问题, 后续可能会作为可选的配置项让用户手动启用

**Comment by zhipengyan** [comment]
期待推出这个配置，类似钉钉、qq这种IM 软件，两边分栏，经常会在联系人和对话栏切换的时候，容易有这种跨越滚动的问题，由于这些软件在工作生活中使用频率挺高，就有点困扰

**Comment by Caldis** [comment]
@zhipengyan 
现在检测机制是针对不同应用间的 bundleId 做的, 如果是同应用内的 ScrollView 来做侦测的话, 这个没有任何办法检测到

**Comment by teemola** [comment]
这个问题我也有遇到过：在mac安装hyperdock之后，可以将鼠标贴在程序窗口顶部，向上/向下滚动滚轮来实现窗口缩小放大的效果。当有多个放大的程序窗口时，mos的平滑滚动会持续作用到这几个程序导致它们也跟着缩小。
![bug (1)](https://user-images.githubusercontent.com/24849359/57829712-6f971f80-77e2-11e9-9983-abac1922e91d.gif)

**Comment by Caldis** [comment]
已修复: https://github.com/Caldis/Mos/releases/tag/3.3.1

**Comment by realMavLee** [comment]
@Caldis Long time no see😎
