### ISSUE TITLE
Smooth Scrolling not working properly in Adobe CC Products

### ISSUE THREAD

**Issue by hohoho123456** [Caldis/Mos#107]
**Describe the bug | 问题描述**
A clear and concise description of what the bug is. | 清晰简洁的问题描述问题所在
--- when I scroll in Adobe Products using the mouse scroll wheel, the scrolls are exaggerated -- too fast. Zoom in Adobe Photoshop, Illustrator, etc. with mouse and MOS enabled is too fast and scrolling in documents with Adobe Acrobat DC is also too fast while everything else scrolls perfectly. Can't correct with settings.

**To Reproduce | 如何重现**
Steps to reproduce the behavior | 重现问题的步骤
--- use zoom with mouse or scroll documents using the mouse scroll wheel in Adobe Products with MOS enabled.

**Expected behavior | 期望结果**
A clear and concise description of what you expected to happen. | 简单描述问题解决后您所希望的结果
--- the scroll with the mouse scroll wheel should be smooth and the right speed like in everything else.

**Screenshots | 相关截图**
If applicable, add screenshots to help explain your problem. | 如果有, 可以帮助我们快速定位问题
Screenshot  --- https://youtu.be/yI0HpAIBK44

**System Info | 系统信息:**
--- Mac OSX Mojave 10.14.1 Beta (18B73a)

--- chrome

--- 69

-  Application [e.g. Safari, Chrome, Whole System]
--- Adobe Photoshop, Illustrator, Acrobat DC, etc.
 
**Additional context | 额外说明**
Add any other context about the problem here. | 任何说明都可以
--- smooth scrolling using the mouse scroll wheel with MOS is perfect everywhere in MacOSX Mojave except for all Adobe Products. Smooth scrolling in Adobe Products with the touchpad works perfectly. The problem is only in MOS.

**Comment by Caldis** [comment]
Some application handling the scrolling events by the time of scrolling, instead of precision distance of scrolling. Interpolation of Mos will scaling the result on those application. 
So, the easiest solution just add those application to Exception and disable the smooth.

**Comment by hohoho123456** [comment]
how do i do that?

i tried this and it did not work. smooth scrolling is still on.
![screen shot 2018-10-29 at 5 57 40 pm](https://user-images.githubusercontent.com/44559677/47642696-43001b00-dba4-11e8-80c4-d4547603ccdc.png)

**Comment by Caldis** [comment]
Maybe it's a bug, i will fix it soon later

**Comment by beyondZB** [comment]
> Maybe it's a bug, i will fix it soon later

I have the same problem on my Adobe Acrobat DC. (macOS 10.13.6; Mos 2.3.0).
I have never read the Mos Code. But I guess that may caused by different names of the same app? 
For "Adobe Acrobat DC", in Mos Exception lis,  its name is "Adobe Acrobat.app".
<img width="562" alt="image" src="https://user-images.githubusercontent.com/7394615/47992106-f8901880-e126-11e8-8f6d-b5b6d51f33c2.png">
While in Activity Monitor, its name is "Acrobat Pro DC".
<img width="843" alt="image" src="https://user-images.githubusercontent.com/7394615/47992213-43119500-e127-11e8-85ca-b5748aea21e1.png">
Only for reference ;b

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/releases/tag/2.4.0-beta

**Comment by hohoho123456** [comment]
I mean make the smooth scroll work in Adobe Products like how it works in the trackpad. Because smooth scrolling with the trackpad works perfect. Make the scroll with MOS using Adobe Products the same like the trackpad smooth scroll? Same like this --- https://youtu.be/clQz1WJJR64

**Comment by Caldis** [comment]
Those application using a different way to treat the different types of scrolling input, unless i found a way to simulate the gesture event, otherwise I can only keep the status quo

**Comment by hohoho123456** [comment]
I did not ask you to help me with my problem with YOUR app. Thank you for
being a jerk. I was actually thinking of paying you for your app when I
have the money in the future. But now I have decided when I saw the
screenshot that I won't do that anymore. Good thing I am smart enough to
backup all my files. Thanks.
