### ISSUE TITLE
例外项允许选取非.app程序

### ISSUE THREAD

**Issue by liujj** [Caldis/Mos#108]
这是一个新功能的建议

我在日常中会使用mac玩Minecraft游戏，在该款游戏中有禁用smooth，开启reverse的需求。这款游戏是通过java虚拟机，在命令行模式下启动的。
此外作为开发者，我还具有使用qt应用并禁用smooth的场景。

在Exception页面中，我注意到使用了`openPanel.allowedFileTypes = ["app", "App", "APP"]`来限制只能选取.app文件，并且最终是通过`getApplicationBundleIdFrom(pid)`来识别鼠标当前位置下的程序。
使用jdk运行Minecraft时，其bundleId为`net.java.openjdk.cmd`，通过修改编译mos并手动写入了需要的例外项，是可以正确生效的。

提出的建议是：
1、对有经验的使用者放开只能选取.app限制。针对非.app应用的例外项，通过完整路径去匹配。
2、对有经验的使用者放开只能选取.app限制。允许自行填写bundleId。

**Comment by Caldis** [comment]
谢谢你的建议，存在这个限制的原因是由于有部分用户会尝试添加位于应用程序目录下的快捷方式，例如 Steam 的游戏，或类似软件。
而此类软件实际在应用程序目录下存放的仅仅是快捷方式，与实际应用的 bundleId 并不相同，导致用户添加后例外并不生效。
对于手动填写 bundleId 确实是个好建议，我会考虑加入。而对于你的情况，也未必需要重新编译，只需要通过直接在 Minecraft 的安装目录下找一下实际启动的应用入口文件，理应是可以添加的。

**Comment by liujj** [comment]
谢谢你的回复~

**Comment by niklaswa** [comment]
What do I have to add to the exception list exactly to make an exception for MC/Java?
