### ISSUE TITLE
睡眠唤醒后，鼠标左右滚动失效

### ISSUE THREAD

**Issue by HuangJianlang** [Caldis/Mos#109]
**Describe the bug | 问题描述**
macOS 10.14， 睡眠唤醒后，鼠标左右滚动失效
**To Reproduce | 如何重现**
鼠标是Microsoft Sculpt Comfort Mouse，睡眠唤醒Mac后，左右滚动键失效，需要重启软件
**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - OS: macOS 10.14
 - Browser ： chrome
 - Version [e.g. 22] 2.30， 2.4 均存在问题
-  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by HuangJianlang** [comment]
感觉是和bettertouchtools有冲突了

**Comment by Caldis** [comment]
每次都会还是偶发 ?

**Comment by HuangJianlang** [comment]
> 每次都会还是偶发 ?
每次都会，只要屏幕休眠，在bbt中设置的左右滚动键就会失效。必须重启mos，重启bbt是没有用。

**Comment by Caldis** [comment]
因为我没在用 BTT, 请问在 BTT 中设置的左右滚动具体是怎么样的 ?
能给个截图最好了

**Comment by Caldis** [comment]
@HuangJianlang THX

**Comment by HuangJianlang** [comment]
@Caldis 辛苦了

**Comment by Caldis** [comment]
@cxzl25 看来我需要弄个看门狗在唤醒后循环检测是不是启动了

**Comment by wayone** [comment]
遇到同样的问题，感觉不是每次，
