### ISSUE TITLE
在IntelliJ IDEA下滚动速度非常快

### ISSUE THREAD

**Issue by galaxy2000** [Caldis/Mos#11]
在IntelliJ IDEA下滚动速度非常快，一屏一屏的翻
相关环境：
     macos 10.12.3
     IntelliJ IDEA 2016.3.5
     mos 1.4.4

**Comment by wyudong** [comment]
我估计是 IntelliJ 对鼠标滚动也做过处理，相应的几款比如 WebStorm、PhpStorm、Android Studio 也遇到类似的问题。所以我把这些都添加到忽略列表了。还有你可以在偏好设置里调节“速度”，但就会影响其他应用了。

**Comment by Caldis** [comment]
建议在这些软件里面直接禁用平滑, 因为这些软件滚动时候不是基于像素的, 是基于行的, 所以就会这样

**Comment by galaxy2000** [comment]
好的，非常感谢。
