### ISSUE TITLE
水平滚动的转换键设置无效

### ISSUE THREAD

**Issue by wayone** [Caldis/Mos#110]
**Describe the bug | 问题描述**
设置了转换键后，设置的那个按键依旧无法使用水平滚动。其实只能使用 shift 键。
**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - OS: [e.g. iOS] 10.14.1 (18B75)
-  Application [e.g. Safari, Chrome, Whole System]
所有软件都这样
**Additional context | 额外说明**

**Comment by Caldis** [comment]
請問使用的是哪一款鼠標

**Comment by wayone** [comment]
> 請問使用的是哪一款鼠標

双飞燕OP-550NU

**Comment by wayone** [comment]
键盘是直接接到 MacBook Pro 上的。
不管设置什么，shift 都有效。设置的那个键无效

**Comment by wayone** [comment]
关闭你这个软件后，shift 也能把鼠标滚轮的竖向滚动切换成横向滚动。使用你这软件后却不能修改按键。

**Comment by Caldis** [comment]
系統本身就有自帶的 Shift 轉換，但是這部份信息是軟件獲取不到的，所以只能根據按下的按鍵來手動處理這個轉換過程，這應該是個BUG

**Comment by jazzbon** [comment]
你换个鼠标试试？我有几个罗技鼠标，有线无线都有，都试了一下，都管用。

**Comment by WuYiwen97** [comment]
确实，只有shift可以转换
