### ISSUE TITLE
minecraft无法添加例外名单

### ISSUE THREAD

**Issue by BAKAMiku** [Caldis/Mos#112]
**Describe the bug | 问题描述**
已查阅#108，还是不清楚如何添加其入口文件
.jar文件无法添加进名单

**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
-  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
之前没有考虑到 ```.jar``` 文件的场景, 之后会加上, 等我有空装个 MC 测一测 ...

**Comment by Caldis** [comment]
已修复: https://github.com/Caldis/Mos/releases/tag/3.3.1
