### ISSUE TITLE
Hide menu bar icon option for Mos

### ISSUE THREAD

**Issue by panicattack95** [Caldis/Mos#113]
**Describe the bug | 问题描述**

**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
-  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by panicattack95** [comment]
Can this feature be added? It annoys me to have the icon in the menu bar because I never need it

**Comment by Caldis** [comment]
Just holding the option button and click the menu bar icon.

**Comment by Caldis** [comment]
@fabiospampinato Sorry for the entrance to this option is hidden so deep, just before I did not find a better solution to make the icon display again and so i don't want most users to use this feature.
But, I have found a way to solve this problem elegantly, just need to look forward to the new version of the update.😜

**Comment by fabiospampinato** [comment]
Awesome, thank you !
