### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by fanchangyong** [Caldis/Mos#115]
**Describe the bug | 问题描述**

我分别下载了2.3.0, 2.2.6, 2.2.2的版本，应用打不开，任务栏那里有个图标闪一下就没了。

**To Reproduce | 如何重现**
下载2.3.0版本的release，直接打开

**Expected behavior | 期望结果**
正常运行

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - OS: macOS 10.14.1
-  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**
在Console中找到一条错误信息：
Fatal error: Failed to create event tap: file /Users/Caldis/Dropbox/Dev/Mos/Mos/ScrollCore/Interception.swift, line 16

**Comment by fanchangyong** [comment]
一个一个的试，直到1.7.0是好的，只好退回到这个版本了。

**Comment by Caldis** [comment]
感谢反馈, 看样子应该是创建滚动事件拦截层的时候挂了, 系统里有用其他的类似软件吗 ?

**Comment by MegaThomas** [comment]
我也遇到了闪退的问题，但已经解决了。
过程：使用 homebrew 安装 2.3.0 版本，然后闪退，就卸载了。之后从网站直接下载 dmg 文件安装，可以正常使用。

**Comment by Caldis** [comment]
@MegaThomas 奇怪, 按理来说不应该有这样的差异, 请问自 homebrew cask 下载的时候有手动或自动做辅助功能授权相关的处理吗 ?

**Comment by MegaThomas** [comment]
> @MegaThomas 奇怪, 按理来说不应该有这样的差异, 请问自 homebrew cask 下载的时候有手动或自动做辅助功能授权相关的处理吗 ?

并没有。homebrew cask install mos 之后第一次打开的时候，并不显示辅助功能授权的界面，任务栏图标闪现一下消失。没有试过手动授权。

**Comment by Caldis** [comment]
@MegaThomas 请问你也安装了Karabiner吗

**Comment by MegaThomas** [comment]
> @MegaThomas 请问你也安装了Karabiner吗

没有，类似软件也没有装过

**Comment by myonlylonely** [comment]
我也有这个问题。1.7版本是可以使用的。更高版本的Mos都会闪退。没有安装Karabiner。

**Comment by williambj1** [comment]
我也有此问题，
- 我安装了Karabiner，但是在Karabiner不运行的时候也会闪退
- 滚动的监视器可以打开而且工作正常
- 软件本身运行正常，滚动的优化效果都在
- 版本是自己Clone下来编译的，到Commit d7cc240
只要一点击设置就会闪退
![image](https://user-images.githubusercontent.com/45396585/53090172-93cbc300-3549-11e9-9da3-73401e6241fc.png)

非常不错的软件，希望能尽快解决这个问题

**Comment by Caldis** [comment]
@williambj1 
试试用 https://github.com/Caldis/Mos/commit/bd56bf1500bc44b23fd55f309354bf8aabb7471c 这个版本编译, 后面新增加了一些未完成的功能可能影响到了设置界面正常运行, 近期比较忙, 没来得及更新

**Comment by williambj1** [comment]
@Caldis 
不好意思最近比较忙没时间测试，我尝试了Release里面的2.4.0beta，现在毫无问题！
你的作品真是太棒了！希望以后能有更多优秀的功能！
