### ISSUE TITLE
禁用键功能，当禁用键设置了 Control 时管用，设置其他按键都不管用

### ISSUE THREAD

**Issue by wayone** [Caldis/Mos#118]
**Describe the bug | 问题描述**
外接键盘【IROCKS艾芮克KR6402】 ，外接鼠标【双飞燕OP-550NU】，禁用键功能，当禁用键设置了 Control 时管用，设置其他按键都不管用。
当用 MacBook Pro 自带键盘时，设置 shift 不管用，设置其他键管用。
**To Reproduce | 如何重现**
如题
**Expected behavior | 期望结果**
设置其他键也管用
**Screenshots | 相关截图**
<img width="234" alt="jietu20181204-092943" src="https://user-images.githubusercontent.com/10210378/49412369-29f01880-f7a7-11e8-9231-19a224b3e626.png">

**System Info | 系统信息:**
 - OS: [e.g. iOS] 10.14.1 (18B75)
 - Browser [e.g. chrome, safari]  chrome
 - Version [e.g. 22] 70.0.3538.102（正式版本） （64 位）
-  Application [e.g. Safari, Chrome, Whole System]
在 chrome 和 xcode Version 10.1 (10B61) 中试过，都不行
**Additional context | 额外说明**

**Comment by Caldis** [comment]
这个热键检测模块很多问题, 到时候重构一下这块
