### ISSUE TITLE
Logitech Options 引起的崩溃问题 | The crash caused by the Logitech Options

### ISSUE THREAD

**Issue by dishitian** [Caldis/Mos#119]
**Describe the bug | 问题描述**

**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
-  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
I first saw this error, are you using it on a remote desktop?

**Comment by dishitian** [comment]
no, I installed Microsoftx Remote 0Desktop on my mac and later I installed the low version as normal.
It's normal to reinstall the latest version again

**Comment by eddyzhouLearning** [comment]
> I first saw this error, are you using it on a remote desktop?

我在 macbook 上用 Microsoft Remote Desktop 连接另外一台PC，同时开启mos。 在远程桌面里面，“翻转方向”没有生效。 我尝试把 Microsoft Remote Desktop 加入 “例外”，没有效果。
但神奇的是，我勾选了 “白名单模式” ，在远程桌面里面“翻转方向”就生效了，同时，Mac自己的应用里面也都是生效的

**Comment by Caldis** [comment]
@eddyzhouLearning 
> 同时，Mac自己的应用里面也都是生效的

怎么理解这句话 ? 意思是说在开启了 Microsoft Remote Desktop 之后勾选白名单模式依然会在全局生效 ?

**Comment by eddyzhouLearning** [comment]
> @eddyzhouLearning
> 
> > 同时，Mac自己的应用里面也都是生效的
> 
> 怎么理解这句话 ? 意思是说在开启了 Microsoft Remote Desktop 之后勾选白名单模式依然会在全局生效 ?

是的。这几天我又在尝试中，发现了好像和 鼠标、连接的win系统有点关系。十分神奇，我打算使用 2.4.0-beta 来试一下。

**Comment by eddyzhouLearning** [comment]
> @eddyzhouLearning
> 
> > 同时，Mac自己的应用里面也都是生效的
> 
> 怎么理解这句话 ? 意思是说在开启了 Microsoft Remote Desktop 之后勾选白名单模式依然会在全局生效 ?

你好，已经破案了。是因为我使用的罗技蓝牙鼠标，为了调整按键功能在macbook上安装了Logitech Option ，这个应用默认对鼠标的滚动进行了调整。在更新了 mos 2.4.0-beta 并 禁用了Logitech Option的滚动设置之后就一切正常了。

**Comment by Caldis** [comment]
@eddyzhouLearning 感谢反馈, 同时为你的破案能力点赞👍, 哈哈
感觉可以在首次开启应用时给个提示, 以前很多 ISSUE 都是类似问题

**Comment by eddyzhouLearning** [comment]
> @eddyzhouLearning 感谢反馈, 同时为你的破案能力点赞👍, 哈哈
> 感觉可以在首次开启应用时给个提示, 以前很多 ISSUE 都是类似问题

@Caldis  是我需要感谢你做出这个app免费让大家使用
