### ISSUE TITLE
希望可以禁止或优化不支持平滑滚动的触摸板平滑滚动（黑苹果的笔记本滚起来很蛋疼）

### ISSUE THREAD

**Issue by varjay** [Caldis/Mos#12]
希望可以禁止或优化不支持平滑滚动的触摸板平滑滚动（黑苹果的笔记本滚起来比较蛋疼）

这个软件在黑苹果的触摸板下还是挺好的，比smoothScroll的轻轻一碰就到底好很多了

**Comment by varjay** [comment]
这软件简直是居家必备！！给作者一个赞！

**Comment by Caldis** [comment]
目前这个还无法做到，因为目前区分触摸板和鼠标的逻辑是根据白苹果触摸板的一些书籍特征来识别的，而一般电脑的触摸板并没有提供这部分数据，无法识别和区分，自然也就无法做到禁用。
具体可以看之前的问题：https://github.com/Caldis/Mos/issues/2

所以建议目前你可以自己尝试一下在设置里面调节出一个触控板和鼠标滚轮都比较合适的参数组合来规避这个问题
