### ISSUE TITLE
与 Keyboard Maestro 的兼容问题

### ISSUE THREAD

**Issue by memset0** [Caldis/Mos#120]
**Describe the bug | 问题描述**
在使用 Keyboard Maestro 进行任何一个快捷键操作后鼠标滚轮的方向会反向（纵向变横向）

**To Reproduce | 如何重现**
在 Keyboard Maestro 中添加一个快捷键操作，然后运行。鼠标滚轮的方向会反向。
重启 Mos 后恢复正常

**System Info | 系统信息:**
 - OS: macOS 10.14.2
 - Version 2.3.0

**Additional context | 额外说明**
不清楚是 Keyboard Maestro 的问题还是 Mos 的问题，关闭平滑滚动的话就不会被反向

**Comment by Caldis** [comment]
感觉上是  Keyboard Maestro  在快捷键激活的过程触发了 Mos 的热键检测, 然后导致的问题, 这块确实很多 BUG

**Comment by memset0** [comment]
请问有什么办法可以暂时关闭这个热键检测吗？

**Comment by Caldis** [comment]
将设置里面的热键都设为DISABLE也不管用吗？

**Comment by Caldis** [comment]
<img width="1072" alt="screen shot 2018-12-20 at 4 39 54 pm" src="https://user-images.githubusercontent.com/3529490/50273532-e6b7ca00-0475-11e9-812d-3006927dfbc5.png">
我这样试了一下，貌似没法复现

**Comment by memset0** [comment]
抱歉我可能没描述清楚，需要设置类似这样的快捷键：

![](https://i.loli.net/2018/12/20/5c1b802e2e5c2.png)

运行后就不能正常滚动，目前 Mos 的设置如下：

![](https://i.loli.net/2018/12/20/5c1b84856abee.png)

**Comment by memset0** [comment]
最新版这个问题好像解决了。

（这句话好像迟到了几个月。
