### ISSUE TITLE
建议增设快捷键或者下拉菜单，快速切换滚动方向

### ISSUE THREAD

**Issue by jiaoting** [Caldis/Mos#121]
建议增设快捷键或者下拉菜单，快速切换滚动方向。目前使用外接鼠标时，与内置触控板的滚动方向是相反的，会出现自然滚动与鼠标滚轮滚动方向相反的情况，目前切换需要进入软件界面，然后点击偏好设置才能设置

**Comment by Caldis** [comment]
为什么需要经常切换这个方向…如果在特定APP中需要反过来，可以用例外列表

**Comment by jiaoting** [comment]
> 为什么需要经常切换这个方向…如果在特定APP中需要反过来，可以用例外列表

有时候需要轮流切换鼠标跟触控板，每次切换都需要点进去设置，需要好几步操作，有没有可以少点几步的操作？

**Comment by Caldis** [comment]
没有...估计很少人这样用, 而且黑果这块也没法太好支持, 毕竟黑果的驱动提供的 HID 信息很有限
