### ISSUE TITLE
在外接键盘下，禁用键只对右边的修饰键生效

### ISSUE THREAD

**Issue by zlaong** [Caldis/Mos#122]
**Describe the bug | 问题描述**
我设置的禁用键是command，这样可以让我在axure中更好的控制缩放。
但是我现在外接一块键盘，只有右边的command可以生效，左边的毫无效果。
因为是块win键盘，我还在系统中互调了command和option的键位。
**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - OS: [OS X 10.14.2]
- keyboard:[leopold fc750R]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
猜测是键盘回报的 keycode 不一致导致的？我的大F并没有感觉到不适…

**Comment by ZbinH2O** [comment]
我所使用的ikbc-c87遇到了相同的问题,左侧command键位不生效,同样在系统当中互换了command和option键位...

**Comment by Caldis** [comment]
@ZbinH2O 互换之后应该要选择Option而不是Command吧

**Comment by ZbinH2O** [comment]
@Caldis 我测试了一下,APP里选择Option的话,只有键盘右测的Option键(指切换后的Option键,即win图标键)生效...另外,我还测试了一下把系统设置的修饰键恢复到默认并把APP选回Command之后,情况变成了只有左边的Command(指未切换的Command键,即win图标键)生效,右边的Command(指未切换的Command键,即win图标键)无效

**Comment by Caldis** [comment]
@ZbinH2O 检查了一下, 左右修饰键的 keycode 确实不一致, 已经修了, 下个版本一起发
