### ISSUE TITLE
Scrolling in Electron based apps stutters

### ISSUE THREAD

**Issue by pushqrdx** [Caldis/Mos#123]
**Describe the bug | 问题描述**
Smooth scroll in Electron/Chromium based apps is stuttering, You can see that in Spotify for example. Try to open a list in Spotify and you'll see that scrolling is jumpy.

**Expected behavior | 期望结果**
Smooth as in Safari.

**System Info | 系统信息:**
 - OS: High Sierra 10.13.6
 - Version: Latest Stable
-  Application: Chromium/Electron based applications.

**Comment by Caldis** [comment]
Some applications have been optimized for smooth scrolling, and these optimizations are only for the original mouse scrolling input, rather than smoothing the interpolated input, perhaps disabling Mos' smooth scrolling in these applications is a better option.

**Comment by pushqrdx** [comment]
@Caldis I wonder whether would be a way to inject Touchpad or MagicMouse input. Maybe lower level api manipulation so instead of smoothing the input you directly send smooth scroll input as if you really have a magic mouse?
The reason i am asking this is that on Windows such thing might have been possible through api hooking and i wonder if it's that different on mac os.

Either way, Mos is a great utility. Excellent work.

**Comment by Caldis** [comment]
Thank you for your kind words
I just tried to reproduce the problem you described in Spotify and found that smooth scrolling didn't cause any problems in any scrollable interface, and Spotify didn't do anything special for smooth scrolling.

**Comment by pushqrdx** [comment]
Could you please open the `Songs` specially with big list view and try it. If it works okay is there a way for me to log that behavior on my end so we can see what's causing it?

**Comment by Caldis** [comment]
@pushqrdx sorry i took so long to reply

But the stutters is not found in any interface in my environment. 
Maybe this is a compatibility issue in 10.13, it's hard to fix, or it's a performance issue in a particular environment. Due to some performance issues, the logging module has been removed and I will add it back after fixing these issues.
Maybe upgrading your OS version will solve the problem.

**Comment by pushqrdx** [comment]
@Caldis I did have same issue on Mojave. So, I'll be waiting for the profiler hoping to finally find a fix.
