### ISSUE TITLE
Do you plan to disabled mouse cursor acceleration?

### ISSUE THREAD

**Issue by zhaoxuan** [Caldis/Mos#124]

**Comment by Caldis** [comment]
Modifying the mouse pointer acceleration requires a lot of extra modifications to the underlying driver. If I using the CGEvent API used by Mos in current for this purpose, it will cause some performance problems.

There are already a bunch of applications in this area that are great, you can use them directly, for example:
- CursorSense
- ControllerMate
- SteelSeries ExactMouse (free)

**Comment by zhaoxuan** [comment]
Thanks, I have already used SteelSeries ExactMouse tools.
Mos is perfect, I didn't know that is hard to disabled mouse cursor acceleration.
Thank you again!

**Comment by Caldis** [comment]
@zhaoxuan Thanks for the kind words.
> By the way, want get more information about mouse acceleration, you can read the discussion at [Dae’s blog](https://dae.me/blog/2144/on-macos-sierra-support-and-the-future-of-smoothmouse/) , from the author of the `SmoothMouse`, which used to be the best mouse acceleration software.
