### ISSUE TITLE
magic mouse2 翻转方向没用

### ISSUE THREAD

**Issue by Ranglage** [Caldis/Mos#126]
**Describe the bug | 问题描述**
magic mouse2 翻转方向没用
**To Reproduce | 如何重现**
magic mouse2 翻转方向没用
**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - OS: Mojave 10.14.1
-  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
MM 输入的滚动事件特征与系统触摸板的一致, 这个目前并没有办法区分
