### ISSUE TITLE
Issue in getting the auto-updates

### ISSUE THREAD

**Issue by vk1712** [Caldis/Mos#128]
**Describe the bug | 问题描述** --- The app is really good but there is no way that i can receive any notification or automatic updates of the app. For updating the app, each time I have to come to git community and check it.

**To Reproduce | 如何重现** ---- It would be really nice if there is some ways in which we can receive auto updates for this app or at least an notification that there is a new update.  

**Expected behavior | 期望结果** ---- Notification about the new updates

**Screenshots | 相关截图**

**System Info | 系统信息:** -- Macbook Air 2018 - MacOS Mojave 10.14.3

**Additional context | 额外说明**

**Comment by Caldis** [comment]
Sparkle will be integrated into the next major update, thanks for your feedback.
