### ISSUE TITLE
github 滚动卡顿

### ISSUE THREAD

**Issue by allenmien** [Caldis/Mos#129]
**Describe the bug | 问题描述**
在浏览如下网页的时候，滑动停止，冷启动会出现卡顿现象：
https://github.com/zergtant/pytorch-handbook/blob/master/chapter2/2.4-cnn.ipynb
**To Reproduce | 如何重现**
如描述即可
**Expected behavior | 期望结果**
滑动流畅
**Screenshots | 相关截图**

**System Info | 系统信息:**
 - OS: [e.g. iOS]10.14.3
 - Browser [e.g. chrome, safari] chrome
-  Application [e.g. Safari, Chrome, Whole System] Chrome

**Additional context | 额外说明**

**Comment by Caldis** [comment]
确实有, 在文本区域滚动就会, 感觉是页面有个隐藏滚动条...

**Comment by allenmien** [comment]
是的，其实软件非常棒，是我已经长期使用了。都是小问题，类似的还有google的jupyter-notebook的滚动页面也是如此，好像jupyter-notebook这类的文件都是有这样的状况
