### ISSUE TITLE
Mos丝滑滚动失效

### ISSUE THREAD

**Issue by Wangll-Akk** [Caldis/Mos#130]
**Describe the bug | 问题描述**
2.3之前一直都很好用，自从装过一次2.4之后，mos的丝滑滚动的效果经常会消失，app没有关闭，但是滚动效果没有了，将mos关闭并重新打开后就可以了。不知道是不是2.4的bug，卸载重装2.3也会时不时出现，平均一天能出现个一两回吧
**To Reproduce | 如何重现**
莫名其妙的消失，不知道如何重现
**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - OS: macOS Mojave 10.14.3
-  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
@Wangll-Akk 应该是热键失效引起的问题, 新版本已经修复, 晚些时候放出

**Comment by Wangll-Akk** [comment]
后来已经发现了是热键导致的，现在禁用热键在使用，等新版本更了后会立马下载试用👍
