### ISSUE TITLE
使用一段时间后变成横向滚动

### ISSUE THREAD

**Issue by SuperYbc** [Caldis/Mos#131]
**Describe the bug | 问题描述**
 APP 使用一段时间后，鼠标滚轮会自动变成横向滚动，此时按住shift 才会纵向滚动，重启后恢复。
**To Reproduce | 如何重现**
无规则出现该bug
**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
-  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
@SuperYbc 应该是热键失效引起的问题, 新版本已经修复, 晚些时候放出

**Comment by freeliuzc** [comment]
> @SuperYbc 应该是热键失效引起的问题, 新版本已经修复, 晚些时候放出

你好，罗技MX Master2，这个问题还是存在
