### ISSUE TITLE
There's no any scroll in Calendar between months

### ISSUE THREAD

**Issue by inocster** [Caldis/Mos#132]
**Describe the bug | 问题描述**
Scroll does not work at system Calendar. Absolutely. I can't switch between months with scroll.
**To Reproduce | 如何重现**
Just install app. Nothing else special settings but default.  
**Expected behavior | 期望结果**
It would be nice to have a simple scroll (not smoothly) between months at least.
**Screenshots | 相关截图**

**System Info | 系统信息:**
macOS Sierra 10.12.6
Safari
12.0.3
-  Application [e.g. Safari, Chrome, Whole System]
System Calendar
**Additional context | 额外说明**
My device is Logitech MX Ergo with installed Options. I didn't uninstall Options before Mos.

**Comment by Caldis** [comment]
It seems the calendar app does not respond to any scroll events on the month page

**Comment by inocster** [comment]
Maybe it's a different event? I have magic mouse 2 and vertical scroll works fine between months.

**Comment by Caldis** [comment]
Yep, it only respond to touchpad event, and the magic mouse has same event with touchpad.

**Comment by le0-VV** [comment]
> Yep, it only respond to touchpad event, and the magic mouse has same event with touchpad.

所以日历app月份/年份页面是没法适配的是吗？ @Caldis
