### ISSUE TITLE
能不能隐藏顶部软件图标？

### ISSUE THREAD

**Issue by Aircus** [Caldis/Mos#134]
您好！
您做的这个小软件非常实用。就是有个小建议，能不能在设置里加一个选项，就是隐藏顶部图标？本人有轻微强迫症，不好意思啊

谢谢！
Tong

**Comment by Caldis** [comment]
没有关系, 按住 option 点击状态栏图标即可

**Comment by Aircus** [comment]
好的！十分感谢！

Mvh
Tong

在 2019年3月13日，18:44，Caldis <notifications@github.com<mailto:notifications@github.com>> 写道：


没有关系, 按住 option 点击状态栏图标即可
