### ISSUE TITLE
Adobe Acrobat Reader DC设置例外时仍无效

### ISSUE THREAD

**Issue by yantaozhao** [Caldis/Mos#135]
**Describe the bug | 问题描述**
2.4.0-beta 设置Adobe Acrobat Reader DC例外时仍无效.

**System Info | 系统信息:**

硬件概览：
  型号名称：	MacBook Pro
  型号标识符：	MacBookPro14,1
  处理器名称：	Intel Core i5

系统软件概览：
  系统版本：	macOS 10.14.2 (18C54)
  内核版本：	Darwin 18.2.0

**Additional context | 额外说明**

Adobe Acrobat Reader DC:
  Architecture: x86_64
  Build: 19.10.20098.316574
  AGM: 4.30.84
  CoolType: 5.14.5
  JP2K: 1.2.2.42832

**Comment by Caldis** [comment]
已知问题, 暂时没办法解决, 因为 Acrobat Reader DC 可能用了一些特殊方法来接收滚动, 导致 Mos 无法对其生效, 你可以把它添加到例外, 然后禁用平滑滚动

**Comment by hotbrave** [comment]
请问如何不收到这些邮件？




| |
brave
邮箱：hotbrave@163.com
|

Signature is customized by Netease Mail Master

在2019年03月23日 10:49，Caldis 写道：

已知问题, 暂时没办法解决, 因为 Acrobat Reader DC 可能用了一些特殊方法来接收滚动, 导致 Mos 无法对其生效, 你可以把它添加到例外, 然后禁用平滑滚动

**Comment by Caldis** [comment]
@hotbrave 点击这个页面右边的 Unsubscribe
