### ISSUE TITLE
預覽程式滾動時一次跳很多頁

### ISSUE THREAD

**Issue by simon0225** [Caldis/Mos#136]
**Describe the bug | 问题描述**
使用預覽程式開啟多頁檔案時，若以單頁或雙頁顯示，滾動一次滾輪頁面將會連續跳很多頁

**To Reproduce | 如何重现**
當使用預覽程式開啟一份多頁的pdf file，並以"單頁(cmd+2)"或"雙頁(cmd+3)"模式顯示
Ｍos使用預設的基礎與高級設定
滾動一格的滑鼠滾輪
頁面將會連續跳很多頁
閱讀上不太方便

**Expected behavior | 期望结果**
若以"單頁(cmd+2)"或"雙頁(cmd+3)"模式顯示：
滾動一格的滑鼠滾輪，頁面只跳一頁

若以"連續(cmd+1)"模式顯示：
正常的Ｍos滾動體驗

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - OS: [e.g. iOS] macOS 10.14.4
-  Application [e.g. Safari, Chrome, Whole System] Preview.app

**Additional context | 额外说明**
使用 Mos 2.4.0-beta

**Comment by Caldis** [comment]
请参考: https://github.com/Caldis/Mos/issues/11
