### ISSUE TITLE
关于设置禁用键导致一段时间后平滑滚动失效

### ISSUE THREAD

**Issue by liangjingkanji** [Caldis/Mos#137]
**Describe the bug | 问题描述**

设置禁用键之后一段时间后 平滑滚动失效

**To Reproduce | 如何重现**

设置禁用键之后一段时间后 平滑滚动失效, 但是此时按下禁用键平滑滚动又有效了, 放开又无效. 

**Expected behavior | 期望结果**

我猜测可能是设置反了

**Screenshots | 相关截图**

**System Info | 系统信息:**
-  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
你猜对了

**Comment by Caldis** [comment]
哥们你的昵称成功地把我逗笑了

**Comment by liangjingkanji** [comment]
Bug修复完, 我认你当表面兄弟
