### ISSUE TITLE
Tmux 下面滚动异常

### ISSUE THREAD

**Issue by cattyhouse** [Caldis/Mos#138]
**Describe the bug | 问题描述**
用的iterm2 配合tmux，滚动一下鼠标能翻100多行
**To Reproduce | 如何重现**
在tmux里面生成一点输出， 然后滚动鼠标
**Expected behavior | 期望结果**
期望可以滚动一下翻5行
**Screenshots | 相关截图**

**System Info | 系统信息:**
 - OS: [e.g. iOS] macOS 10.14.4
-  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
对于这类基于 **行/页** 滚动的软件请添加到例外中, 并对其禁用平滑, 请参考: #11

**Comment by cattyhouse** [comment]
iterm2 本身没问题，有问题的时候开启tmux之后，但是tmux是个命令不是个app，也可以添加到例外吗？

ps：只是把iterm2添加到例外，没有效果。

**Comment by Caldis** [comment]
我试了一下, 貌似在我的机器上开不开 tmux 好像看起来都一致 ...
这类命令行程序确实比较特殊, 你试着把持续时间调低, 看看有没有效果 ?

**Comment by cattyhouse** [comment]
我又测试了下, 把iterm添加到例外就好了.刚才可能没有重启mos和iterm所以设置没生效. 感谢!
