### ISSUE TITLE
滚轮滚动的时候,不能通过点击左键立即停止

### ISSUE THREAD

**Issue by xuanxuan321** [Caldis/Mos#139]
- 问题描述 |滚轮滚动的时候,不能通过点击左键立即停止

- 期望结果 |希望在滚动的时候,点击鼠标左键能立刻停止滚动

**Comment by Caldis** [comment]
本来也不能啊……

**Comment by alphaArgon** [comment]
Magic Mouse 和內建軌跡版都可以

**Comment by Caldis** [comment]
还真的有, 我一直没发现 ...
有空做成配置项吧

**Comment by xuanxuan321** [comment]
嗯，谢谢，感觉这个功能上了可以极大增强用户体验哈




    


在2019年04月16日 23:27，Caldis 写道： 还真的有, 我一直没发现 ...
有空做成配置项吧

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Caldis/Mos","title":"Caldis/Mos","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Caldis/Mos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Caldis in #139: 还真的有, 我一直没发现 ...\r\n有空做成配置项吧\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Caldis/Mos/issues/139#issuecomment-483710639"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Caldis/Mos/issues/139#issuecomment-483710639",
"url": "https://github.com/Caldis/Mos/issues/139#issuecomment-483710639",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/releases/tag/3.3.1
