### ISSUE TITLE
能否禁用掉 Launchpad 中的缓动效果

### ISSUE THREAD

**Issue by maxming2333** [Caldis/Mos#14]
设置如下：

![image](https://cloud.githubusercontent.com/assets/8816730/23906117/0b1546e0-0908-11e7-927f-3397a6978400.png)

目前设置了 `Launchpad.app` 的忽略，

但是当点击 `Launchpad` 图标后，再滚动鼠标，发现还是会有缓动效果，导致翻页不迅速

**Comment by Caldis** [comment]
已有反馈, 正在研究中
https://github.com/Caldis/Mos/issues/9

**Comment by Caldis** [comment]
已更新, 可以试试效果, 我机器上10.12已测试无问题

**Comment by SunWeihan** [comment]
建议默认禁用 Launchpad，或者下载时提醒一下

**Comment by Caldis** [comment]
@SunWeihan 好建议👍

**Comment by allenmien** [comment]
在10.15 BETA6中，launchpad使用鼠标滚动很慢的问题再次复现了。按照添加例外的方式也没有解决，麻烦作者看一下这个问题
