### ISSUE TITLE
Sketch.app 添加到例外中无效

### ISSUE THREAD

**Issue by funtrip** [Caldis/Mos#141]
**Describe the bug | 问题描述**
Sketch.app 添加到例外中无效，平滑滚动仍然存在。

**To Reproduce | 如何重现**
在例外列表中添加应用程序 Sketch.app

**System Info | 系统信息:**
 - OS: macOS X Mojave
 - Version 10.14.4 (18E226)
-  Application Sketch

**Additional context | 额外说明**
Sketch 版本 53.2

**Comment by Caldis** [comment]
感谢反馈, 我有空看下
