### ISSUE TITLE
I want to add finder.app to whitelist

### ISSUE THREAD

**Issue by tmyuan2017** [Caldis/Mos#142]
- 问题描述 | Issue description:
开启白名单模式，不能添加finder到list

- 如何重现 | How to reproduce it:
    开启白名单模式，不能将finder添加到名单中

- 期望结果 | What is expected:
    在finder中开启功能

- 实际结果 | What is actually happening:
     在应用程序中找不到finder

- 软件版本 | Application version:
    2.4.beta

- 系统版本 | System version:
    10.13.6

**Comment by Caldis** [comment]
Finder 在这里
```
/System/Library/CoreServices/Finder.app
```
