### ISSUE TITLE
当鼠标滚轮滚动的同时，将鼠标指针移向另一个应用，滑动被保留

### ISSUE THREAD

**Issue by MLYC** [Caldis/Mos#144]
- 问题描述 | Issue description:
当鼠标滚轮滚动的同时，将鼠标指针移向另一个应用，滑动被保留。例如：当我在网页里面滚动滚轮，页面开始滚动，我迅速将鼠标指针移向PhpStorm，PhpStorm里面的代码被滚动，我并不想它被滚动。smooze上不会有这个问题。

- 如何重现 | How to reproduce it:
按描述可重现，特别是动画时间长的时候。

- 期望结果 | What is expected:
每个应用窗口的滚动相互独立，彼此不影响。smooze上实现了。

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:
smooze

**Comment by Caldis** [comment]
@MLYC 抱歉才看到你的反馈, 这个建议很好, 实现上目前没有难点, 我会考虑增加一个配置项来让用户切换这个功能, 不过我也不想界面变的太复杂

**Comment by youngbeen** [comment]
有同样的困扰，个人认为这应该算得上一个“副作用”

**Comment by huanglusong** [comment]
同样受到这个问题的困扰，不知道开发者什么是否可以尽快实现这个功能

**Comment by the-eric-kwok** [comment]
+1
希望会有这个设置

**Comment by Caldis** [comment]
已更新, 目前滚动仅会保留在其产生的应用窗口中
https://github.com/Caldis/Mos/releases/tag/3.3.1
