### ISSUE TITLE
Apple TrackPad 妙控板/无线触控板2代垂直方向无法反转

### ISSUE THREAD

**Issue by kotlin360** [Caldis/Mos#147]
**Describe the bug | 问题描述**
您好，Apple TrackPad 妙控板/无线触控板2代，垂直方向无法反转

**To Reproduce | 如何重现**

**Expected behavior | 期望结果**
外接鼠标是符合中国人的习惯，但是Apple TrackPad 妙控板/无线触控板2代是反着的

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - OS: 10.14.4

**Additional context | 额外说明**
无

**Comment by Caldis** [comment]
外置的 TrackPad, Magic Mouse 与内置 TrackPad 都不会被处理, Mos 仅针对普通鼠标生效, 如果需要修改这类设备的滚动, 使用系统内置的设置选项即可
