### ISSUE TITLE
[Feature Request]请问能不能设置对特定的鼠标生效

### ISSUE THREAD

**Issue by SIDmao** [Caldis/Mos#148]
我有一个Magic Mouse和一个Microsoft Sculpt Comfort Mouse
然后我希望Magic Mouse能保持滚轮方向不变
Microsoft Sculpt Comfort Mouse能翻转滚轮方向
请问有没有可能实现 = =

**Comment by Caldis** [comment]
抱歉目前没有办法做到, Mos 基于事件层做检测, 而不是驱动层, 这也意味着无法区分普通设备间的差异.

不过, 系统中的滚动方向选项对所有设备生效, 而 Mos 内的翻转方向仅对普通鼠标生效, (MagicMouse 和触控板属于同一类设备, Mos 对其不生效)
因此如果需要区分 MagicMouse 和普通鼠标, 你可以试着修改一下系统的滚动方向和 Mos 里面的 "翻转方向", 试试看能不能调整出合适你的滚动效果
