### ISSUE TITLE
4K 显示器开启 Retina 后滚动卡顿

### ISSUE THREAD

**Issue by robertying** [Caldis/Mos#149]
**Describe the bug | 问题描述**

4K 显示器开启第二档 Retina 缩放（逻辑分辨率 2K）后，在 Chrome、Safari 以及 VSCode 中能感到明显的卡顿和滚动拖影。

关闭缩放，将显示器设置为默认分辨率，平滑滚动正常工作。

之前在 2K 显示器下手动开启 HiDPI 后，平滑滚动也能正常工作。

**System Info | 系统信息:**
 - OS: macOS 10.14.5
 - Browser [Chrome，Safari]
 - Version [Chrome 75]
-  Application [Chrome，Safari, VSCode]

**Comment by ChenLLE** [comment]
同样的问题。。

**Comment by Caldis** [comment]
大概率是机器性能不足, 我也有同样的场景, 这种情况下不论是触控板或是 Mos 都会丢帧

**Comment by robertying** [comment]
@Caldis 借了一个触控板，确实也会产生丢帧，看来不是 Mos 的问题。感谢解答！
