### ISSUE TITLE
使用后，鼠标按住 shift 横向滚动的功能失效

### ISSUE THREAD

**Issue by sivan** [Caldis/Mos#15]
按住 shift 滚动是横向滚动，开启 Mos 后失效。

**Comment by Caldis** [comment]
目前已经在Safari里发现了这个情况，还在研究中。

如果有更多的失效/生效场景希望补充， 暂时不知道是哪方面的问题

**Comment by sivan** [comment]
在 Chrome 里也这样，PhotoShop 里也是~

**Comment by Caldis** [comment]
更新到10.12.4之后没法重现了, 貌似按住Shift滚动是有效的...

**Comment by wyudong** [comment]
@Caldis 我更新到10.12.4之后仍然不能横向滚动。如果不勾选“平滑滚动”，按住 Shift 鼠标上下滚动，页面是可以左右滚动的。

**Comment by Caldis** [comment]
@wyudong 纠正一下上面我说的, 应该是:
在PS中按住command可以横向滚动

但是在Safari中按住shift中则不能, 我怀疑是处理机制的关系, 一时半会还不知道咋处理

**Comment by ace-huang** [comment]
勾选“平滑滚动”后，按住shift横向滚动失效，目前测试受影响的有：Finder、Safari、Firefox、Office系列。MacOS系统版本是10.11.6

**Comment by Freurso** [comment]
1.6版本，在Preview里 Shift横向滚动失效，系统10.12.6

**Comment by sivan** [comment]
我在想，如果横向滚动的问题原因比较复杂，是不是可以给 mos 加一个全局的快捷键开关，可以临时禁用一下？

因为横向滚动本来也不是特别高频的操作，看大尺寸页面和文档时才会用到。

**Comment by Caldis** [comment]
@sivan 
如果这样的话，我在处理逻辑中中手动将 Shift 按下后将滚动方向从 Y 轴转换为 X 轴的功能手动处理一次的话应该是可行的，但是不知道会不会在某些应用中有其他负面的影响
近期可能会作为一个测试功能加入

**Comment by hxfdarling** [comment]
在vscode中也不能横向滚动

**Comment by MeCKodo** [comment]
非常迫切这个功能，我在chrome里，vscode里都无法 shift+滚轮 横向滚动。！！！ 希望可以修复！修复后打赏了！ 这个应用非常好用！十分感谢

**Comment by Caldis** [comment]
Support on 2.2.0: https://github.com/Caldis/Mos/releases/tag/2.2.0

**Comment by sivan** [comment]
完美解决，赞！！👍

**Comment by lovelock** [comment]
我用的是2.3.0版本，居然没有发现这个选项
<img width="391" alt="image" src="https://user-images.githubusercontent.com/2208731/88504278-d29b5d80-d006-11ea-84ec-0bfa9ef271a5.png"> 这个名字取的有点过于隐晦了，没有仔细看下面的说明。

我就纳闷网上说的按住Shift再滚动这个方法怎么不好使呢，我就怀疑到底是我用了罗技Ghub还是因为MOS，原来是MOS托管了这个事件，而且默认给关掉了。是不是可以考虑默认打开呢？

**Comment by wydinhk** [comment]
> 我用的是2.3.0版本，居然没有发现这个选项
> <img alt="image" width="391" src="https://user-images.githubusercontent.com/2208731/88504278-d29b5d80-d006-11ea-84ec-0bfa9ef271a5.png"> 这个名字取的有点过于隐晦了，没有仔细看下面的说明。
> 
> 我就纳闷网上说的按住Shift再滚动这个方法怎么不好使呢，我就怀疑到底是我用了罗技Ghub还是因为MOS，原来是MOS托管了这个事件，而且默认给关掉了。是不是可以考虑默认打开呢？

同 找了半天原因发现没有默认开启
