### ISSUE TITLE
Crashes when Preferences selected

### ISSUE THREAD

**Issue by ultratiem** [Caldis/Mos#150]
Crashes when Preferences selected. Compiling on Xcode 10.2.1 provides a successful build and Mos starts normally. But once Preferences is selected, the app crashes. Xcode lists the following reason:

Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

**To Reproduce | 如何重现**
Compile Mos using Xcode 10.2.1

**Expected behavior | 期望结果**
Show Preferences Pane

**Screenshots | 相关截图**

**System Info | 系统信息:**
macOS 10.14.5 (18F132)

**Additional context | 额外说明**

**Comment by Caldis** [comment]
Maybe the new options value cause the problem, try using previous version to build
