### ISSUE TITLE
Scrolling on inactive window of an app which in exception of the scrolling feature

### ISSUE THREAD

**Issue by crgriseus** [Caldis/Mos#151]
**Describe the bug | 问题描述**
When I move my cursor to Adobe Acrobat for example from another window, the exception not working until I click on the window.

**To Reproduce | 如何重现**
1. Open Acrobat with multiple Pages inside
2. Open any other app
3. Close it
4. Now try to scroll in Acrobat's window without clicking on it.

**Expected behavior | 期望结果**
Working exception

**System Info | 系统信息:**
 - OS: High Sierra

**Additional context | 额外说明**

**Comment by Caldis** [comment]
It's the limitation of Adobe Acrobat. It using custom scrollview to render content pages. 
So the detection will only working when the window become activate.
