### ISSUE TITLE
双屏时隐藏Mos状态栏图标，在非活动屏幕会有空的占位

### ISSUE THREAD

**Issue by yew** [Caldis/Mos#152]
**Describe the bug | 问题描述**
双屏时隐藏Mos状态栏图标，在非活动屏幕会有空的占位

**To Reproduce | 如何重现**
双屏，隐藏Mos状态栏图标，观察费活动屏幕状态栏

**Expected behavior | 期望结果**
两个屏幕都可以正常隐藏图标

**Screenshots | 相关截图**
![Snipaste_2019-06-16_15-09-01](https://user-images.githubusercontent.com/12381485/59560724-0dcc0e80-9049-11e9-8040-9ce524c7866e.png)

**System Info | 系统信息:**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] None
 - Version [e.g. 22] Mojave 10.14.5 
-  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
貌似鼠标移上去就好了, 应该是系统不会自动更新非活动状态的屏幕状态栏, 这个我也没啥办法

**Comment by yew** [comment]
移上去也不会好: (
点击之后（也就是激活这个屏幕了）就好了
我还是让它显示图标吧，或者使用Bartender
