### ISSUE TITLE
Vertical and toggled Horizontal Scrolling is sometimes swapped

### ISSUE THREAD

**Issue by GregorBeyerle** [Caldis/Mos#153]
**Describe the bug | 问题描述**
Sometimes, after pressing my toggle "ctrl" to enable horizontal scrolling, it stays stuck in horizontal scrolling even after I let go of "ctrl". From that point onwards, pressing "ctrl" will toggle vertical scrolling, but not horizontal - Horizontal will be the new default scrolling now until I restart the app.

**To Reproduce | 如何重现**
Unfortunately, I haven't found a way to reliably reproduce this yet. Hope this issue sounds familiar to someone? 

**Expected behavior | 期望结果**
Vertical Scrolling should always be the scrolling behavior when no toggle key is pressed.
**Screenshots | 相关截图**

**System Info | 系统信息:**
 - OS: OSX 10.14.5
 - Browser = Opera, Chrome
 - Version = 2.3.0
-  Application = Whole System

**Additional context | 额外说明**

**Comment by laelsirus** [comment]
same issue
10.14.6

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/issues/207
