### ISSUE TITLE
翻转方向的水平滚动实在太慢了。

### ISSUE THREAD

**Issue by zuorn** [Caldis/Mos#155]
**Describe the bug | 问题描述**
水平方向的滚动实在太慢了。
**To Reproduce | 如何重现**

**Expected behavior | 期望结果**
希望可以自定义调节水平方向滚轮的相关参数
**Screenshots | 相关截图**
![image](https://user-images.githubusercontent.com/42893135/60311982-14814c80-998c-11e9-90a7-306b5b46802c.png)

**System Info | 系统信息:**
 - OS: macOS
 - Version ：10.14.5
-  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
明明两个方向的处理逻辑理应是一样的呀, 为什么会慢呢...... 你用的是什么神奇鼠标
