### ISSUE TITLE
Not working exception - Acrobat

### ISSUE THREAD

**Issue by qaywsxedcrfvtgb** [Caldis/Mos#156]
- 问题描述 | Issue description:
When I add acrobat to exceptions it works a while, but it stops and is smooth scrolling. Other apps exceptions works fine.

- 如何重现 | How to reproduce it:
Add acrobat to exceptions, forbid smooth scrolling and reverse, quit acrobat, open pdf, it is smooth scrolling, exception not working.

- 期望结果 | What is expected:
To add acrobat to exceptions

- 实际结果 | What is actually happening:
Not making exception

- 软件版本 | Application version:
2.3.0

- 系统版本 | System version:
10.14.5 (18F132)

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:
None

**Comment by Caldis** [comment]
Knowing issues, please ref: https://github.com/Caldis/Mos/issues/135#issuecomment-475832934
