### ISSUE TITLE
[Feature Request]: 键盘方向键的平滑滚动, smooth scroll with keyboard arrow-keys. 

### ISSUE THREAD

**Issue by linxucc** [Caldis/Mos#157]
- 问题描述 | Issue description:
这是一个Feature Request，鼠标的平滑滚动已经做得很好，但希望能够在此基础上加入键盘上下左右（或者仅上下）的平滑滚动，其实很多情况下，键盘滚动的laggy问题比鼠标滚轮严重得多…… 

- 如何重现 | How to reproduce it:
在需要滚动屏幕的场景，使用键盘方向键滚动屏幕。

- 期望结果 | What is expected:
滚动如使用鼠标一样平滑……

- 实际结果 | What is actually happening:
只有鼠标平滑，键盘不支持……

**Comment by Caldis** [comment]
键盘不仅仅用于滚屏，可能会影响游戏内的操作，或是应用中的焦点选择，用户需要花费更多事件来管理他们的例外应用

与其覆盖用键盘浏览页面的低频场景，我觉得还是避免引入潜在的问题来的更为划算

**Comment by linxucc** [comment]
了解了，确实，我们生产力用户一般都忘了还能玩游戏。。。
不过键盘的case太复杂了，包括是否是输入状态，还有像excel这样的应用，都有很多问题。

我最后使用了浏览器插件，效果也比较不错。我觉得你上面那段话可以加到FAQ或者Frequent Qusetions之类的地方（如果有）。

**Comment by Caldis** [comment]
@linxucc 确实可以录入 FAQ，感谢提醒
