### ISSUE TITLE
Add top bar to exceptions

### ISSUE THREAD

**Issue by yakimka** [Caldis/Mos#158]
- 问题描述 | Issue description:
  When using the Volume Scroll (program that can change volume level by scrolling on top bar area) in conjunction with MOS, Volume Scroll does not work. Adding top bar to exceptions would solve this problem.
  Video: https://youtu.be/5gUPQogA5gY
  Link to Volume Scroll: volumescroll.com

- 如何重现 | How to reproduce it:
  * install MOS
  * enable smooth scroll
  * install Volume Scroll
  * try to adjust volume to 100% by scrolling on top bar

- 期望结果 | What is expected:
Volume Scroll working normally

- 实际结果 | What is actually happening:
Volume is no longer regulated at some value.

- 软件版本 | Application version:
MOS: 2.3.0
Volume Scroll: 1.0.17

- 系统版本 | System version:
10.14.5

**Comment by Caldis** [comment]
Thank you @yakimka ! 
Good suggestions, but i need some time to figure out how to identification the top bar with the common applications。

**Comment by yakimka** [comment]
Thanks!. I will wait for the implementation.

**Comment by Caldis** [comment]
@yakimka Very lucky, the top bar is identifiable using the bundleId: `com.apple.systemuiserver`, i will add it to default exceptions.

**Comment by yakimka** [comment]
Wow, sounds great. I will look forward to the next version.

**Comment by Caldis** [comment]
Now you can manually adding ```com.apple.systemuiserver``` to exception list for identify volume bar
