### ISSUE TITLE
chrome上鼠标放到某些元素无法滑动

### ISSUE THREAD

**Issue by xiaojun1994** [Caldis/Mos#159]
**Describe the bug | 问题描述**

鼠标在某些元素时无法滑动

**To Reproduce | 如何重现**

https://www.mf8.biz/without-gfxstatus/#，请把鼠标放到评论区，划不动

**Expected behavior | 期望结果**

正常滑动

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - OS: macOS
 - Browser [e.g. chrome, safari] chrome 75.0.3770.100
 - Version [e.g. 22] Mojave 10.14.5
-  Application [e.g. Safari, Chrome, Whole System] Chrome

**Additional context | 额外说明**

**Comment by Caldis** [comment]
某些 iframe 区域好像是会阻塞滚动事件冒泡, 在 Github 的某些内嵌页面也会有这种问题 
由于问题与浏览器相关, 该问题暂时无解, 抱歉
