### ISSUE TITLE
acrobat pro dc启动平滑滚动，滚动速度特别快

### ISSUE THREAD

**Issue by Jiangshuyang** [Caldis/Mos#16]
我启用mos的平滑滚动后，其他软件都挺好的。可是偏偏acrobat pro dc滚动速度特别快，怎么可以解决这个问题？

1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 1.24863797426224, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 1.94092398881912, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 2.42881298065186, logsTag, 1, 5.0, 0.4862060546875, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 5.0
Pt X: 0.0
Fix Pt Y: 0.4862060546875
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 2.5077840089798, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 2.88903599977493, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 3.34297597408295, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 3.77079200744629, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 4.19689798355103, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 4.645034968853, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 5.08309000730515, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 5.52096700668335, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 5.94094896316528, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 6.35489100217819, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 6.7808690071106, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 7.1570720076561, logsTag, 1, 4.0, 0.35772705078125, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 4.0
Pt X: 0.0
Fix Pt Y: 0.35772705078125
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 7.24504297971725, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 7.57514399290085, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 7.9590579867363, logsTag, 1, 5.0, 0.485733032226562, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 5.0
Pt X: 0.0
Fix Pt Y: 0.485733032226562
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 8.03074097633362, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 8.34488797187805, logsTag, 1, 5.0, 0.404190063476562, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 5.0
Pt X: 0.0
Fix Pt Y: 0.404190063476562
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 8.43005895614624, logsTag, 1, 1.0, 0.100006103515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 1.0
Pt X: 0.0
Fix Pt Y: 0.100006103515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 8.66284197568893, logsTag, 1, 9.0, 0.84228515625, Is using TouchPad: false
Fix Y: 1.0
Fix X: 0.0
Pt Y: 9.0
Pt X: 0.0
Fix Pt Y: 0.84228515625
Fix Pt X: 0.0
, scrollWheelEventInstantMouser: 0.0
scrollWheelEventIsContinuous: 0.0
scrollWheelEventScrollCount: 0.0
scrollWheelEventMomentumPhase: 0.0
scrollWheelEventScrollPhase: 0.0
, eventTargetProcessSerialNumber: 249917.0
eventTargetUnixProcessID: 2799.0
eventSourceUnixProcessID: 0.0
eventSourceUserData: 0.0
eventSourceUserID: 0.0
eventSourceGroupID: 0.0
eventSourceStateID: 1.0
, 8.69646197557449

**Comment by wyudong** [comment]
See #11

**Comment by Caldis** [comment]
@wyudong 就是这样

@Jiangshuyang 建议直接添加进忽略列表里, 或者使用这种滚动模式:
<img width="159" alt="qq20170401-005355 2x" src="https://cloud.githubusercontent.com/assets/3529490/24560527/bb499c30-1675-11e7-8915-f739a706386c.png">

**Comment by Jiangshuyang** [comment]
好吧，多谢了

**Comment by Breezeore** [comment]
![image](https://github.com/Caldis/Mos/assets/83111713/2ca759a8-0785-4798-8913-2c102de6b12e)
