### ISSUE TITLE
horizontal toggle key not working majove

### ISSUE THREAD

**Issue by kkew3** [Caldis/Mos#161]
**Describe the bug | 问题描述**
I found a similar issue #125 but this is different. When I was using Macally keyboard and the builtin keyboard of macbook pro majove, I set the toggle key to Option. Recently I switched to Filco keyboard. Option key no longer works. I also tried out Command key, which didn't work either. Note that I switch the position of Option (Alt) and Command (Win) in system preference, since the keyboard is designed used by Windows.

Details on my trials:

| Toggle key set to | Press which key | Horizontal scrolling works or not |
|------------------|------------------|------------------------------|
| Shift | Shift | works |
| Ctrl | Ctrl | works |
| Command | Command | not works |
| Command | Option | not works |
| Option | Option | not works |
| Option | Command | not works |

**To Reproduce | 如何重现**
Set toggle key to Option. When using builtin keyboard, it works. When using Filco keyboard, it does not.

**Expected behavior | 期望结果**
Use Option key as toggle key when using Filco keyboard

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - OS: [e.g. iOS] macOS Majove 10.14.6
 - Browser [e.g. chrome, safari]: chrome; version 75.0.3770.142 (Official Build) (64-bit)
 - Version [e.g. 22]: Mos version 2.3.0
-  Application [e.g. Safari, Chrome, Whole System]: Whole System

**Additional context | 额外说明**
I don't have other keyboard to try. Not sure whether it's common for all Windows keyboard or not. At least Macally keyboard (designed for mac) does not have such issue.

**Comment by Caldis** [comment]
@kkew3 
It's quite a coincidence that I also have a Flico keyboard, but I usually use it on a PC. I just tried it in the development version of Mos, and the problem can't be reproduced because I refactored most of the code related to handling modifier keys. I hope this fix will also work for your keyboard.
