### ISSUE TITLE
一个很小的Bug,关闭平滑滚动只开启反向,在调整音量时用滚轮还是反着的

### ISSUE THREAD

**Issue by xiaoqiang179** [Caldis/Mos#164]
**Describe the bug | 问题描述**
一个很小的Bug,关闭平滑滚动只开启反向,在调整音量时用滚轮还是反着的
**To Reproduce | 如何重现**
只开反向,不开平滑就会这样
**Expected behavior | 期望结果**
同样可以反过来,不止Mos这个软件,其他的反向软件都有这问题

**Additional context | 额外说明**
我用的罗技G502鼠标,不知道别的鼠标有没有这个问题

**Comment by Caldis** [comment]
研究了一下, 这个问题修起来成本太高, 要额外加判断逻辑, 可能影响性能, 考虑到使用频率, 就先忽略了...

**Comment by Caldis** [comment]
新版本可以用 bundleId 来添加例外, 意外发现音量条也有独立的 bid, 于是添加 ```com.apple.systemuiserver``` 到例外就好了
