### ISSUE TITLE
可以增加一个去掉状态栏图标的选项吗？

### ISSUE THREAD

**Issue by ZoolYe** [Caldis/Mos#166]
**Describe the bug | 问题描述**
   强迫症用户，想作者增加个去掉状态栏图标的选项

**Comment by FateLight** [comment]
bartender3

**Comment by ZoolYe** [comment]
不想使用这样的工具，还是想程序能原生支持，非常感谢作者，我已经安利了身边的很多同事使用上了Mos，评价一级棒

**Comment by FateLight** [comment]
@ZoolYe 这个软件基本必备吧
