### ISSUE TITLE
chrome 浏览器 页面头部滚动不回弹

### ISSUE THREAD

**Issue by gongjunhao** [Caldis/Mos#167]
**Describe the bug | 问题描述**
chrome 浏览器 页面头部滚动不回弹 大白头
**To Reproduce | 如何重现**
滚动滚轮打开github、v2ex都出现这个问题，偶尔会出现，用触摸板滚动显示正常
**Expected behavior | 期望结果**
修复
**Screenshots | 相关截图**
![](https://imgchr.com/i/ntrNi6)
https://imgchr.com/i/ntrNi6
**System Info | 系统信息:**
 - OS: mac os
 - Version 2.3、2.4
-  Application [e.g. Safari, Chrome, Whole System]
Chrome
**Additional context | 额外说明**

**Comment by gongjunhao** [comment]
问题复现： 触摸板下滑同时滚动鼠标会复现

**Comment by Caldis** [comment]
@gongjunhao 谢谢反馈，终于找到触发原因了……

**Comment by Caldis** [comment]
新版本中已修复 https://github.com/Caldis/Mos/releases/tag/3.3.1
