### ISSUE TITLE
Mos在网易邮箱大师下，需要关闭平滑模式才能使用

### ISSUE THREAD

**Issue by ixiaoming** [Caldis/Mos#168]
- 问题描述 | Issue description:
网易邮箱大师下，需要关闭平滑模式才能使用

- 如何重现 | How to reproduce it:
打开收件箱，默认展示一小部分收信，使用鼠标向下滚动时，无法获取更多邮件。
使用MacBook Pro的触摸板向下滚动时，可以获取更多邮件。
关闭mos或关闭mos对网易邮箱大师的平滑滚动支持时，又可以用鼠标获取更多邮件了。

- 期望结果 | What is expected:
mos对网易邮箱大师开始平滑滚动可以获取更多邮件

- 软件版本 | Application version:
网易邮箱大师版本：V2.13.2.1260, Channel: Store, 
软件版本2.3.0

- 系统版本 | System version:
系统：版本 10.14.6（版号 18G95）

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:
无

**Comment by Leewiswind** [comment]
你这个问题。。我觉得例外添加一下，把平滑选项去掉，翻转留着应该可以。

**Comment by Caldis** [comment]
我直接使用普通的鼠标滚动貌似也无法触发他的滚动加载，反倒是触控板在底部区域稍微滑动一下就触发了，我感觉是不是鼠标的问题，你有安装 Logitech Options ？

**Comment by ixiaoming** [comment]
> 你这个问题。。我觉得例外添加一下，把平滑选项去掉，翻转留着应该可以。

是的，我现在就这么用的。

**Comment by ixiaoming** [comment]
> 我直接使用普通的鼠标滚动貌似也无法触发他的滚动加载，反倒是触控板在底部区域稍微滑动一下就触发了，我感觉是不是鼠标的问题，你有安装 Logitech Options ？

咱们的情况是一样的，鼠标不能触发滚动加载，触控板可以。
现在没安装其他的鼠标辅助软件，我觉得可能是mos和邮箱大师兼容性问题。
------
最后感谢您提供让macOS变得更好的工具

**Comment by Leewiswind** [comment]
> 我直接使用普通的鼠标滚动貌似也无法触发他的滚动加载，反倒是触控板在底部区域稍微滑动一下就触发了，我感觉是不是鼠标的问题，你有安装 Logitech Options ？

我有安装Logitech Options，在没装mos之前，我有时候也会出现滚轮方向不正确的情况，但是过一小会儿又变回正确设置的滚动方式，有可能是罗技驱动问题

**Comment by Caldis** [comment]
试了一下，网易这个客户端比较奇怪，貌似是独立检测触控板和鼠标的，我给鼠标事件设定了用于模拟触控板的部分参数之后网易客户端就能识别了
但这样其他应用会受到影响，Chrome 直接歇了...
