### ISSUE TITLE
在catalinabeta版本中无法运行的问题（已请大佬喝咖啡了）

### ISSUE THREAD

**Issue by simba22223** [Caldis/Mos#169]
**Describe the bug | 问题描述**
刚装时完美运行，但因为滑轮反向无法在虚拟机中实现，就按照下面链接的方法修改了滑轮参数，第一次将0（默认为0）改为1，没发生任何变化，又把1改为0，其它没进行任何操作，回到OS系统中，发现Mos所有功能已经失效，重装后仍不起作用。
 修改滑轮方法：
https://blog.csdn.net/james_616/article/details/78311510

**To Reproduce | 如何重现**

**Expected behavior | 期望结果**
希望能给一个解决的办法
**Screenshots | 相关截图**
<img width="225" alt="Snipaste_2019-09-22_12-37-27" src="https://user-images.githubusercontent.com/55645044/65382420-51fd3800-dd37-11e9-9991-89bafd96b08d.png">
<img width="325" alt=" " src="https://user-images.githubusercontent.com/55645044/65382423-5590bf00-dd37-11e9-9eb3-73dd0020434f.png">
<img width="397" alt="3" src="https://user-images.githubusercontent.com/55645044/65382424-59244600-dd37-11e9-95ce-4dc479c6bca0.png">

**System Info | 系统信息:**
 - OS: [e.g. iOS]虚拟机系统为win10 
-  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by simba22223** [comment]
监控动态
<img width="1170" alt="4" src="https://user-images.githubusercontent.com/55645044/65382441-ebc4e500-dd37-11e9-9a17-dc64fe290880.png">

**Comment by Caldis** [comment]
意思是在虚拟机中修改了注册表之后影响到了macOS中的Mos？感觉玄学了…

**Comment by Caldis** [comment]
你试试在 macOS 的辅助功能里面重新给Mos授权一下（去掉打勾再勾上）

**Comment by simba22223** [comment]
> 功能

还是不行、、、

**Comment by zicjin** [comment]
今天更新了 catalina beta9 后软件功能失效了。诡异的是当我重新授权“辅助功能”或重启程序的过程中会偶尔有效一段时间，但一段时间后又自动失效了。之前的 catalina 版本么有问题。

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/issues/206
