### ISSUE TITLE
新功能请求（如果大佬还维护的话）

### ISSUE THREAD

**Issue by L1cardo** [Caldis/Mos#171]
能不能加一个隐藏状态栏图标的功能，13寸的mbp表示状态栏不够用

**Comment by L1cardo** [comment]
我在代码里面发现了有隐藏状态栏图标的设置选项，但是我的mos设置里面没有啊！！
我人傻了！
![截屏2019-09-22下午8 20 51](https://user-images.githubusercontent.com/33802186/65387115-7a585700-dd76-11e9-816c-d7eb6861439b.png)
![截屏2019-09-22下午8 19 44](https://user-images.githubusercontent.com/33802186/65387097-53018a00-dd76-11e9-8e7e-66772dadc186.png)

**Comment by L1cardo** [comment]
我人又傻了。。。
https://github.com/Caldis/Mos/issues/134#issuecomment-472531712 这里找到了答案。。。

**Comment by L1cardo** [comment]
现在的隐藏状态栏的方法隐藏的太深，而且隐藏之后再显示太过于硬核，不符合正常人的使用习惯，如果有时间的话可以参考一下[这个项目](https://github.com/L1cardo/ClockBar)，做一个检点的checkbox来控制状态栏的隐藏和呼出

**Comment by Caldis** [comment]
@L1cardo 谢谢你的建议，隐藏图标做成 Checkbox 实际上没有问题，但之前把功能入口藏起来的主要原因就是没有找到比较好的方式来重新显示状态栏按钮
最近解决了这个问题，近期我发一个 Beta 测试一下 ...

**Comment by L1cardo** [comment]
@Caldis 嗯嗯  好的大佬，麻烦你了！

**Comment by luqinghui** [comment]
@L1cardo 你直接用一个管理状态栏的软件不就好了

**Comment by L1cardo** [comment]
@luqinghui 有推荐的吗，我用过的要么付费，要么就是不是很兼容，要么就是太花里胡哨。我就想简单的隐藏，需要的时候再显示

**Comment by luqinghui** [comment]
我在用的是[Dozer](https://github.com/Mortennn/Dozer)，你可以试一下

**Comment by luqinghui** [comment]
@L1cardo 我用的是[Dozer](https://github.com/Mortennn/Dozer)，你可以试试看。

**Comment by L1cardo** [comment]
@luqinghui 嗯嗯 ！ 谢谢啦

**Comment by Chandler-Lu** [comment]
> @L1cardo 谢谢你的建议，隐藏图标做成 Checkbox 实际上没有问题，但之前把功能入口藏起来的主要原因就是没有找到比较好的方式来重新显示状态栏按钮
> 最近解决了这个问题，近期我发一个 Beta 测试一下 ...

可以考虑一下popclip的方式，每次点击的时候出现状态栏图标。现在的方案会导致每次重启之后，总要弹出来一个通知，个人觉得有些不太好，谢谢～

**Comment by Caldis** [comment]
新版本已发布欢迎测试
