### ISSUE TITLE
滚轮缩放不平滑的问题

### ISSUE THREAD

**Issue by SunnyDeer1** [Caldis/Mos#172]
- 问题描述 | Issue description:
在使用option+鼠标滚轮，进行缩放操作时，缩放的速度过快，轻轻滚动，就会放到很大，或者缩到很小。
WPS、Skim、Adobe Acrobat 都会遇到类似的情况。

- 期望结果 | What is expected:
缩放操作可以稍微慢一点，平滑一点。

- 实际结果 | What is actually happening:
缩放速度过快。

- 软件版本 | Application version: 2.3.0
- 系统版本 | System version: MacOS Mojave 10.14.6

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/wiki/已知问题#在某些软件中一次滚动会滚动很多页行
