### ISSUE TITLE
如何添加应用包里面的应用为例外

### ISSUE THREAD

**Issue by Nojike** [Caldis/Mos#177]
**Describe the bug | 问题描述**
比如calibre里面的ebook-viewer，在程序里右键没有打开包内容。
**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
 - Version [e.g. v69]
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
新版本可使用 bundleID 添加
