### ISSUE TITLE
Not support in New Mac OS 10.15 Catalina

### ISSUE THREAD

**Issue by khanhvu14** [Caldis/Mos#178]
Mouse not scroll smooth on new MacOS

**Comment by lvhe19880210** [comment]
same here

**Comment by charlzyx** [comment]
samehere

**Comment by Caldis** [comment]
Try to reauthorization Mos in accessibility (Uncheck and check again)

**Comment by IFierta** [comment]
> Try to reauthorization Mos in accessibility (Uncheck and check again)

I tried to reauthorize the application, reinstall, cleaned the configuration files. Nothing helped. In the launchpad, scrolling works poorly (with a delay).

**Comment by inocster** [comment]
Cannot agree with this. The app works fine as before 10.15. I've got a smooth nice scrolling. But I did a clean install of macOS Catalina and did not connect my trackpad. Just a mouse.

**Comment by seagle0128** [comment]
Same here. Sometimes it works again after restarting it.

**Comment by getjake** [comment]
It works on Catalina

**Comment by seagle0128** [comment]
Sometimes the smooth scrolling stops working, just on Catalina.

**Comment by iJonathan-Dev** [comment]
Having issue with catalina just like @IFierta , launchpad scrolling is laggy. Trying to add the launchpad to exceptions, but it doesn't help. Apart from that this app is cool

**Comment by eko133** [comment]
> Having issue with catalina just like @IFierta , launchpad scrolling is laggy. Trying to add the launchpad to exceptions, but it doesn't help. Apart from that this app is cool

Just compile the latest repo using xcode. The scrolling in launchpad works fine now.

**Comment by Caldis** [comment]
Some issues have been fixed in version 3.0.0, but for macOS Catalina compatibility issues, please follow here https://github.com/Caldis/Mos/issues/207
