### ISSUE TITLE
能否提高最大滚动速度?

### ISSUE THREAD

**Issue by xdxdy** [Caldis/Mos#18]
我在10.12下有一个 bug, 就是外接鼠标的滚轮速度始终只有10, 系统偏好设置里面怎么调都没用, 用了您的软件之后, 速度能到50了, 不过还是太慢, 希望能更好一点. 

感谢开发者😭

**Comment by Caldis** [comment]
没问题, 我将上限适当提高

**Comment by xdxdy** [comment]
我用您的滚动监控测了一下 smoothScroll 的速度, 感觉有两个方面的建议.

一个是滚轮加速度, 我用smoothScroll(默认设置)的时候, 缓慢滚一格是10, 快速连续滚动, 速度就会飙升到200. 而 Mos 就不会这样, 快速连续滚动的最高速度还会在50左右. 如果加上滚轮加速度的话, 应该可以短距离精确定位和长距离快速滚动之间取得平衡.

第二个就是动画延时, 您的延时曲线, 开始运动的时候坡度比较缓, 这就显得滚动有延时, 不是很顺手.

**Comment by Caldis** [comment]
@xdxdy 
加速度这块跟算法有关, 这个需要后续优化了, 这个问题我其实很早就注意到了
关于曲线, 其实用于插值的平滑曲线的峰值和前后端的曲率其实都是可调的, 具体可以看这里:
https://github.com/Caldis/Mos/blob/master/Mos/ScrollCore.swift#L55
不过暂时没有做在UI里面, 因为这块如果没有将曲线可视化出来的话, 调整起来会比较抽象...

**Comment by Caldis** [comment]
@aduxhi https://github.com/Caldis/Mos/releases/tag/1.6.0
1.6.0 版本已提高了速度上限, 且峰值位置也可调

**Comment by balthild** [comment]
更新到 2.3 后，峰值位置不再可调了。

**Comment by Caldis** [comment]
@balthild 因为后来改了算法, 也就没有这个东西了

**Comment by balthild** [comment]
好吧，只能先暂时先用回旧版了。

不过我还是有些希望能加上选择不同算法的功能，之前用惯了 SmoothScroll 那种没有加速的滚动……
