### ISSUE TITLE
开启mos之后，触摸板双指滑动出现问题，滑动后页面飞速略过，SmoothScroll无此问题

### ISSUE THREAD

**Issue by yoheRabit** [Caldis/Mos#180]
**Describe the bug | 问题描述**
如题，开启mos之后，触摸板双指滑动出现问题，滑动后页面飞速略过，SmoothScroll无此问题

**To Reproduce | 如何重现**
在Catalina安装并使用mos,原使用mojave时这个问题也存在

**Expected behavior | 期望结果**
希望不影响触摸板的双指滑动，毕竟不需要鼠标大规模操作时，有时拉一下触摸板会更快。

**Screenshots | 相关截图**
无法截图

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
Logitech G304

macOS Catalina

chrome, safari

 - Version [e.g. v69]
 -  Application [e.g. Safari, Chrome, Whole System]
均为当下最新版本，截止10.16

**Additional context | 额外说明**

**Comment by Caldis** [comment]
是黑果么, 如果不是的话, 能否反馈一下你的机型
这个问题可能要抓滚动事件才能修

**Comment by Caldis** [comment]
黑果暂时没解, 这个跟 Mos 的事件判断方式有关, 你暂时只能用 SmoothScroll 代替了

**Comment by yoheRabit** [comment]
谢谢。目前还在用Mos。触摸板功能有限，还是要依赖鼠标。感谢你为Mos所做的努力。
