### ISSUE TITLE
在滚动的时候向同方向移动鼠标 会出现指针移动然后回到原来位置

### ISSUE THREAD

**Issue by chao-luo** [Caldis/Mos#181]
**Describe the bug | 问题描述**
在滚动的时候向同方向移动鼠标 会出现指针移动然后回到原来位置

**To Reproduce | 如何重现**
在滚动的时候向同方向移动鼠标

**Expected behavior | 期望结果**
指针不回来

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: Logitech G403
 - OS: 10.14.6
 - Browser chrome
 - Version 77.0.3865.90
 -  Application Whole System

**Additional context | 额外说明**
有时候并不需要滚动，也会出现移动鼠标然后指针移动了然后又回来

**Comment by Caldis** [comment]
无法重现, 会不会是跟其他软件冲突了
