### ISSUE TITLE
希望能加入鼠标侧键的功能

### ISSUE THREAD

**Issue by yanjieee** [Caldis/Mos#182]
用的带侧键的鼠标，习惯性上侧键是前进，下侧键是后退，不知道能不能加入这个功能。

**Comment by zhuxiaoxi** [comment]
可以试一下这个，我用了很久 https://github.com/archagon/sensible-side-buttons

**Comment by yanjieee** [comment]
> 可以试一下这个，我用了很久 https://github.com/archagon/sensible-side-buttons

嗯，现在也用这个了，可惜他不能自定义侧键。

**Comment by nanL** [comment]
可以试试这个：SteerMouse  https://plentycom.jp/en/steermouse/
自定义按键功能很好用，就是价格有点贵。

**Comment by Caldis** [comment]
目前希望 Mos 只专注做滚动平滑相关的部分, 至于按键绑定这个坑太大了, 暂时没有余力去做 ...
(或许哪天)
