### ISSUE TITLE
例外的应用程序列表无法添加Java应用

### ISSUE THREAD

**Issue by CycleDM** [Caldis/Mos#184]
**Describe the bug | 问题描述**
例如当我在macOS上玩Minecraft时，实际上启动的是java控制台程序，而Mos的例外应用程序无法添加“java”（资源库中的应用无法选中），这导致在macOS上玩Minecraft时很不方便。
**To Reproduce | 如何重现**
尝试添加Minecraft所依赖的java控制台程序。
**Expected behavior | 期望结果**
例外应用程序可以添加java应用。
**Screenshots | 相关截图**
![image](https://user-images.githubusercontent.com/54836831/67156457-bf61b000-f359-11e9-9783-ba4c66e757db.png)
![image](https://user-images.githubusercontent.com/54836831/67156474-eb7d3100-f359-11e9-8930-68d958a1d26d.png)

**Comment by anamewing** [comment]
同样遇到了此问题（也是为了玩minecraft），看起来在 v3.0 中似乎依然暂未能修复？
https://github.com/Caldis/Mos/issues/206#issuecomment-569066984

**Comment by Caldis** [comment]
谢谢反馈, 新版已修复 https://github.com/Caldis/Mos/releases/tag/3.3.1
