### ISSUE TITLE
滚轮滑动在launchpad中出现滑动延迟

### ISSUE THREAD

**Issue by El1ter** [Caldis/Mos#187]
**Describe the bug | 问题描述**
macOS 15.0 catalina中，进入launchpad页面滑动滚轮进行翻页时，画面出现严重滞后
**To Reproduce | 如何重现**
进入launchpad页面滑动一下滚轮进行翻页就可以重现
**Expected behavior | 期望结果**
让页面和鼠标的滑动动作同步响应
**Screenshots | 相关截图**
无
**System Info | 系统信息:**
 - Mouse: [Logitech M558]
 - OS: [MacOS]
 - Browser [Chrome]
 - Version [10.15]
 -  Application [launchpad(启动台)]

**Additional context | 额外说明**

**Comment by jayceehu** [comment]
一样,设置启动器例外也没用

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/issues/206
