### ISSUE TITLE
能不能增加一个桌面滚动功能呢

### ISSUE THREAD

**Issue by aiyuchen** [Caldis/Mos#188]
按住某个键（比如contorl），滑动滚轮后，可以切换到下一个或上一个桌面

**Comment by Caldis** [comment]
建议直接在系统设置里面绑定快捷键比较方便...

**Comment by zengcai** [comment]
> 建议直接在系统设置里面绑定快捷键比较方便...
希望可以直接通过鼠标切换桌面而不需要键盘的配合(比如：光标靠屏幕下边缘时滚动滑轮切换桌面)

**Comment by zengcai** [comment]
> 建议直接在系统设置里面绑定快捷键比较方便...

希望可以直接通过鼠标切换桌面而不需要键盘的配合(比如：光标靠屏幕下边缘时滚动滑轮切换桌面)
