### ISSUE TITLE
来鼓励鼓励作者

### ISSUE THREAD

**Issue by newpanjing** [Caldis/Mos#19]
很不错的一个软件，期待很久了，之前一只用的收费的破解版～

**Comment by Caldis** [comment]
@newpanjing 谢谢你喜欢MOS~

**Comment by leo-yi** [comment]
有计划出windows版本的吗？感觉这个软件可以成为必备的一个软件，或者说，windows版本的需要什么帮助？

**Comment by Caldis** [comment]
@leo-yi windows下的鼠标滚轮表现我感觉并没有mac下用鼠标滚轮那么不堪，加之各个浏览器的windows版本也有自带的鼠标滚动平滑，所以暂时还没有windows版本的打算。😂
