### ISSUE TITLE
Mos改动鼠标的滑轮方向

### ISSUE THREAD

**Issue by oucystong** [Caldis/Mos#191]
**Describe the bug | 问题描述**
我使用的是罗技的M590鼠标，使用options软件自定义好每个功能键，并未设置鼠标的平滑滚动功能，因为mos与他不兼容，所以我紧紧通过options软件设置了功能键，准确适应mos来平滑鼠标的滑动功能，但是用着用着突然滑轮的滚动失灵了，我一度认为是options软件和鼠标的问题，但是我测试一个pdf文件，把pdf文件放大，滑动鼠标可以看到pdf文件左右滑动，而不是上下滑动，在网页里因为没缩放，所以看到是滚动失灵，实际上滑轮已经改变为左右方向了，不再是上下方向了，退出mos在进入又可以使用了，可能mos中存在潜在的bug，建议大佬们有空检查一下，谢谢！
**To Reproduce | 如何重现**
一下午出现了两次这样的bug。不知道怎么复现。
**Expected behavior | 期望结果**
使用mos的平滑过度我想实现上下方向的，不是左右方向的，希望不要在篡改鼠标的方向了。
**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master] Logitech M590
 - OS: [e.g. iOS]Mac OS
 - Browser [e.g. chrome, safari] chrome safari
 - Version [e.g. v69]2.3.0
 -  Application [e.g. Safari, Chrome, Whole System]whole system

**Additional context | 额外说明**

**Comment by Rainyn** [comment]
@oucystong 
同款鼠标，遇到相同问题。目前问题已解决。
解决方案：mos 恢复使用2.3.6版本，同时Mac设置中安全性与隐私-辅助功能，重新添加罗技鼠标的那两项。重启就可以了

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/issues/206
