### ISSUE TITLE
打开Mos之后，鼠标放到在Safari的网页Tab栏的滚动功能失效。

### ISSUE THREAD

**Issue by hanhiver** [Caldis/Mos#192]
**Describe the bug | 问题描述**
打开Mos之后，鼠标放到在Safari的网页Tab栏的滚动功能失效。

**To Reproduce | 如何重现**
1. 打开Safari网页浏览器，多开一些Tab直到部分Tab被收缩隐藏。
2. 在没有Mos运行的时候，鼠标悬停在Tab栏滚动滚轮，可以滚动Tab栏，让隐藏的Tab可以滚动出来以供选择。
3. 打开Mos运行，鼠标悬停在Tab栏，滚动鼠标滚轮，无效果。
4. 打开Mos，触摸板的滚动在Tab栏依然有效。

**Expected behavior | 期望结果**
期望打开Mos和系统默认的行为一致，都能够滚动Tab栏。

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master] 
Mi Mouse. 
Darwin Kernel Version 18.7.0
Safari
 - Version [e.g. v69]
Version 13.0.1 (14608.2.11.1.11) 
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
似乎浏览器会在这里自动将元素的纵向滚动转换成横向的, 经过 Mos 处理之后好像就失效了, 你可以试试左右拨滚轮, 或者按转换键之后再上下滚轮

**Comment by hanhiver** [comment]
是的，浏览器在这里自动的将元素的纵向滚动变成横向了，尝试用快捷键切换上下滚动为左右滚动有效，浏览器的tab页面可以自动滚动了。目前的Workaround可以是用快捷键切换，不过是否能有自动判别的完美解决方案呢？ 谢谢！

**Comment by Caldis** [comment]
目前应该没有办法进一步区分应用内的框架元素...这样运行效率太低
