### ISSUE TITLE
Shift / Horizontal scroll getting stuck in 2.4.0 beta

### ISSUE THREAD

**Issue by momomo** [Caldis/Mos#195]
Nice that there is a ability to scroll horizontally as well as disable scroll for when zooming on google maps or photoshop for instance! 

great! 

but currently it is not working perfectly. it is buggy, but yes it is a beta. 

the key seems to get stuck. 

i would like to contribute if someone could help me get started with the code. 

thank you! 

**Describe the bug | 问题描述**

**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
 - Version [e.g. v69]
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by momomo** [comment]
this is true for 2.3.0 non beta as well.

**Comment by momomo** [comment]
seems like the shift key for horizontal is getting stuck.

**Comment by jt3k** [comment]
same error, fix it plz ! :((
