### ISSUE TITLE
Exception menu is not working with Steam Apps

### ISSUE THREAD

**Issue by Tiefflieger** [Caldis/Mos#198]
**Describe the bug | 问题描述**
It is not possible to use exception with steam apps like Counterstrike Global Offensive
**To Reproduce | 如何重现**
add /Users/*user*/Library/Application Support/Steam/steamapps/common/Counter-Strike Global Offensive command 
csgo_osx64 unix command line to exceptions
generation desktop app also doesn't work (Steam right click -> Add to desktop)
**Expected behavior | 期望结果**
adding app to exception menu
**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech G900]
 - OS: [e.g. MacOS 10.15]
 - Browser [e.g. safari]
 -  Application [Steam -> Counterstrike Global Offensive]

**Comment by Caldis** [comment]
Added two options in the 3.0.0 for adding exception apps
