### ISSUE TITLE
Add an option to display or hide the status bar icon?

### ISSUE THREAD

**Issue by maundytime** [Caldis/Mos#199]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**
因为缺少设置，Mac状态条往往很拥挤。可以隐藏吗？
Status bar icons may be too many. May we hide it?

**顺带说说你的新点子 | Describe the solution you'd like**
可以增加一个设置，设定是否显示status bar icon吗？
Could we add an option to display or hide the status bar icon?

**对了，还有别的替代方案吗？ | Describe alternatives you've considered**
比如Bartender可以隐藏，收费较贵。
Some app could hide status bar icons.

**额外说明 | Additional context**
Thank you.

**Comment by hrvstr** [comment]
Just hold the ALT/OPTION key and click on the status bar icon. It will show up as an option.

https://github.com/Caldis/Mos/issues/113#issuecomment-441682047

You can also use Dozer: https://github.com/Mortennn/Dozer
