### ISSUE TITLE
作者是不是可以考虑可以出一个黑名单模式？这样就不每次把新安装的应用添加白名单了

### ISSUE THREAD

**Issue by zhangzizhao404** [Caldis/Mos#204]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**
启动台使用这个左右滑动会有问题，反应超级慢，但是开了白名单模式把启动台加过去，去掉对勾就会恢复正常了，mac os 15

**Comment by Caldis** [comment]
测试版已修复, 可以试一下

**Comment by zhangzizhao404** [comment]
> 测试版已修复, 可以试一下

感谢
