### ISSUE TITLE
3.0.0 Public Testing

### ISSUE THREAD

**Issue by Caldis** [Caldis/Mos#207]
## The latest version has published, please download the new version directly.
   
https://github.com/Caldis/Mos/releases

---

<details>
  <summary>Legacy Content</summary>
  
  # Congratulations

You finally get here !

### Why here ?

I believe that the users who find here are have an unusual spirit of exploration. We welcome you to join in the public testing.

In fact, if you have notice the code already existed, you can find that the code for 3.0.0 is already ready, but it has not been released due to various problems.

Due to the long interval from previous version, it involves changes in multiple configuration items, and the new restriction of macOS 10.15 requirements for Notarizing has caused more trouble.

### Why testing ?

In fact, the new features are not the focus of this test (but you can also feedback below), we are more concerned about the following points

- Due to major changes in configuration items, if you encounter errors during operation, please provide feedback below

- As Apple has added Notarizing requirements before application release in the latest version of macOS, developers are required to join Developer Program for notarization ** ($ 99) **

Obviously, those compiled version has not been Notarizing. If you getting any problems, please feedback below

If nothing happens after double-clicking the icon, you can try the following solutions

```
Right click on the application and select Open
Remove Mos form accessibility
When you see the alert about 'Can’t be opened because...' after opening the mos, Click the '
Open Anyway' button form 'Security&Privacy-General-Allow apps downloaded form'
```

If you have any other solution, please feedback below.

If those above solution can help you to run successfully, please also feedback below, we will release the official version as soon as everything is ready.

Thanks for join in the test

> [Please click here to download the test version](https://raw.githubusercontent.com/Caldis/Mos/master/Release/Mos.Versions.3.0.0.dmg)
</details>

**Comment by khanhvu14** [comment]
I'm testing... It work perfectly 👍 .

Thanks you so much.

**Comment by andtos90** [comment]
Same here, after 2 days no problem whatsoever :ok_hand:

**Comment by vk1712** [comment]
Hi Caldis/Mos,

I am not able to open the download link.
Any help here?

For your reference
[image: image.png]

Regards,
Vishal Kumar [A big fan of MOS]
(+91) 8861 294750

**Comment by Caldis** [comment]
@vk1712 You can clone the project directly, and the released files are placed in the [Release](https://github.com/Caldis/Mos/tree/master/Release) directory

**Comment by divyanshu013** [comment]
Works great on Catalina 💛

**Comment by philrp** [comment]
I'm testing under Mojave 10.14.6, and all seems great.

I think I'm noticing that the smooth scrolling is better than under 2.3 or 2.4, but that could just be me.

Thank you so much for this.

**Comment by nlenkowski** [comment]
Can confirm all is well in Catalina 10.15.3.

Thanks for maintaining Mos @Caldis, I couldn't use an external mouse on the Mac without it!

**Comment by KhushrajRathod** [comment]
@Caldis 
Hi 👋.
I've been using Mos 3.0.0 for the past 4 months, and I've seen no issues so far!
Any timeline on when 3.0.0 will be released as stable?
Thanks.

**Comment by willerbee** [comment]
My feedback for v3.0.0 public testing:

All my past issues has been fixed! But there's a new one:

When I put my display to sleep and then I wake it up at some point, scrolling still works great, however BetterTouchTool can't seem to catch the scrollUp or scrollDown triggers anymore until I close Mos and open it up again. :)

Thank you @Caldis for blessing us this gem

**Comment by idanmashaal** [comment]
Hi, @Caldis ,

I'm using v3.0.0 and it works as expected on both my MacMini 2018 and MBA 2020.
Both are running Catalina 10.15.5.
I found one issue and it's with the Dock. If I have a folder in the dock, for example "Downloads" or "Applications" the scrolling is not smooth at all.
I think that Launchpad is the same but not sure, it's horizontal scrolling anyways..

Is there something that can be done to fix this for the dock?

Thanks, Idan.

**Comment by sn0wyfall** [comment]
This is great, solved the MX Master 3 bugs I was having with the Logitech Options software! Thanks a ton. I was fearing I'd have to move over to Smooze or something.

**Comment by sn0wyfall** [comment]
> Hi, @Caldis ,
> 
> I'm using v3.0.0 and it works as expected on both my MacMini 2018 and MBA 2020.
> Both are running Catalina 10.15.5.
> I found one issue and it's with the Dock. If I have a folder in the dock, for example "Downloads" or "Applications" the scrolling is not smooth at all.
> I think that Launchpad is the same but not sure, it's horizontal scrolling anyways..
> 
> Is there something that can be done to fix this for the dock?
> 
> Thanks, Idan.

I'm getting this too! It's a pity, I liked having smooth scrolling there. It definitely used to work in the previous version.

**Comment by sn0wyfall** [comment]
I realized this is only an issue on my main display. There is smooth scrolling in the Applications folder on my monitor. Interesting...

**Comment by idanmashaal** [comment]
On my MacMini there is only one monitor (the external one) and the smooth scrolling on the Dock pinned folders (Applications/Downloads/etc) is it working. 

Anywhere else it’s smooth. It’s very interesting... 
@Caldis do you think this can be easily fixed in v3 ?

**Comment by sn0wyfall** [comment]
It stopped being smooth on my external monitor's dock lol

**Comment by techguy9** [comment]
So far so good on macOS 11 👍

**Comment by Caldis** [comment]
The version 3.0 code sign for testing has expired, please download the new version directly
https://github.com/Caldis/Mos/releases/tag/3.1.0

**Comment by willerbee** [comment]
Thank you Caldis! <3
