### ISSUE TITLE
在office2016里面滚动还不是那么平滑，能解决一下吗？

### ISSUE THREAD

**Issue by yff0216** [Caldis/Mos#21]
在office里面滚动还不是那么平滑，能解决一下吗？

**Comment by wyudong** [comment]
禁用比启用好些吗

**Comment by yff0216** [comment]
我用的是mx master 2s 禁用之后，更加不好用

**Comment by Caldis** [comment]
@yff0216 
方便详细描述一下Office的版本和具体场景吗

**Comment by yff0216** [comment]
office2016，编辑普通excel，滚动的时候会滚少了不动，滚多了跑的快了点。
不像触摸板那样，可以一行一行的滚动。谢谢

**Comment by Caldis** [comment]
看看 Logitech Options 里面的平滑滚动有没有关掉

**Comment by yff0216** [comment]
@Caldis罗技选项里面是关闭状态。在滚轮向上滚动的时候明显一些，向下的时候正常。会是哪里的问题呢？谢谢

**Comment by yff0216** [comment]
鼠标是mx master 2s

**Comment by Caldis** [comment]
@yff0216 会不会是由于 Excel 内容太丰富引起的?
我试着用模板新建了几个试了下, 都挺流畅的

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/issues/37
