### ISSUE TITLE
能否增加鼠标中键模拟触摸板三指的功能

### ISSUE THREAD

**Issue by dicrm** [Caldis/Mos#211]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**

**说说你的新点子 | Describe the solution you'd like**

**还有别的替代方案吗？ | Describe alternatives you've considered**

**额外说明 | Additional context**

**Comment by Caldis** [comment]
你可以试试这个
https://github.com/cl3m/MiddleClick

**Comment by dicrm** [comment]
他实现的是三指触摸实现鼠标中键，跟我说的刚好完完全全反过来。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Caldis"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月3日(星期二) 凌晨0:00
收件人:&nbsp;"Caldis/Mos"<Mos@noreply.github.com&gt;;
抄送:&nbsp;"DICHEN"<di168@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Caldis/Mos] 能否增加鼠标中键模拟触摸板三指的功能 (#211)




你可以试试这个
 https://github.com/cl3m/MiddleClick

**Comment by Caldis** [comment]
🤣🤣 好吧，没仔细看标题
手势这块API暂时没空研究了，你可以找找别的替代软件
