### ISSUE TITLE
Chrome 网页刷新一次后, 页面可以上下无限滚动

### ISSUE THREAD

**Issue by suxiaogang** [Caldis/Mos#213]
**Describe the bug | 问题描述**
首先感谢开发者的辛苦工作, 并且Launch Pad的bug终于在3.0.0修复啦.

在Chrome中刷新某个网页之后, 页面就可以用鼠标中键上下无限滚动了 (不知道我这个描述对不对, 就是用鼠标滚轮滚到顶之后, 页面还可以无限制的继续往上滚动, 下面有图片说明)

已经确定是Mos的锅... 我关掉Mos, 原生的Chrome环境下没有这个问题

**System Info | 系统信息:**
 - Mouse: Logitech M557
 - OS: macOS 10.15.2 (19C57)
 - Browser: Chrome 79.0.3945.88
 - Version: 3.0.0

![image](https://user-images.githubusercontent.com/1567518/71431067-5c4e1a00-270a-11ea-8e60-4d73a7a8e256.png)

上面图片中黑色框部分就是"无限滚动"的部分, 并且还可以继续滚动...

**Comment by suxiaogang** [comment]
更新一下标题 与开发者模式无关, 只要在Chrome下刷新网页就会有这个问题.

**Comment by Caldis** [comment]
之前有其他用户反馈过, 应该是与触控板同时滑动会触发这个问题, 我这边有很低的几率会触发

**Comment by linking2014** [comment]
我刚才测试了一下，在打开新链接（页面还是白屏）的时候，向上滚动鼠标就会这样

**Comment by suxiaogang** [comment]
这个bug怎么说呢, 一般的使用场景下打开一个网页后短时间内很少会再次刷新当前网页.

但是当(前端)开发者在调试网页时恰恰会很频繁的刷新同一个网页. 我这里基本上每天碰到这个bug几百次, 每次只能通过 > 复制当前tab然后再关闭当前tab 来解决...

**Comment by linking2014** [comment]
我也是前端开发，大概每天遇到十几次吧😂

**Comment by luckyyyyy** [comment]
这个问题可以100%复现，并且是在chrome 70+某个版本更新后。
其他应用无此BUG。

在页面转圈的时候滚动即可100%触发。

**Comment by luckyyyyy** [comment]
这问题很头疼了，看起来像是chrome的问题其实。

我确定是在某个chrome版本后 70+具体哪个忘了，时间有点久了。

**Comment by suxiaogang** [comment]
@luckyyyyy 啊 对 应该是你说的这种操作更准确一些...

**Comment by luckyyyyy** [comment]
> @luckyyyyy 啊 对 应该是你说的这种操作更准确一些...

主要是没有其他鼠标替代方案，mm的手感实在受不了。

**Comment by Caldis** [comment]
@luckyyyyy @suxiaogang  似乎这是 Chrome 的一个问题, 在滚动事件被处理后会出现
我在关闭 Mos, 且仅运行 Logitech Options 的情况下, 使用 MX Anywhere 仍然可以触发这个问题

这里有一个解决方案
https://github.com/Caldis/Mos/issues/160#issuecomment-588078077

**Comment by lechie** [comment]
我这每天也会遇到n次吧，网页顶部、底部都可以无限滚动

**Comment by ruolis** [comment]
我现在每天也遇到很多次

Mac：10.15.5 (19F101)
鼠标：master anywhere
mos：2.3.0

**Comment by quanbrew** [comment]
可能不是软件的问题，我是搜索进来的，我没装这个软件也经常触发

**Comment by ShaochengChu** [comment]
有解决方案了吗，我没有这个软件，用的罗技mx鼠标，浏览器是safari，每天都会遇到

**Comment by quanbrew** [comment]
> 有解决方案了吗，我没有这个软件，用的罗技mx鼠标，浏览器是safari，每天都会遇到

我也是……

**Comment by Caldis** [comment]
修好了: https://github.com/Caldis/Mos/releases/tag/3.3.1

**Comment by tangtongda** [comment]
是不是macos滑动机制的问题，经常遇到
