### ISSUE TITLE
在使用POSTMAN出现的一个问题

### ISSUE THREAD

**Issue by asp1111** [Caldis/Mos#215]
**Describe the bug | 一个界面里面有两个滚动条，当两个滚动条都拉倒底端，然后网上滑动的话，两个滚动条会同时滚动，导致非常难用。

**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | 相关截图**
![image](https://user-images.githubusercontent.com/13173179/71511930-0d9dad00-28cf-11ea-8311-a8bdc98e9fcb.png)

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
 - OS: 10.14.5
 - Browser  chrome
 - Version 2.3.0
 -  Application postman
**Additional context | 额外说明**

**Comment by Caldis** [comment]
目前有双滚动条的 Web 页面都会有这样的问题, 目前没有什么好的办法, 抱歉
