### ISSUE TITLE
v3.0「恢复为预设值」会同时使「翻转方向」也生效，界面勾选未同步对应；但建议只恢复参数数字，不要干预功能选择

### ISSUE THREAD

**Issue by saintmob** [Caldis/Mos#216]
涉及版本：v3.0 Public Beta （相信旧版本也存在相同问题，但未实测）

具体复现描述：
1. 在【基础】设置页，不启用「翻转方向」；
2. 在【高级】设置页，点「恢复为预设值」，此时滚动滚轮会发现，「翻转方向」也被恢复默认（启用）了，但【基础】设置页面中的「翻转方向」并未勾选（不启用）。

合理的解决方案：
A. 既然全都恢复预设了，那么【基础】页面的勾选也要对应正确。
B. 在【高级】页的「恢复为预设值」按钮，正常理解应该只影响【高级】页的参数配置，不应该干预【基础】页面用户所做的手动选择。

个人推荐方案 B。

**Comment by Caldis** [comment]
感谢反馈, 确实有这个问题

**Comment by Caldis** [comment]
已在新版本中更改此行为: https://github.com/Caldis/Mos/releases/tag/3.3.2
