### ISSUE TITLE
Scrolling toggle inverted when monitor turns off / back on

### ISSUE THREAD

**Issue by willerbee** [Caldis/Mos#217]
**Describe the bug | 问题描述**
The mouse wheel scroll horizontally when my monitor is powered off, then powered on again after a few minutes.

**To Reproduce | 如何重现**
I would think this depends on the monitor. Some monitors completely disconnects from the video card when it's turn off (which is how my monitor behaves). To reproduce, just turn off the monitor, or unplug hdmi/dp cable. Wait for a couple of minutes, plug the video cable back in.

**Expected behavior | 期望结果**
Scrolling the wheel will go horizontal by default, using the toggle key it will scroll normally. You have to quit Mos and restart it again.

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: Logitech G304
 - OS: MacOS 10.14.6
 - Browser: Chrome 79.0.3945.117 (Official Build) (64-bit)
 - Version: Caldis v2.4.0-beta
 -  Application: Whole System

**Additional context | 额外说明**

**Comment by Caldis** [comment]
You can try version 3.0 to see if the problem persists

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/issues/207
