### ISSUE TITLE
文字在滑动时有拖影

### ISSUE THREAD

**Issue by forever0shine** [Caldis/Mos#219]
- 问题描述 | Issue description:
在外接显示器(刷新率 60)的情况, 看含有文字的网页在滑动的时候会有拖影. 

现在提高了速度增益,有所缓解.

希望能达到像手机上滑动时的缓慢且顺滑感觉.
- 软件版本 | Application version:

2.3.0
- 系统版本 | System version:
10.14.6

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:

**Comment by Caldis** [comment]
建议你换一个 120HZ 的显示器 ............
