### ISSUE TITLE
平滑滚动能否优化罗技鼠标master3的横向滚轮

### ISSUE THREAD

**Issue by liangjingkanji** [Caldis/Mos#220]
感觉横向滚轮很不顺滑

**Comment by Caldis** [comment]
master系列的横向滚动都是被 Logitech 的驱动接管的, 软件不好处理

**Comment by liangjingkanji** [comment]
但是好像不安装Logitech Options 也可以使用横向滚动吧,   感觉横向滚动不顺滑都不太想用了

**Comment by Caldis** [comment]
已修复: https://github.com/Caldis/Mos/releases/tag/3.3.1
