### ISSUE TITLE
能不能选择具体的可执行文件（不是包）加入黑名单啊

### ISSUE THREAD

**Issue by liyuxi** [Caldis/Mos#221]
从Steam启动的游戏是无法加入黑名单的，而mos的行为会造成游戏干扰（比如CSGO，mos会干扰切枪的行为）

**Comment by Caldis** [comment]
你可以试一下测试版, 添加的时候可以直接用 bundleId 来添加

**Comment by Caldis** [comment]
你可以试一下测试版, 添加的时候可以直接用 bundleId 来添加

**Comment by liyuxi** [comment]
> 你可以试一下测试版, 添加的时候可以直接用 bundleId 来添加

我就是用的3.0.0测试版，我无法在黑名单中添加可执行文档,能不能在后续版本中提供一个可定义的快捷键，在需要时可以完全关闭Mos的功能呢？

**Comment by Caldis** [comment]
我没在 Mac 上试过 CSGO, 不过按理来说只要你从 ```~/Library/Application Support/Steam/steamapps/common/``` 下面找到具体的文件添加就行
或者是启动游戏后使用 ```从运行的应用程序中添加``` 选项

**Comment by liyuxi** [comment]
> 我没在 Mac 上试过 CSGO, 不过按理来说只要你从 `~/Library/Application Support/Steam/steamapps/common/` 下面找到具体的文件添加就行
> 或者是启动游戏后使用 `从运行的应用程序中添加` 选项

我运行CSGO后，`从运行的应用程序中添加`列表不会出现CSGO，我在“手动从访达中选择”定位到具体的可执行文件，但是是灰的，无法添加

**Comment by Caldis** [comment]
理论上应该能找到游戏的一个 `.app` 为后缀的启动文件，难道 CSGO 不是这样的？

**Comment by liyuxi** [comment]
> 理论上应该能找到游戏的一个 `.app` 为后缀的启动文件，难道 CSGO 不是这样的？
不是
