### ISSUE TITLE
Not only mouse but trackpad too

### ISSUE THREAD

**Issue by forusak** [Caldis/Mos#223]
**Describe the bug | 问题描述**
Mos is using cpu even when trackpad scrolling is used.

**To Reproduce | 如何重现**
open activity monitor and scroll with trackpad, Mos jumps up in cpu usage.

**Expected behavior | 期望结果**
React just to the mouse scrolling since trackpad has it's own smooth scroll. Or add option to (de)activate.

**System Info | 系统信息:**
 - OS: MacOS Catalina

**Comment by Caldis** [comment]
You can try version 3.0 to see if the problem persists

**Comment by forusak** [comment]
> You can try version 3.0 to see if the problem persists

I see no difference, you do?

**Comment by Caldis** [comment]
Some CPU usage fluctuations are normal, Mos needs to handle all scroll events first, and then can further distinguish which ones need to be further processed
