### ISSUE TITLE
Why is middle click affected by Mos? 

### ISSUE THREAD

**Issue by MariuzM** [Caldis/Mos#224]
Without Mos when i middle click the mouse i can then move around the window. But when Mos is enabled this is useless it moves to fast barely can control this. So why is Middle mouse click part of Mos?

**Comment by Caldis** [comment]
Could you further describe how you setup the middle button functions ?

**Comment by WojciechTrzasko** [comment]
Hi,
I noticed the same issue as @MariuzM mentioned and it's probably not connected to any additional configuration or middle mouse function.

It's reproducible just by pressing the scroll wheel (middle) button and use it for scrolling and navigation. For example, it's visible in applications like Miro, Affinity Designer, SketchUp etc. when you try to use the middle button to move in the viewport.

I'm using Microsoft Sculpt Comfort Mouse.

**Comment by Caldis** [comment]
Fixed in latest versions: https://github.com/Caldis/Mos/releases/tag/3.3.1
