### ISSUE TITLE
Interferes with BTT Scroll Left / Right actions on Logitech Mouse

### ISSUE THREAD

**Issue by ja14000** [Caldis/Mos#225]
**Describe the bug | 问题描述**

BTT is unable to execute action for scroll left / right when when mos is active. Instead of the BTT assigned action a regular scroll left / right happens instead.

Once mos is restarted BTT is once again able to execute its actions.

**To Reproduce | 如何重现**

- In BTT remap scroll left / right to something else (with a Logitech MX Anywhere 2 )

- Use the system as normal 

- After some amount of time the remapped action for scroll left / right is no longer executed and the mouse does a regular horizontal scroll (it's default action) 

**Expected behavior | 期望结果**

- Remapped actions are executed in BTT

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse:  Logitech MX Anywhere 2
 - OS: 10.15.3
 - Browser: System wide
 - Version n/a
 -  Application [e.g. Safari, Chrome, Whole System]: System Wide

**Additional context | 额外说明**

**Comment by Caldis** [comment]
Fixed: https://github.com/Caldis/Mos/releases/tag/3.3.1
