### ISSUE TITLE
能够将mos应用于触控板

### ISSUE THREAD

**Issue by seanxu01** [Caldis/Mos#229]
发现开了MOS插上鼠标用的流畅度和
不插鼠标的流畅度有区别

能够在开启mos不插鼠标的情况下也能应用平滑滑动

**Comment by Caldis** [comment]
还有这种神奇现象。。。
能提供具体一点的设备信息吗？

**Comment by seanxu01** [comment]
搞错了,原来是默认集显导致的掉帧.
插上拓展坞切换独显不掉帧了

**Comment by Caldis** [comment]
🤣🤣
