### ISSUE TITLE
白名单模式BUG

### ISSUE THREAD

**Issue by BenjaminGao** [Caldis/Mos#230]
**Describe the bug | 问题描述**
只要打开白名单，任何程序都会进入到白名单里
**To Reproduce | 如何重现**
打开Chrome，开关白名单即可复现
**Expected behavior | 期望结果**
麻烦开发者尽快修复
**Screenshots | 相关截图**
![2020-02-24 12 30 22](https://user-images.githubusercontent.com/16028320/75128945-a1d69580-5701-11ea-97da-33dccba8d5f4.gif)

**System Info | 系统信息:**
 - Mouse: [雷蛇蝰蛇标准版]
 - OS: [macOS 10.13]
 - Browser [chrome]
 - Version [V80.0.3987.116]
 -  Application [All]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
白名单的工作机制本来就是这样。。。如果启用白名单，只有在列表中的应用才会对其生效

**Comment by BenjaminGao** [comment]
> 白名单的工作机制本来就是这样。。。如果启用白名单，只有在列表中的应用才会对其生效

麻烦作者看一下GIF，左边白名单列表根本就没有应用程序，请问为什么 Chrome 还跟开了白名单一样呢？我是很认真提了 issues。算了。

**Comment by wyudong** [comment]
@BenjaminGao 结合你的 GIF 和我的理解：开启白名单，Chrome 鼠标不平滑（此时只有在白名单里的应用才会启用滚动平滑）；关闭白名单，Chrome 鼠标变得平滑（此时白名单无效，默认对所有应用启用滚动平滑）。

**Comment by Caldis** [comment]
@wyudong 谢谢解释
@BenjaminGao Mos的默认工作模式是平滑所有应用，而开启白名单之后的工作模式是仅对白名单内的应用平滑，应用里的提示确实不太明确，抱歉
