### ISSUE TITLE
关于程序顶部状态栏图标隐藏的优化

### ISSUE THREAD

**Issue by richie52081** [Caldis/Mos#231]
希望mos能给一个隐藏顶部状态栏图标的选项

感谢mos团队为了用户这一点细微的体验做的优化，好的产品总是润物细无声的。我只是需要刚下载mos的时候简单设置一下就够了，后面的每次开机每次使用都可以在后台自动完成，它也不需要常驻在我电脑右上角的状态栏图标里，那个地方已经很拥挤了，有用没用的图标一大堆。这一点做的比较爽的产品是paste，一款剪贴板辅助产品，用的时候只需要快捷键调用，完全不用把图标常驻在状态栏里。
总之还是谢谢你，愿意为了一点细微的体验做改变。

**Comment by wyudong** [comment]
Mos 的偏好设置里不是已经有隐藏图标选项了吗
https://github.com/Caldis/Mos/releases/tag/2.0.0

**Comment by richie52081** [comment]
按链接里的引导找到了，偏好设置里找里半天都没看到，藏的可真深哈哈

Wang Yudong <notifications@github.com> 于2020年2月27日周四 下午1:29写道：

**Comment by wyudong** [comment]
#206 可以试试最新的 3.0.0 版本

**Comment by Caldis** [comment]
该功能新版本已实现, 谢谢支持
