### ISSUE TITLE
开启后，一些软件的shift+滚动  将会失效

### ISSUE THREAD

**Issue by qwer130140190** [Caldis/Mos#232]
- 问题描述 | Issue description:
开启后，一些软件的shift+滚动  将会失效

- 如何重现 | How to reproduce it:

- 期望结果 | What is expected:

- 实际结果 | What is actually happening:

- 软件版本 | Application version:

- 系统版本 | System version:

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:

**Comment by Caldis** [comment]
在设置中手动将切换键设置为 SHIFT 键即可
