### ISSUE TITLE
Mos_3 当鼠标在简书的代码块中滚轮无效

### ISSUE THREAD

**Issue by liangjingkanji** [Caldis/Mos#234]
当鼠标在简书的代码块中滚轮无效

**System Info | 系统信息:**
 - Mouse: [罗技 MX Master3]
 - OS: [Mac OS 10.15.3 (19D76) ]
 - Browser [Chrome]
 - Version [Chrome 80.0.3987.122]
 -  Application [Mos v3]

**Comment by TomatoWithEgg** [comment]
不仅简书,其他网页也一样.当代码块可以水平滚动,则鼠标在代码块中时.无法垂直滚动.当代码块无法水平滚动时,则可以垂直滚动

**Comment by Caldis** [comment]
可能跟另一个 https://github.com/Caldis/Mos/issues/213 有相同的诱因, Chrome 不知为何对转换后的滚动事件处理上有问题，可能是缺少了某些特征值

**Comment by zxp1314gch** [comment]
csdn也是，在代码块里滑动总是卡住

**Comment by hyang57** [comment]
chrome://flags

Disable following functions:

- Threaded scrolling
- Enable resampling scroll events
- Filtering scroll prediction

This could dramatically improve scrolling performance in code blocks.

**Comment by zxp1314gch** [comment]
thanks

hyang57 <notifications@github.com> 于 2020年3月11日周三 上午11:05写道：

**Comment by Caldis** [comment]
Fixed in latest versions: https://github.com/Caldis/Mos/releases/tag/3.3.1
