### ISSUE TITLE
不能左右滾動(Can not scroll horizontally)

### ISSUE THREAD

**Issue by HackettLai** [Caldis/Mos#235]
**Describe the bug | 问题描述**
在啟用狀態下Shift+滾輪沒有反應
No response with Shift+Wheel under enable status

**System Info | 系统信息:**
 - Mouse: Fujitsu FR500
 - OS: MacOS 10.15.3
 - Version: MOS 2.3.0

**Comment by Caldis** [comment]
@HackettLai 请在设置中将转换键设置为 SHIFT 即可，因为 Mos 对部分应用的 SHIFT 的转换可能存在问题，所以没有做成默认启用，见谅

**Comment by hupanqing** [comment]
> @HackettLai 请在设置中将转换键设置为 SHIFT 即可，因为 Mos 对部分应用的 SHIFT 的转换可能存在问题，所以没有做成默认启用，见谅

但是实际上mac默认就支持shift + 滚轮实现水平滚动的；可是当打开mos程序后，这个原生的功能就不生效了，如果在mos中设置shift+滚轮实现水平滚动，也不会生效了。。

**Comment by sn0wyfall** [comment]
@Caldis Thanks, I think it should be enabled by default in the future! :)

**Comment by idanmashaal** [comment]
Oh my MacMini + Catalina 10.15.5 with Logitech MX Vertical this works fine and by default. 
You should try MOS V3.0.0, it’s in testing. 

https://github.com/Caldis/Mos/issues/206
https://github.com/Caldis/Mos/issues/207
