### ISSUE TITLE
MX Master3  鼠标上下滚动失效

### ISSUE THREAD

**Issue by Yutin666** [Caldis/Mos#236]
**Describe the bug | 问题描述**
MX Master3  鼠标在Logi Options里把水平滚轮设置为Chrome/Safari标签切换后，用水平滚轮切换到下一个标签后再切换回上一个标签后垂直滚轮回失效（不只是在浏览器内没反应，所有应用内都没反应）。失效后再一次用水平滚轮切换两次标签后恢复正常。
**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master 3]
 - Version [e.g. v69]
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
可否帮助测试一下, 在垂直滚轮失效后, 在一个可横向滚动的页面中滚动垂直滚轮, 页面是否会横向滚动?
另外在垂直滚轮失效后, 滚动监视(3.0版本请按住 Options 点击状态栏图标) 内是否有数据?

**Comment by Yutin666** [comment]
> 可否帮助测试一下, 在垂直滚轮失效后, 在一个可横向滚动的页面中滚动垂直滚轮, 页面是否会横向滚动?
> 另外在垂直滚轮失效后, 滚动监视(3.0版本请按住 Options 点击状态栏图标) 内是否有数据?

哇哦我猜你已经知道问题出在哪了。1、会横向滚动；2、滚动监视中仅有水平数据。另外我试了一下3.0版本中垂直滚轮不会失效。

**Comment by Caldis** [comment]
@Yutin666 那就请继续使用 3.0 就好, 之前的版本确实存在这个问题
