### ISSUE TITLE
10.15.3 lanchpad 切换延迟

### ISSUE THREAD

**Issue by chenxi-zhao** [Caldis/Mos#237]
10.15.3 lanchpad 切换延迟，会顿一下

**Comment by chenxi-zhao** [comment]
换成3.0之后好了，但是lanchpad 滚动效果不如触控板平滑

**Comment by Caldis** [comment]
谢谢反馈
鼠标滚轮在 lanchpad 内只能这样了, 肯定比不上触控板的
