### ISSUE TITLE
点击偏好设置的开机启动会自动退出

### ISSUE THREAD

**Issue by StarFishing** [Caldis/Mos#238]
**Describe the bug | 问题描述**点击偏好设置的开机启动会自动退出程序，无法勾选开机启动

**To Reproduce | 如何重现** macos 10.14.6

**Expected behavior | 期望结果**可以设置开机启动

**Screenshots | 相关截图**

![image](https://user-images.githubusercontent.com/41889222/76679508-1a06eb80-661c-11ea-88d9-ded7f0c49f98.png)

**System Info | 系统信息:**macos 10.14.6
 - Mouse: [e.g. Logitech MX Master]
 - Version [e.g. v69]
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/releases/tag/3.3.1
