### ISSUE TITLE
在博客代码块处，无法通过鼠标滚轮上下移动

### ISSUE THREAD

**Issue by liufei666** [Caldis/Mos#240]
**Describe the bug | 问题描述**

在 *静止的* 博客代码块处，无法通过鼠标滚轮上下移动。chrome有问题，safari正常

**To Reproduce | 如何重现**

以 <https://blog.csdn.net/conansonic/article/details/51849659> 为例，先移动到第一个代码块，然后 *静止* 鼠标，之后滚动鼠标滑轮，无法上下移动。

**Expected behavior | 期望结果**

期望解决

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master] 罗技 M100r
 - OS: [e.g. iOS] mac os 10.15.3
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. v69] 3.0.0
 -  Application [e.g. Safari, Chrome, Whole System] Chrome

**Additional context | 额外说明**

**Comment by wyudong** [comment]
Probably duplicated: #234

**Comment by liufei666** [comment]
Thanks
