### ISSUE TITLE
mos 2.4版，3.0版，鼠标划过浏览器时窗口缩小居中，mos1.7版就没有这个问题，

### ISSUE THREAD

**Issue by Taoisting** [Caldis/Mos#241]
**Describe the bug | 问题描述**
mos 2.4版，3.0版，鼠标划过浏览器时窗口缩小居中，mos1.7版就没有这个问题，
**To Reproduce | 如何重现**
鼠标迅速或者不经意划过浏览器标签栏时，窗口缩小居中，无论是safari还是chrome都会如此，其他软件倒没发现过。
**Expected behavior | 期望结果**
修复这个莫名其妙的问题
**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
 - OS: [e.g. iOS]  MAc 10.14.5
 - Version [e.g. v69]  chrome 80，safari 12.1.1
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Taoisting** [comment]
我删掉mos 2.4， mos3，换回mos1.7 就完全没有这个问题了，测试了一段时间都没有了，一换回来马上会不定时出现问题。
mos1.7的滚动没有2.4和3的好，生硬的，没有那么顺滑

**Comment by Caldis** [comment]
窗口缩小居中是指换出 mission conrtol 的界面?

**Comment by Taoisting** [comment]
不是的，比如chrome，是鼠標快速經過瀏覽器標簽欄時，瀏覽器的窗口自動縮小居中了，這個情況警察發生，但是故意去劃過時就沒事，不經意就會。
用mos1.7版無論怎麽樣，就一直沒有這個問題。

**Comment by Taoisting** [comment]
我的 mission conrtol 界面是只有右下角才能進入

**Comment by Caldis** [comment]
根据你的描述, 我感觉是 App Exposé 的效果 ...

**Comment by Taoisting** [comment]
我没有 App Exposé ，这段时间一直用mos1.7，其他所有app都没有改变，就没有这个问题。
我换成2.4和3，马上会随机出现，而且有点频繁。

**Comment by Caldis** [comment]
能否提供一段录屏？因为我实在没有头绪这是什么效果…

**Comment by Taoisting** [comment]
简单地说，就是鼠标一快速滑过已经最大化（非mac的全屏）chrome的标签栏时，chrome上下左右 4个边框同时缩小，chrome变成一个居中的窗口大小在电脑屏幕上，我得重新手工双击标签栏空白来最大化

**Comment by Taoisting** [comment]
怎么传视频给你看呢？

**Comment by Taoisting** [comment]
新版2.4 依然存在问题，没有解决，怎么发视频给你看？
