### ISSUE TITLE
黑名单匹配规则增加窗口名称或路径匹配

### ISSUE THREAD

**Issue by Vxider** [Caldis/Mos#242]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**

是，目前黑名单匹配方式只能匹配macos应用程序，但是有很多非原生应用并没有bundle ID，比如 [scrcpy](https://github.com/Genymobile/scrcpy). 导致无法匹配。而这些应用在窗口切换器（cmd+tab)中是可以看到的。

**说说你的新点子 | Describe the solution you'd like**

可以增加使用窗口标题或者文件路径匹配，并支持正则表达式匹配。

例如，keyboard Maestro中可以直接匹配窗口名称。
Karabiner-Elements中则使用`file_paths`匹配，比如

```
"conditions": [
    {
        "file_paths": [
            "^.*scrcpy"
        ],
        "type": "frontmost_application_if"
    }
],
```

并且，Mos在添加黑名单时，无法添加`/usr/local/bin`目录下的应用。

**还有别的替代方案吗？ | Describe alternatives you've considered**

**额外说明 | Additional context**

**Comment by Caldis** [comment]
已在新版本中加入 https://github.com/Caldis/Mos/releases/tag/3.3.1
