### ISSUE TITLE
滑动触摸板后滚动鼠标滚轮时滚轮不反转

### ISSUE THREAD

**Issue by zanjie1999** [Caldis/Mos#243]
**Describe the bug | 问题描述**
滑动触摸板后马上滚动鼠标滚轮时一小段时间内滚轮不会反转

**To Reproduce | 如何重现**
启动鼠标滚轮反转，在触摸板上滚动（比如把内容下拉），然后马上去鼠标上滚动（比如向上滚动），此时内容会向上移动

![https://i.loli.net/2020/03/27/znjxSBhkOMZ7LAg.png](https://i.loli.net/2020/03/27/znjxSBhkOMZ7LAg.png)

**Expected behavior | 期望结果**
滚动鼠标滚轮时应该反转，内容向下移动

**System Info | 系统信息:**
 - Mouse: 普通蓝牙鼠标
 - OS: macOS 10.15.3

**Additional context | 额外说明**

**Comment by Caldis** [comment]
虽然没有特地修复这个问题, 不过似乎在新版本中这个问题已经不存在了
https://github.com/Caldis/Mos/releases/tag/3.3.1
