### ISSUE TITLE
滑动操作应该在鼠标位置移动后取消，类似触摸板操作

### ISSUE THREAD

**Issue by kevinaskin** [Caldis/Mos#245]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**

在一个窗口滑动滚轮之后移到另一个窗口，会触发另一个窗口的滚动。而触摸板操作是会在鼠标移动时立即停止滚动事件

**说说你的新点子 | Describe the solution you'd like**

**还有别的替代方案吗？ | Describe alternatives you've considered**

**额外说明 | Additional context**

**Comment by Caldis** [comment]
已知问题, 正在探索解决方案, 谢谢反馈

**Comment by kkzz2000** [comment]
刚买了逻辑mx master 3，遇到了相同的问题，盼望尽快解决，经测试，smoothscroll没有这个问题。

**Comment by kkzz2000** [comment]
这个软件顺滑度真的很赞，要顶起来，pk掉smoothscroll

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/releases/tag/3.3.1
