### ISSUE TITLE
黑苹果触摸板滚动太快

### ISSUE THREAD

**Issue by igeosciences** [Caldis/Mos#247]
**Describe the bug | 问题描述**
黑苹果触摸板滚动太快，基本一划就到底了。
**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
**Catalina**
 - Version [e.g. v69]
**15.4**
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by mayan-lab** [comment]
应该是黑苹果中，触摸板和鼠标没有识别开，导致触摸板也用了速度增益。

**Comment by Caldis** [comment]
由于目前用的启发式算法是基于 eventTap 事件的一些特征来识别的, 暂时无法区别出黑苹果的触控板, 见谅
