### ISSUE TITLE
您好，macosx 10.15.4使用时无法实现对鼠标滚轮方向的控制。

### ISSUE THREAD

**Issue by as2h** [Caldis/Mos#248]
**Describe the bug | 问题描述**

**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | **

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
 - Version [e.g. v69]
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
您好, 请于 3.0 版本下尝试一下, 如果还有问题欢迎回报
