### ISSUE TITLE
建议添加一个小功能，鼠标轻触点击

### ISSUE THREAD

**Issue by vajvip** [Caldis/Mos#25]
建议添加一个小功能，鼠标轻触点击，感觉也蛮实用的。（ps：使用magic mouse）

**Comment by Caldis** [comment]
意思是类似触控板中的 "轻点来点按" 吗?

**Comment by vajvip** [comment]
是的，之前有一个鼠标手势扩展应用是支持的。

**Comment by Caldis** [comment]
目前暂时没有想做成这种大而全的 APP 想法, 而且手边也没有 MagicMouse 可供我调试~
