### ISSUE TITLE
罗技 anywhere s2 鼠标滚轮，水平方向与垂直方向反了

### ISSUE THREAD

**Issue by cjpxyz** [Caldis/Mos#250]
Mac Book 2019 MacOS Catalina10.15.4
罗技 anywhere s2鼠标，刚安装Mos时还好，用着用着就默认的滚轮滚动方向就变成水平滚动了。

**Comment by Caldis** [comment]
已知问题, 请试一下 3.0 版本, 如果还有问题欢迎回报
