### ISSUE TITLE
双栏滑动问题

### ISSUE THREAD

**Issue by qq515550** [Caldis/Mos#257]
在有双栏的软件 e.g. 微信
当你向下快速滑动「对话列表」，快速将鼠标移动到「聊天窗口」，
如果可以的话，「聊天窗口」也会向下滑动一小段，方向和「对话列表」一致。
同样布局界面软件可以复现。
版本3.0

**Comment by qq515550** [comment]
<img width="651" alt="截屏2020-05-07 下午6 52 15" src="https://user-images.githubusercontent.com/64960415/81286701-0f088e80-9094-11ea-8dd7-f1e940795cd8.png">
类似这种界面都可以复现

**Comment by qq515550** [comment]
<img width="651" alt="截屏2020-05-07 下午6 52 15" src="https://user-images.githubusercontent.com/64960415/81286758-28a9d600-9094-11ea-900a-707c8e36841d.png">

**Comment by Caldis** [comment]
因为目前平滑滚动的惯性并不会随着鼠标移动而停止, 而 Mos 本身并不能区分窗内部的 ScrollView (其实有方案, 但性价比相当低, 对性能影响也很大), 因此目前不对这种行为做处理, 算是一种折中方案
