### ISSUE TITLE
你好，为什么我设置了开机启动，每次还要登陆后手动打开程序

### ISSUE THREAD

**Issue by kk2snm** [Caldis/Mos#26]
为什么我设置了开机启动，每次还要登陆后手动打开程序？

**Comment by kk2snm** [comment]
开机没有自动启动

**Comment by Caldis** [comment]
可以看看勾选了开机启动之后, 系统偏好设置里面的 "用户与群组" 的 "登陆项" 里面, MOS 有没有被自动添加进去.
另麻烦提供一下系统版本

**Comment by kk2snm** [comment]
你好，登陆项里面有mos,并且前面以打勾，系统版本为macos sierra 10.12，谢谢！

**Comment by Caldis** [comment]
试试手动删除之后再于登录项面板内手动添加一次呢?

**Comment by kk2snm** [comment]
手动添加还是不行哎，每次开机都要双击应用程序

**Comment by Caldis** [comment]
@kk2snm 我系统是10.12.6, 暂时也没法重现这个问题...
看看有没有其他患者能提供相关资料了
