### ISSUE TITLE
Hide menubar icon

### ISSUE THREAD

**Issue by EthanZeigler** [Caldis/Mos#260]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**
I have a top of menubar icons for various things and they sometimes cause weird things with the current application.

**说说你的新点子 | Describe the solution you'd like**
Have some way of disabling the menu bar icon and opening settings from another mechanism.

**还有别的替代方案吗？ | Describe alternatives you've considered**
There is no other way to address the problem

**额外说明 | Additional context**

**Comment by sn0wyfall** [comment]
Try using bartender

**Comment by idanmashaal** [comment]
I specifically use Bartender and it works amazing (comes with a price) but if you are looking for something open source and free you can also try using “Hidden Bar”. 
https://github.com/dwarvesf/hidden/blob/develop/README.md

“Hidden Bar” is installable from the AppStore.

**Comment by sn0wyfall** [comment]
@idanmashaal Nice, that looks cool. How does it compare to Bartender? I don't really use many of the features Bartender has (e.g. shortcuts and stuff), so I'm wondering if it's worth it just using Hidden Bar instead.

**Comment by idanmashaal** [comment]
@sn0wyfall I really think Bartender is an amazing application that worth the $$$.
Hidden Bar is nice, it works by putting a placeholder in the status bar and everything to the left is hidden. Bartender is much more powerful and consistent which makes it a joy to use.
If you have purchased Parallels Desktop it comes with the Parallels Toolbox which has a similar feature. Hope this helps :)

**Comment by Caldis** [comment]
thanks for you feedback, you might want to try the new version.

**Comment by EthanZeigler** [comment]
I did, and I really appreciate not only the change, but how graceful the
start notification is.

Ethan Zeigler
ethanzeigler.com

Please excuse any typos. Sent from my phone.
