### ISSUE TITLE
希望增加隐藏菜单栏图标功能

### ISSUE THREAD

**Issue by danngo78** [Caldis/Mos#262]
可以节省一些菜单栏空间

**Comment by wyudong** [comment]
这个功能很早就有了，设置里找一下

**Comment by danngo78** [comment]
> 这个功能很早就有了，设置里找一下

设置找不到哇，搜索引擎一搜发现是你17年提的改进wwww感谢

不过话说回来这个功能也太难找了吧，我搜索更新日志才知道怎么设置。。。

新功能
现在你可以隐藏状态栏的图标了, 只需要按住 option 键, 再单击状态栏图标, 根据提示操作即可. 如果您需要重新显示状态栏的图标, 请使用活动监视器关闭 Mos, 再重新运行, 并点击通知中出现的 "显示图标" 按钮
