### ISSUE TITLE
Smooth scrolling doesn't work with horizontal scrolling wheel on MX Master 3

### ISSUE THREAD

**Issue by sn0wyfall** [Caldis/Mos#263]
**Describe the bug | 问题描述**

Smooth scrolling doesn't work with horizontal scrolling wheel on MX Master 3

**To Reproduce | 如何重现**

Use MX Master 3 mouse horizontal scrolling

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
 - Version [e.g. v69]
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

You can get smooth scroll behavior if you use shift or whatever + scroll. But I want to use this for the horizontal scroll wheel.

**Comment by idanmashaal** [comment]
Do you have LogiOptions installed?
If so, make sure you have “Smooth Scrolling” disabled.
On my MX Master 2S I recall that it was enabled by default and I started using MOS after changing to MX Vertical that doesn’t have the smooth scrolling feature in the LogiOptions app.

Also, if you are on Catalina, try using the beta v3.0.0 here:
https://github.com/Caldis/Mos/issues/206
https://github.com/Caldis/Mos/issues/207

**Comment by sn0wyfall** [comment]
@idanmashaal Wow, this works so well! Previously I had an issue when I scrolled horizontally in Safari to switch tabs that scrolling would stop working, likely due to the way Logitech Options send the keystrokes and it messed with Mos, so I'd have to restart it which was super sad. But it works pretty well now, almost without any issue! This is amazing.

**Comment by lthoerner** [comment]
@idanmashaal I am having the same issue now, do you have any insight as to how to disable smooth scrolling on the horizontal scroll wheel? Unlike the vertical scroll wheel, there is no toggle box for smooth scrolling.

**Comment by wwongfan123-prog** [comment]
我也遇到了这个问题，还没能解决。
