### ISSUE TITLE
Exceptions Per Mouse

### ISSUE THREAD

**Issue by mojomojo52** [Caldis/Mos#265]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**

It would be great if I can set which mouses I want to use MOS with, like how I can set different settings per input device in karabiner.
MOS collides with Logitech options, which I would rather use for Logitech mouses while all other mouses I would stick with MOS.

**说说你的新点子 | Describe the solution you'd like**
Give a way to set which devices I want and do not want to use MOS.

**还有别的替代方案吗？ | Describe alternatives you've considered**

**额外说明 | Additional context**

**Comment by sn0wyfall** [comment]
I prefer using Mos over Logitech options tbh. The smooth scrolling is subpar from Logitech Options.

**Comment by Caldis** [comment]
Sorry Mos doesn't have the ability to read the underlying device, it needs to be connected to IOKit or DriverKit, that would probably be more work.
