### ISSUE TITLE
Disable for Spaces in Mission Control

### ISSUE THREAD

**Issue by SnooHD** [Caldis/Mos#266]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**
I use a shortcut for my mouse where i can switch between spaces using my scrollwheel, but due to Moss i always scroll to the last space.

**说说你的新点子 | Describe the solution you'd like**
Possibility to disable moss for Mission control

**还有别的替代方案吗？ | Describe alternatives you've considered**
I have tried adding Mission Control as an exception, but this does not work.
For now i set a block key to make it work, but this kind of takes out the point of my mouse shortcut..

**Comment by Caldis** [comment]
You might want to try the new version.
