### ISSUE TITLE
希望能够隐藏顶部图标

### ISSUE THREAD

**Issue by RogerProSelf** [Caldis/Mos#267]
希望提供隐藏顶部图标的选项，如果需要设置可以直接在launchpad中打开app设置，顶部菜单已经很满了……谢谢！

**Comment by wyudong** [comment]
> 现在你可以隐藏状态栏的图标了, 只需要按住 option 键, 再单击状态栏图标, 根据提示操作即可. 如果您需要重新显示状态栏的图标, 请使用活动监视器关闭 Mos, 再重新运行, 并点击通知中出现的 "显示图标" 按钮

该功能早在 [2.0.0](https://github.com/Caldis/Mos/releases/tag/2.0.0) 版本已有。
