### ISSUE TITLE
例外列表无效

### ISSUE THREAD

**Issue by dvdhoo** [Caldis/Mos#268]
- 问题描述 | Issue description:
添加到例外列表的app还是会平滑滚动，例如Acrobat或者Chrome

- 如何重现 | How to reproduce it:
添加到例外列表并且取消勾选平滑，平滑滚动依旧生效
![Screen Shot 2020-06-18 at 7 02 47 PM](https://user-images.githubusercontent.com/691461/85080096-55becd80-b196-11ea-8122-8db05dcf82bf.png)

- 期望结果 | What is expected:
添加到例外并且取消勾选后，平滑滚动应该不工作

- 实际结果 | What is actually happening:
例外列表无效

- 软件版本 | Application version:
2.3.0

- 系统版本 | System version:
10.5.5

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:

**Comment by dvdhoo** [comment]
我觉得是双屏幕的问题。我用的是MacBook Pro 2015 13 inch。外接了Dell的显示器做副屏。Acrobat拖到Dell显示器的时候例外无效，在MacBook主屏幕的时候例外有效。

**Comment by Caldis** [comment]
已修复: https://github.com/Caldis/Mos/releases/tag/3.3.1
