### ISSUE TITLE
I hid the menu bar icon and now am unable to open the app

### ISSUE THREAD

**Issue by danielcxu** [Caldis/Mos#269]
**Describe the bug | 问题描述**
I used the app's option to hide the menu bar icon. Now I'm unable to access the app at all

**To Reproduce | 如何重现**
Use the app's setting to hide menu bar item, then try to launch the app

**Expected behavior | 期望结果**
The app launches and you see a user inteface

**System Info | 系统信息:**

 - OS: Mac

**Comment by Caldis** [comment]
Try latest version https://github.com/Caldis/Mos/releases
