### ISSUE TITLE
打开 Android Studio 自带的模拟器后, Mos 会自动退出

### ISSUE THREAD

**Issue by CasparGX** [Caldis/Mos#27]
打开 Android Studio 自带的模拟器后, Mos 就会自动退出, 也没有提示, 导航栏里的图标也直接没了,需要重新打开, 而且模拟器在的时候, 总是会自动退出.

**Comment by Caldis** [comment]
烦请提供一下系统版本和 Android Studio 的版本

**Comment by CasparGX** [comment]
MacOS 10.12
Android Studio 2.3
Android Studio 自带模拟器

**Comment by Caldis** [comment]
@CasparGX 
这个 Android Studio 装的我好苦, 不过算找到问题了
那模拟器是  Android Studio  的子进程, 找不到 bundleId 所以报错了

**Comment by CasparGX** [comment]
哈哈哈, Android Studio 安装的确, 有很多东西有墙, 有的又没有.
现在能解决吗, 好像 Android Studio 打开的子进程都会这样, 有一些工具是单独打开的.

**Comment by Caldis** [comment]
@CasparGX 代码已经传上来了, 过两天发个版本

**Comment by CasparGX** [comment]
好的

**Comment by Caldis** [comment]
@CasparGX 上传了1.6.1版本, 欢迎测试反馈~
https://github.com/Caldis/Mos/releases/tag/1.6.1
