### ISSUE TITLE
Safari Tab Scrolling does not work

### ISSUE THREAD

**Issue by ilteen** [Caldis/Mos#270]
**Describe the bug | 问题描述**
In Safari, one can scroll through the tabs beneath the search bar, but when Mos is running this doesn't work.

**To Reproduce | 如何重现**
Enable Mos, open many Tabs in Safari, position the mouse cursor on the tab bar and try to scroll.

**Expected behavior | 期望结果**
The tabs scroll/cycle through

**Screenshots | 相关截图**
![ezgif-2-afd6deffd808](https://user-images.githubusercontent.com/35779536/85268452-d1f73080-b476-11ea-8567-31f62be3d469.gif)

**System Info | 系统信息:**
 - Mouse: Logitech G600
 - OS: macOS Catalina 10.15.5
 - Browser: Safari 13.1.1
 - Application: Safari

**Comment by Caldis** [comment]
Thanks for feedback，its a known issues. You can assign a toggle key and Transform the direction of scrolling to achieve it. Seems Safari can‘t process the scroll event correctly after interpolation.
