### ISSUE TITLE
Reverse scrolling doesn't work on Apple Magic Mouse

### ISSUE THREAD

**Issue by baimhanifkamil** [Caldis/Mos#271]
- 问题描述 | Issue description:
Reverse scrolling doesn't work on Apple Magic Mouse

- 如何重现 | How to reproduce it:
Use a magic mouse to horizontal scroll

- 期望结果 | What is expected:
Swiping down in the middle of the mouse will scroll down to the UI

- 实际结果 | What is actually happening:
Page will scroll up the UI

- 软件版本 | Application version:
All apps

- 系统版本 | System version:
MacOS Catalina 10.15.5

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:
none

**Comment by Caldis** [comment]
Thanks for feedback but Apple Magic Mouse has same events with the build-in Trackpad so it can't be handled separately
