### ISSUE TITLE
Not able to set a value for Step/Speed/Duration with keyboard or number-pad

### ISSUE THREAD

**Issue by Li-nuz** [Caldis/Mos#273]
**Describe the bug | 问题描述**
Although, I can adjust the values for Step/Speed/Duration with the sliders and arrows, I am not able to enter a specific value with the keyboard because there is no way to confirm and apply the value. Enter-, ESC- or Tab- key don't work. It makes a sound, but the cursor is still trapped in the input value field and the value is not applied.

**To Reproduce | 如何重现**
Click inside the boxes where the values for Step/Speed/Duration are. Now try to put in any specific value with the numb pad or keyboard and try to confirm the value and apply it.

**Expected behavior | 期望结果**
After pressing the enter-key, the cursor should leave the value field and the value should be applied. 

**Screenshots | 相关截图**
[https://abload.de/img/bildschirmfoto2020-07gfj31.png](url)
<img width="462" alt="Bildschirmfoto 2020-07-04 um 19 03 28" src="https://user-images.githubusercontent.com/54778964/86517499-a3d80000-be29-11ea-8111-75dfc5551789.png">

**System Info | 系统信息:**
 - Mouse: Macbook Pro 2014 Trackpad; Logitech G502
 - OS: MacOS Catalina
 - Version: 2.3.0
 - Application: Whole System

**Comment by Caldis** [comment]
fixed https://github.com/Caldis/Mos/releases/tag/3.3.1
