### ISSUE TITLE
Values in "Exclusion" instead of ON/OFF // Profiles for Applications (Photoshop Zoom Problem)

### ISSUE THREAD

**Issue by Li-nuz** [Caldis/Mos#274]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**

When using Photoshop with an external non-apple mouse and MOS is activated, zooming is almost impossible as it zooms either way too far in or way too far out, although i just turn the mouse-wheel just by one click. When I disable smooth scrolling in MOS, zooming is of course very choppy again.

**说说你的新点子 | Describe the solution you'd like**

When I set all the values in MOS to "1.0" i can zoom perfectly smooth and in perfect steps when using Photoshop. But then I would have to change the MOS settings every time i use Photoshop.

Therefore, I would really like it, if i could create some exception-presets for certain apps. Similiar to "Exception" but with added values insted of just on/off... Like this for example:

![WhatsApp Image 2020-07-04 at 20 04 50](https://user-images.githubusercontent.com/54778964/86518363-c66e1700-be31-11ea-90b3-20f2c340724d.jpeg)

**还有别的替代方案吗？ | Describe alternatives you've considered**

Excluding Photoshop when using MOS but scrolling is so bad without MOS

**Comment by Caldis** [comment]
Just try the latest version, the independent settings feature has just been added to Mos !
