### ISSUE TITLE
mos突然无法使用

### ISSUE THREAD

**Issue by silentchild** [Caldis/Mos#275]
版本3.0 
系统10.15.5
已经卸载重装，依然无效，点击mos完全没反应（状态栏也没有图标）

**Comment by silentchild** [comment]
是否是因为是测试版，刚刚下载2.4可以使用了，3.0现在无法使用

**Comment by HunDunDM** [comment]
碰到同样问题，mos 3.0 和 macOS 10.15.5

**Comment by dhliubj** [comment]
同，昨晚突然出现问题，今天显示“应用程序Mos无法打开”
![截屏2020-07-08 上午8.16.56.png](https://i.loli.net/2020/07/08/CFTYDVX84KEuP3U.png)

**Comment by yaochangliang159** [comment]
我也是这样，今早打开电脑，MOS突然无法使用了，打不开了！！！！同样的问题！！！我的系统版本
10.15.5 (19F101)

**Comment by vescape920** [comment]
同出现此问题

**Comment by yaochangliang159** [comment]
作者大佬解决一下，我现在鼠标用起来特别不舒服，滚轮拨动起来也是相反的方向滑动。。。好难受啊。严重影响我办公效率。。

**Comment by silentchild** [comment]
> 作者大佬解决一下，我现在鼠标用起来特别不舒服，滚轮拨动起来也是相反的方向滑动。。。好难受啊。严重影响我办公效率。。

先安装2.4，2.4可以正常使用，不要一直干等着更新

**Comment by dhliubj** [comment]
> > 作者大佬解决一下，我现在鼠标用起来特别不舒服，滚轮拨动起来也是相反的方向滑动。。。好难受啊。严重影响我办公效率。。
> 
> 先安装2.4，2.4可以正常使用，不要一直干等着更新

我重新装了2.4，点击之后还是打不开，菜单栏没有图标。
[11.0 Beta版(20A4299v)]

**Comment by nb5p** [comment]
我的也是，突然就无法用了，且和本Issue的版本号一直

> 版本3.0
> 系统10.15.5
> 已经卸载重装，依然无效，点击mos完全没反应（状态栏也没有图标）

**Comment by silentchild** [comment]
> 我的也是，突然就无法用了，且和本Issue的版本号一直
> 
> > 版本3.0
> > 系统10.15.5
> > 已经卸载重装，依然无效，点击mos完全没反应（状态栏也没有图标）

卸载后安装2.4，我目前可以用

**Comment by silentchild** [comment]
> > > 作者大佬解决一下，我现在鼠标用起来特别不舒服，滚轮拨动起来也是相反的方向滑动。。。好难受啊。严重影响我办公效率。。
> > 
> > 
> > 先安装2.4，2.4可以正常使用，不要一直干等着更新
> 
> 我重新装了2.4，点击之后还是打不开，菜单栏没有图标。
> [11.0 Beta版(20A4299v)]

好吧，我的15.5是可以用2.4的，3.0用不了

**Comment by kakakuangkuang** [comment]
我的也是,就今天无法使用了
版本3.0
系统10.14.5

**Comment by git-systemd** [comment]
罗技 master 3 没法用老版 2.4 ，滚动有问题；3.0 版今天不能用之后，我差点崩溃了。。。求解救。。。

**Comment by Caldis** [comment]
十分抱歉，应该是之前测试时候 Bundle 的 Code sign 过期了导致无法正常启动，请直接下载新版本即可
https://github.com/Caldis/Mos/releases/tag/3.1.0

**Comment by silentchild** [comment]
作者解决了，更新就行
