### ISSUE TITLE
Reported as Malware (Though I'm sure it isn't)

### ISSUE THREAD

**Issue by KhushrajRathod** [Caldis/Mos#276]
**Describe the bug | 问题描述**
Catalina reports Mos as malware all of a sudden

**To Reproduce | 如何重现**
Not reproducible, happens randomly

**Expected behavior | 期望结果**
No malware popups

**Screenshots | 相关截图**
![Screenshot 2020-07-08 at 10 47 08 AM](https://user-images.githubusercontent.com/44947946/86879539-c5abde00-c0da-11ea-8215-bdfde35f7579.png)

**System Info | 系统信息:**
 - OS: macOS Catalina
 - Version: 3.0.0

**Comment by Caldis** [comment]
The version 3.0 code sign for testing has expired, please download the new version directly

**Comment by KhushrajRathod** [comment]
> The version 3.0 code sign for testing has expired, please download the new version directly
> https://github.com/Caldis/Mos/releases/tag/3.1.0

Nice!!
