### ISSUE TITLE
解决 Mos 3.0 版本无法使用 | Fix the Mos 3.0 not working

### ISSUE THREAD

**Issue by Caldis** [Caldis/Mos#277]
```
十分抱歉带来不便，请直接下载新版本即可
```

```
The version 3.0 code sign for testing has expired, please download the new version directly
```

https://github.com/Caldis/Mos/releases/tag/3.1.0

**Comment by cyea** [comment]
It's been a long time!

**Comment by idanmashaal** [comment]
@Caldis Thanks for version 3.1.0 - I wanted to let you know that Docked Folders (Applications, Downloads, etc) are still not smooth when scrolled. Could you please check this ?

**Comment by Voring** [comment]
好久不见，辛苦了

**Comment by smiledahai** [comment]
great 感谢付出

**Comment by cv0cv0** [comment]
终于更新了！

**Comment by Alleckz** [comment]
i am still having this issue on latest build. Im on macOS Catalina 10.15.6.
