### ISSUE TITLE
菜单栏图标问题

### ISSUE THREAD

**Issue by L1cardo** [Caldis/Mos#278]
**Describe the bug | 问题描述**
我猜菜单栏图标在隐藏的时候不是隐藏了，而是宽度设为了 0 吧。
导致被隐藏时还能呼出菜单。

**To Reproduce | 如何重现**
点击菜单栏任意图标，再点击左右方向键

**Screenshots | 相关截图**
![image](https://user-images.githubusercontent.com/33802186/87224751-596efa00-c3ba-11ea-8c1b-5ad1e123fb17.png)

**Additional context | 额外说明**
隐藏时不要设置为宽度=0， 试试下面的代码
```swift
statusItem.isVisible = false
```

**Comment by L1cardo** [comment]
翻看了一下代码，果然是宽度设为了 0

![image](https://user-images.githubusercontent.com/33802186/87224840-35f87f00-c3bb-11ea-81c2-867889848315.png)

**Comment by Caldis** [comment]
印象中一开始用的就是设置 visible 的方式, 好像后来是和 显示/隐藏 图标的功能有冲突, 才换成了设置 length 的方式, 我有空看看
