### ISSUE TITLE
反弹滑动

### ISSUE THREAD

**Issue by hu6360567** [Caldis/Mos#28]
![8 -20-2017 23-12-57](https://user-images.githubusercontent.com/1241597/29496056-528e92fc-85fd-11e7-8527-b5782f52bc61.gif)

鼠标是MX anywhere2，没有安装Options。
只有在b站该位置，上滚时，在最后减速阶段会反弹下滑。

**Comment by Caldis** [comment]
B站这里估计是用了页面内嵌的平滑滚动插件, 导致有这种怪异的冲突...
用触控板在这里滑动也有怪怪的手感

**Comment by Caldis** [comment]
@hu6360567 
我试了一下我的 MX anywhere2 , 只有 Chrome下会这样, Safari没有问题, 你是否也是用 Chrome 测的?

**Comment by hu6360567** [comment]
@Caldis 是chrome
