### ISSUE TITLE
我比较追求稳定。倒不需要经常更新。所以有考虑过给稳定版做一下Apple的公证吗？安装启动不方便

### ISSUE THREAD

**Issue by hugbio** [Caldis/Mos#281]
公证可能需要点时间，不过我建议稳定版不需要经常更新，毕竟这东西我感觉比较追求稳定。但是现在因为新系统限制。安装后，无法直接打开，需要手动去隐私设置中启动。比较不方便。对于小白可能是灾难性的。
所以，希望作者辛苦点能否做一下公证？

**Comment by Chandler-Lu** [comment]
开发者证书一年99刀，兄弟

**Comment by Caldis** [comment]
公证并不费太多时间，费钱
