### ISSUE TITLE
3.1安装后，授权引导，导致系统卡死

### ISSUE THREAD

**Issue by hugbio** [Caldis/Mos#282]
描述：首次启动。根据说明引导，打开系统偏好设置的辅助功能授权（因为旧版本已经授权过，所以已经打勾了），根据说明需要重新取消勾选再勾选。于是发现点击勾选无法取消勾选。多次点击尝试后，发现系统卡死现象：鼠标可以动。但是无法无法点击和右键，单击或者右键均无法反应。最后通关打开终端通过命令强制重启

**To Reproduce | 如何重现  ： 暂时无法重现

**System Info | 系统信息:**
 - Mouse: 小米无线鼠标
 - OS: mac os 10.15.5
 - Browser chrome
 - Version  3.1.0

**Comment by Ye-Chenhao** [comment]
Open System Preferences -> Security & Privacy. You will see Mos is blocked by your system. Check to let it run.

**Comment by gtming0508** [comment]
![image](https://user-images.githubusercontent.com/35806300/92229889-bed3f880-eedc-11ea-8287-b62a7421e4c4.png)
@hugbio
