### ISSUE TITLE
例外Minecraft遊戲的時候就會閃退

### ISSUE THREAD

**Issue by bs10081** [Caldis/Mos#283]
**Describe the bug | 问题描述**
當我啟動Minecraft的時候，會有一個java的程式在運行，進去MOS屏蔽的時候便閃退了
**To Reproduce | 如何重现**
在例外中屏蔽Minecraft就會問題重現
**Expected behavior | 期望结果**
希望能修復屏蔽Minecraft的閃退問題
**Screenshots | 相关截图**
<img width="122" alt="截圖 2020-07-19 下午2 15 54" src="https://user-images.githubusercontent.com/38148679/87868621-66977480-c9ca-11ea-82ed-0f6b5a6facfd.png">
**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
 - OS: macOS [e.g. iOS]
 - Version [e.g. v69]
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by arbego** [comment]
Confirmed on macOS Catalina. MOS crashes after adding running minecraft instance (java) to exceptions.

**Comment by BaiSheng10081** [comment]
Okay, thank you.

**Comment by Caldis** [comment]
新版本已修复 https://github.com/Caldis/Mos/releases/tag/3.3.1
