### ISSUE TITLE
和 BetterTouchTool 一起使用，导致 BetterTouchTool 监听不到鼠标滚动滑轮

### ISSUE THREAD

**Issue by Acmu** [Caldis/Mos#284]
**Describe the bug | 问题描述**
和 BetterTouchTool 一起使用，导致 BetterTouchTool 监听不到鼠标滚动滑轮
**To Reproduce | 如何重现**
先启动 Mos 后启动 BetterTouchTool，会产生问题。
但先启动 BetterTouchTool，后启动 Mos，就正常
**Expected behavior | 期望结果**
我都是 开机自启的，控制不了顺序，期望能正常使用
如下是 BetterTouchTool 配置，主要是使用 滚轮 实现切换 mission control

**Screenshots | 相关截图**
![image](https://user-images.githubusercontent.com/35673748/88356386-3836e200-cd9a-11ea-8ead-1d88c39b7853.png)

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
 - Version [e.g. v69]
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

mbp 10.15.5 (19F101)

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/releases/tag/3.3.1

**Comment by Caldis** [comment]
试了一下, 应该没有问题了

**Comment by louishino** [comment]
最新版也有这种神奇的bug 开了mos btt有时候检测滚轮不灵敏
