### ISSUE TITLE
can add horizontal smooth roll function?

### ISSUE THREAD

**Issue by hellomos** [Caldis/Mos#285]
Hi,

Im using Logitech MX Master 3 but i found out horizontal scroll cannot scroll smoothly. Can help to add horizontal smooth function?

**Comment by rodriigovieira** [comment]
Well, I managed to restore horizontal scrolling by opening the application, going to "Advanced" and setting the Block Key to Shift. When I press shift, it disables the smooth scrolling and I'm capable of scrolling horizontally.

That does not solves your issue, though. The scroll is back, but it's not smooth. I just posted that to someone that might be looking for a way to reactivate horizontal scroll while at the same time keeping smooth vertical scroll.

**Comment by voltechs** [comment]
@rodriigovieira clever workaround. Thanks. I came looking to report the issue (but searched first, like a good citizen), and found your work around.

I'd also like support for this, or at least, not interfering with the horizontal scrolling (I'm on macOS Catalina). I prefer to use shift for the Dash key, but I will use this for now as a work around.

**Comment by rodriigovieira** [comment]
> @rodriigovieira clever workaround. Thanks. I came looking to report the issue (but searched first, like a good citizen), and found your work around.
> 
> 
> 
> I'd also like support for this, or at least, not interfering with the horizontal scrolling (I'm on macOS Catalina). I prefer to use shift for the Dash key, but I will use this for now as a work around.

I believe you can set the "Block Key" to other options other than shift, if that suits you.

**Comment by voltechs** [comment]
> I believe you can set the "Block Key" to other options other than shift, if that suits you.
Indeed! The trade off then would be needing to press two keys, shift and the block key, to get horizontal scrolling.

**Comment by alvarotrigo** [comment]
Yeap, I'm interested on this too.
I was quite surprised when I found out that Mos didn't scroll horizontally when using the mouse wheel. This is specially useful for us developers who enjoy big fonts and have to quite often scroll horizontally to read the whole code.

**Comment by Caldis** [comment]
Fixed in latest version: https://github.com/Caldis/Mos/releases/tag/3.3.1
