### ISSUE TITLE
无法打开“Mos.app”，因为Apple无法检查其是否包含恶意软件。

### ISSUE THREAD

**Issue by fengtalk** [Caldis/Mos#286]
**Describe the bug | 问题描述**
安装之后，打开Mos时会出现
> 无法打开“Mos.app”，因为Apple无法检查其是否包含恶意软件。
**To Reproduce | 如何重现**
打开Mos。
**Expected behavior | 期望结果**
正常运行。
**Screenshots | 相关截图**
![image](https://user-images.githubusercontent.com/2913058/88541113-d222b700-d046-11ea-8293-47374f702c3e.png)

**System Info | 系统信息:**
 - Mouse: [Logitech M558]
 - OS: [Catalina]
 - Version [10.15.6]

**Additional context | 额外说明**
Mos.app的版本为当前最新版3.1.0。

**Comment by Caldis** [comment]
没钱交苹果税所以没法上 Developer ID 证书签名...
弹出这个窗口之后去 设置->安全性与隐私->通用 里面放行就好

**Comment by Eve-Sama** [comment]
![图片](https://user-images.githubusercontent.com/30228406/183862266-cdf9cae6-e108-4fa5-b591-b12d64e81641.png)
我这样设置,  但还是打不开
![图片](https://user-images.githubusercontent.com/30228406/183862346-cc40acda-bdcf-4e11-9e51-39375558318b.png)

**Comment by Eve-Sama** [comment]
解决了. 需要在同样下面点击'仍要执行'

**Comment by daniuyue** [comment]
解决了. 需要在同样下面点击'仍要执行'。 这个在哪里找啊没有看到

**Comment by daniuyue** [comment]
> 解决了. 需要在同样下面点击'仍要执行'

没有这个弹窗

**Comment by daniuyue** [comment]
> > 解决了. 需要在同样下面点击'仍要执行'
> 
> 没有这个弹窗

有了。哈哈哈

**Comment by dajinlou** [comment]
> ![图片](https://user-images.githubusercontent.com/30228406/183862266-cdf9cae6-e108-4fa5-b591-b12d64e81641.png) 我这样设置, 但还是打不开 ![图片](https://user-images.githubusercontent.com/30228406/183862346-cc40acda-bdcf-4e11-9e51-39375558318b.png)

有用。感谢
