### ISSUE TITLE
请问如何进入滚轮监控页面？

### ISSUE THREAD

**Issue by nb5p** [Caldis/Mos#287]
**Describe the bug | 问题描述**
请问Mos 3.1如何进到下图中的界面，我记得2.x版本好像菜单里有，但是新版本找不到入口了

**Screenshots | 相关截图**
https://github.com/Caldis/Mos/raw/master/docs/resources/image/cn/Mointor.png?raw=true

**System Info | 系统信息:**
 - Version: 3.1
 -  Application: Whole System

**Comment by choyri** [comment]
[发行说明](https://github.com/Caldis/Mos/releases/tag/3.1.0) 里有这么一句话：

> 考虑到滚动监控的使用频率, 现在它被雪藏了, 只有在按下 **Options** 并点击状态栏的图标后才能看到滚动监控的选项。

**Comment by nb5p** [comment]
> [发行说明](https://github.com/Caldis/Mos/releases/tag/3.1.0) 里有这么一句话：
> 
> > 考虑到滚动监控的使用频率, 现在它被雪藏了, 只有在按下 **Options** 并点击状态栏的图标后才能看到滚动监控的选项。

Thx
