### ISSUE TITLE
使用Mos时会导致Chrome浏览器页面顶部底部出现白屏

### ISSUE THREAD

**Issue by linvon** [Caldis/Mos#288]
**Describe the bug | 问题描述**
Mos启用的情况下，浏览网页滚动时会超额滚动，导致顶部底部出现白屏，关闭Mos后正常
**To Reproduce | 如何重现**
Chrome浏览器打开V2EX或者GitHub，刷新页面并在页面未加载完成时向顶部滚动
**Expected behavior | 期望结果**

**Screenshots | 相关截图**
https://i.imgur.com/iRN9Dus.jpg
**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
Logic G304
MacOS 10.15.5 (19F96)
Chrome 
 - Version [e.g. v69]
版本 84.0.4147.105
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**
这看起来像是Chrome浏览器的BUG，可能是chromium内核的浏览器有问题，我试过新版edge也有问题，但Safari是没有问题的。同时试用了其他平滑滚动软件，发现有同样问题，如果确认是浏览器问题，也烦请关闭此Issue了。

**Comment by choyri** [comment]
问题加一。详细的复现步骤：
刷新网页时用鼠标向上滚。此后，鼠标滚轮失去作用，只能用触控板滚动，而触控板一滚，页面随即恢复，包括鼠标滚轮。

**Comment by Acmu** [comment]
+1
我也遇见过好多次，但好像不能稳定复现

**Comment by FKPYW** [comment]
我还以为chrome插件太多 bug了

**Comment by tcgbp** [comment]
Chrome下Reload + 向上滚动 就可以稳定重现    不过点击一下滚动条就恢复了

**Comment by kong36088** [comment]
出现问题+1，求修复

**Comment by Caldis** [comment]
是已知问题... 目前没有什么好解法, 应该是 Chrome 在初始化页面的时候对滚动事件有什么特殊处理

**Comment by Caldis** [comment]
修好了: https://github.com/Caldis/Mos/releases/tag/3.3.1
