### ISSUE TITLE
Per-mouse settings

### ISSUE THREAD

**Issue by sn0wyfall** [Caldis/Mos#291]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**

I use two mice. One of them has good scrolling, the other one is really slow. I'm wondering if it's possible to change the scrolling acceleration and whatnot of mouses individually.

**说说你的新点子 | Describe the solution you'd like**

Being able to change the scroll settings per-mouse

**还有别的替代方案吗？ | Describe alternatives you've considered**

SteerMouse is a good program that can do per-device settings. However, its scroll smoothing didn't work for me.

USB Overdrive is another good program but it doesn't seem to detect mouses properly.

**Comment by Caldis** [comment]
Mos does not use IOKit for the underlying data interception, and therefore cannot distinguish between specific devices by now.
