### ISSUE TITLE
Apple cannot check Mos for malicious software

### ISSUE THREAD

**Issue by Kalaschnik** [Caldis/Mos#295]
When I try to open Mos I get this:

![image](https://user-images.githubusercontent.com/9831678/89658174-7ff75680-d8ce-11ea-82c9-e9096a5c73fd.png)

**Comment by otakustay** [comment]
Same issue, not fixed by installing the latest version

**Comment by Caldis** [comment]
Mos is not notarized, so it will be blocked by the gatekeeper on your macOS, you can bypass it by editing the ```com.apple.quarantine``` property
ref: https://superuser.com/questions/28384/what-should-i-do-about-com-apple-quarantine

Or just compile the source code yourself

**Comment by Kalaschnik** [comment]
Thanks that did it: `˜/Applications xattr -d com.apple.quarantine Mos.app`

**Comment by bartekpacia** [comment]
`$ cd /Applications`
`$ xattr -d com.apple.quarantine Mos.app`

**Comment by MitchellX** [comment]
> Thanks that did it: `˜/Applications xattr -d com.apple.quarantine Mos.app`

Thanks, dude. works for me.

**Comment by arsoni20** [comment]
> `$ cd /Applications` `$ xattr -d com.apple.quarantine Mos.app`

Thanks so much!! It worked like a charm!

**Comment by shohanursobuj** [comment]
`$ xattr -d com.apple.quarantine /Applications/Mos.app` 

macOS Sonoma
