### ISSUE TITLE
请求支持快捷键 command + q 退出应用

### ISSUE THREAD

**Issue by Acmu** [Caldis/Mos#296]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**

是的，来源于这里：https://github.com/Caldis/Mos/issues/284

**说说你的新点子 | Describe the solution you'd like**

希望支持快捷键 command + q 退出应用，这样我能尽快重启 Mos，也算是另一种解决方案吧，而且这个操作应该很通用，不知道为什么 Mos 不支持

**还有别的替代方案吗？ | Describe alternatives you've considered**

无

**额外说明 | Additional context**

无

**Comment by Caldis** [comment]
不妨说说为什么要重启。。。
快捷键由于目前应用隐藏了 Dock 的 Icon, 所以无法独立响应快捷键事件

**Comment by Acmu** [comment]
上面有说，问题来源于这里 https://github.com/Caldis/Mos/issues/284

就是要保证在 BetterTouchTool 之后启动，才能不影响到 BetterTouchTool 的鼠标滑轮监听。
长时间锁屏，也会导致 BetterTouchTool 的鼠标滑轮监听不能用，所以我每次都要重启 Mos 才能正常使用，不能支持快捷键的话，增加一个 重启 也不错。

主要是感觉这里可能不好改，因为是 Mos 先启动， BetterTouchTool 后启动，BetterTouchTool 不好用，反过来的话就都可以正常使用了。

能方便 重启 Mos 的话，也算是曲线救国吧。

还有 Mos 是真的好用，点赞👍

**Comment by Caldis** [comment]
新版本重构了底层的监听层级, 应该不会影响到了
https://github.com/Caldis/Mos/releases/tag/3.3.1

**Comment by Caldis** [comment]
顺便也可以帮忙测试一下 https://github.com/Caldis/Mos/issues/284 有没有被解决
