### ISSUE TITLE
Big Sur 上，即使选择隐藏 Status Bar 图标，仍占据部分空间。

### ISSUE THREAD

**Issue by craigary** [Caldis/Mos#297]
**Describe the bug | 问题描述**

如题，在 Big Sur 上，即使选择隐藏 Status Bar 图标，仍占据部分空间。从 Beta 1 开始，到目前 Beta 4 上仍然是这样。

**To Reproduce | 如何重现**

1. 系统运行 MacOS Big Sur Beta 版本；
2. 安装 MOS App，配置好基础设置后，启用「Hide Status Bar Icon」选项。
3. Icon 隐藏，但仍占据部分空间，指针移到上面没有 Hover 的效果，但可以按住 Cmd 拖动，不可拖出。

**Expected behavior | 期望结果**

彻底隐藏 Status Bar Icon。

**Screenshots | 相关截图**

Before:
<img width="617" alt="Screen Shot 2020-08-13 at 18 30 21" src="https://user-images.githubusercontent.com/10571717/90124506-175b1e80-dd93-11ea-889a-5e8ac34890c9.png">

After:
<img width="617" alt="Screen Shot 2020-08-13 at 18 30 35" src="https://user-images.githubusercontent.com/10571717/90124542-217d1d00-dd93-11ea-8836-7cac4879e75c.png">

**System Info | 系统信息:**

 - Mouse: [ Logitech M590 ]
 - OS: [ macOS 11 Beta 4 ]
 - Browser [ Irrelevant ]
 - Version [ 3.1.0 ]
 -  Application [ Irrelevant ]

**Additional context | 额外说明**
另，这个 Status Bar Icon 是不是有点小了😂

**Comment by Acmu** [comment]
为啥你们隐藏图标就不能用个 App 呢？比如 Hidden Bar  https://github.com/dwarvesf/hidden

这种任何 App 图标都能隐藏，不香吗，为什么非要让 Mos 支持隐藏图标呢？

**Comment by craigary** [comment]
> 为啥你们隐藏图标就不能用个 App 呢？比如 Hidden Bar https://github.com/dwarvesf/hidden
> 
> 这种任何 App 图标都能隐藏，不香吗，为什么非要让 Mos 支持隐藏图标呢？（导致我都不能按 command + q 退出应用了。。。）

Big Sur 上 Bartender 应该还不能用。没有测试 Hidden Bar...
Hmmm 隐藏图标这个 Feature 既然做了…有 Bug 还是要提嘛😂

**Comment by Mr-UFO** [comment]
这个问题应该由MacOS开发者解决|this question owns to developer of apple.inc
从搜狗拼音输入法切换到其他输入法时，搜狗输入法在标题栏仍旧占空白空间.可见并不是某个软件的特有问题
![image](https://user-images.githubusercontent.com/59684700/91162960-62fcb900-e6ff-11ea-9f08-747e1975bbaf.png)
![image](https://user-images.githubusercontent.com/59684700/91162986-6db74e00-e6ff-11ea-9771-27b9ae0234d9.png)

**Comment by craigary** [comment]
> 这个问题应该由MacOS开发者解决|this question owns to developer of apple.inc
> 从搜狗拼音输入法切换到其他输入法时，搜狗输入法在标题栏仍旧占空白空间.可见并不是某个软件的特有问题
> ![image](https://user-images.githubusercontent.com/59684700/91162960-62fcb900-e6ff-11ea-9f08-747e1975bbaf.png)
> ![image](https://user-images.githubusercontent.com/59684700/91162986-6db74e00-e6ff-11ea-9771-27b9ae0234d9.png)

不认同，显然这种隐藏的办法是用了 Hack 的方式，之前图标宽度为 0 就没问题，现在 Apple 加了 Padding，才出现了这个情况。如果举例子来合理化的话……1password 隐藏图标就没有任何问题啊

**Comment by Caldis** [comment]
之前使用 length 的方式是为了兼容 10.11, 下个版本会修正该问题

**Comment by Caldis** [comment]
新版本已修复 https://github.com/Caldis/Mos/releases/tag/3.3.1
