### ISSUE TITLE
“例外”下的应用程序列表显示不全

### ISSUE THREAD

**Issue by 2O48** [Caldis/Mos#299]
**Describe the bug | 问题描述**
“例外”下的应用程序列表显示不全，有时是一部分应用程序被遮住，也有情况是遮住一大半只露出一小部分，导致左边的勾没法点

**To Reproduce | 如何重现**
应用列表划到底部

**Expected behavior | 期望结果**
完全显示

**Screenshots | 相关截图**
<img width="562" alt="截屏2020-08-15 15 50 19" src="https://user-images.githubusercontent.com/21039418/90308083-06cfb300-df0f-11ea-815b-94419565e28a.png">

**System Info | 系统信息:**
 - Mouse: [--]
 - OS: [macOS 11]
 - Browser [Chrome]
 - Version [84]
 -  Application [Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
感谢反馈，BugSur 的系统 UI 改动影响有点大

**Comment by Caldis** [comment]
已修复: https://github.com/Caldis/Mos/releases/tag/3.3.1
