### ISSUE TITLE
点击“开机启动”自动退出应用

### ISSUE THREAD

**Issue by JeromeLiee** [Caldis/Mos#30]
MacOS版本：10.12.6
Mos版本：1.6.0

打开Mos的偏好设置，点击“开机启动”，应用会退出，必现。

**Comment by Caldis** [comment]
我也是 10.12.6, 但是无法复现...
是不是某些应用导致冲突?

**Comment by Chandler-Lu** [comment]
测试了一下，10.12.6我这里也没有问题～

**Comment by Tsahao** [comment]
10.13 public beta 9 必现

**Comment by newpanjing** [comment]
降级吧 12.13太卡了 很多不兼容

发自我的 iPhone

**Comment by Caldis** [comment]
因为添加开机启动项的实现用了LSSharedFile, 有可能是在新版本这个API被弃用导致应用异常, 暂时请手动添加到登陆项里面来开机启动

吐槽: 
我去找添加启动项的 API, 找到 LSSharedFile 文档说这个API即将弃用, 请用 Service Management 
然后我再去看 Service Management 的API, 跟我说请使用 Launch Services, 那个更方便
最后找到 Launch Services 的文档, 说请使用 LSSharedFile
Yay
