### ISSUE TITLE
影响到了微信的表情窗口的滑轮滚动

### ISSUE THREAD

**Issue by Robot-L** [Caldis/Mos#300]
**Describe the bug | 问题描述**
在微信的表情选择浮窗中滚动滑轮，本来是可以横向切换表情面板的，使用MOS后快速滑动无法切换面板，只能滚一下，等一下再滚动，才可以正常切换

**To Reproduce | 如何重现**
打开表情浮窗，快速滚动滑轮

**Expected behavior | 期望结果**
聊天窗口平滑滚动的同时不影响表情浮窗的使用

**Screenshots | 相关截图**
![image](https://user-images.githubusercontent.com/16471200/90999414-1929ab00-e5f9-11ea-9713-cdf8e26e42c1.png)

**System Info | 系统信息:**
 - Mouse: 普通无线鼠标
 - OS: Mac 10.15.5 
 - 微信：Version. 2.4.2 (15067)

**Additional context | 额外说明**
虽然可以使用快捷键禁用Mos，但还是希望能分析下原因，优化体验

**Comment by Caldis** [comment]
应用内的部分滚动交互目前是无解的，可以试下把Shift绑定为转换键然后在这里按住来滚动试试
