### ISSUE TITLE
Consider creating a linux version

### ISSUE THREAD

**Issue by jonseppanen** [Caldis/Mos#302]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**
No

**说说你的新点子 | Describe the solution you'd like**
I would love a linux version of this tool.

**还有别的替代方案吗？ | Describe alternatives you've considered**
There are none.

**额外说明 | Additional context**
Nothing additional.

**Comment by Caldis** [comment]
Thanks for the suggestion but at the moment I don't have the time to maintain more versions, considering that Linux uses a completely different interface framework.
