### ISSUE TITLE
开启平滑滚动时safari网页标签无法横向滚动

### ISSUE THREAD

**Issue by wp161** [Caldis/Mos#303]
**Describe the bug | 问题描述**
偏好设置中开启平滑滚动时，在safari无法在标签页栏横向滚动浏览已经打开的标签页，关闭平滑滚动则恢复正常

**To Reproduce | 如何重现**
开启平滑滚动-打开safari-打开若干标签页-鼠标指针移到标签页栏上滚动鼠标滚轮-标签页栏无法横向左右滚动

**Expected behavior | 期望结果**
能在平滑滚动开启的状态下使用鼠标滚轮滚动浏览标签页栏中的标签页

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: Dell WM116p
 - OS: macOS 10.13.6 (17G13035)
 - Browser: Safari
 - Version: 13.1.2 (13609.3.5.1.5)
 -  Application: Safari

**Additional context | 额外说明**
无

**Comment by ChadCSong** [comment]
遇到了同样的问题，Mac系统下，按住shift+滚动是横划的命令。用了这个之后都变成竖着划了。

**Comment by 1607941875** [comment]
同样的问题

**Comment by Caldis** [comment]
应用内的部分交互目前无解，不过我在 BigSur 上可以正常滚动 Safari 的 Tab 标签栏，或许你可以考虑升级 ？

**Comment by Caldis** [comment]
@ChadCSong 请在设置中将 Shift 设置为转换键
