### ISSUE TITLE
Can't add Java process

### ISSUE THREAD

**Issue by alienjax** [Caldis/Mos#306]
**Describe the bug | Can't add a Java app (.jar) or java executable (bin/java). When I choose the java executable (bin/java) in Mos the program quits.

**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
 - OS: 10.15.6 (19G2021)
 - Version 3.1.0
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
Application crashes are a known issue and will be fixed in subsequent releases
Maybe you're playing Minecraft? I tried adding Minecraft Launcher to the exceptions list and the settings are working for the game

**Comment by Caldis** [comment]
Fixed in latest release https://github.com/Caldis/Mos/releases/tag/3.3.1
