### ISSUE TITLE
Launch on Login feature not working as expected

### ISSUE THREAD

**Issue by Ryanfsdf** [Caldis/Mos#308]
**Describe the bug | 问题描述**
"Launch on Login" does not enable smooth scrolling sometimes. This seems to happen roughly half the time. The scrolling is smoother than without Mos, but not as smooth as when Mos is opened without the "Launch on Login" feature. If I turn off Mos using "Quit" and reopen it, scrolling becomes smooth again. I'm guessing there's some sort of race condition on macOS startup that causes this issue. I wrote a script to wait 10 seconds before starting up Mos when my MacBook starts up and that fixed the issue for me.

**To Reproduce | 如何重现**
1) Turn on "Launch on Login"
2) Restart the MacBook
3) Turn on any application that scrolls (ex. Chrome)

**Expected behavior | 期望结果**
Scrolling is not as smooth as it can be. If Mos is restarted, scrolling becomes smooth.

**System Info | 系统信息:**
 - Device: MacBook Pro 16" 2019
 - OS: [e.g. iOS] macOS 10.15.6
 -  Application [e.g. Safari, Chrome, Whole System]: Any application (ex. Chrome, Microsoft Word, Spotify, etc)

**Additional context | 额外说明**

**Comment by Caldis** [comment]
谢谢你的反馈，我想是启动应用程序时产生了某些冲突启动了多个滚动截取器导致的

**Comment by Caldis** [comment]
Thanks for the feedback, I think it's caused by some conflict launching multiple scrolling interceptors when launching the app.

**Comment by Caldis** [comment]
Fixed: https://github.com/Caldis/Mos/releases/tag/3.3.1
