### ISSUE TITLE
Too fast zooming

### ISSUE THREAD

**Issue by jordanslon** [Caldis/Mos#310]
**Too fast and crazy horizontal scroll and zooming** 

it will be awesome to setting up horizontal and zooming (z-axis scroll) separately from vertical zooming, right now Mos is a-bit discomfortable in use for designers. Designers often zooming and scrolling horizontally to much and as designer is annoying to use Mos.

How it looks now, i'm doing just 1-2 step scrolls:
- zooming in Sketch https://streamable.com/tzqtuf
- zooming in illustrator https://streamable.com/4pyybl
- horizontal scroll in Sketch https://streamable.com/qfl68t

**Comment by Caldis** [comment]
Ok, let me explain using Sketch as an example.
In screen scrolling, there is no Z axis, only X-Y axis/plane. When you scroll the wheel in Sketch, Sketch reads the scrolling data and maps it to the scaling of the interface. That is, as long as you adjust the speed of the Y-axis, you can adjust the scaling speed and scale. But the interpolated scrolling data will often not be what you expect - the scrolling distance may be too little or too much. You can use the Block Key in Advanced Settings and hold down Disable while scrolling to adjust the scrolling scale precisely, although this may not be very smooth. Or you can set Sketch as an exception and adjust the scrolling speed for it.
Ultimately, how the app maps the scrolling data for the X-Y axes to the corresponding behavior is beyond Mos's ability to interfere with. You can only affect the mapping results by adjusting Mos' existing settings.

**Comment by jordanslon** [comment]
it will be great to have ability detailed settings. as i wrote in initials message, there is missed settings for zoom. In General, it would be ideal to settings individually scroll for each app, for example: i'd like to switch off zoom smoothing for graphic apps and a-bit different setup horizontal scrolling too.

Anyway You've do great job! Thanks!

**Comment by Caldis** [comment]
Thanks for your support
