### ISSUE TITLE
求原图

### ISSUE THREAD

**Issue by bdingtech** [Caldis/Mos#311]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**

**说说你的新点子 | Describe the solution you'd like**

**还有别的替代方案吗？ | Describe alternatives you've considered**

**额外说明 | Additional context**
大佬可以发一下release2.3.0和3.1.0的原图吗，Google找了一圈没找到，是大佬自己拍的吗？

**Comment by Caldis** [comment]
是自己拍的
