### ISSUE TITLE
Big Sur下菜单栏图标无法完全隐藏

### ISSUE THREAD

**Issue by Voring** [Caldis/Mos#312]
**Describe the bug | 问题描述**
在Big Sur下，在mos的偏好设置中选中隐藏菜单栏图标，实际上并未完全隐藏，而是以透明形式占用一格，由于Big Sur空隙本身就比较大，所以出奇的显眼。

**Expected behavior | 期望结果**
希望能够真正隐藏mos的菜单栏图标，而不是变透明状态占用空间。

**Screenshots | 相关截图**
图一为未启动mos时的菜单栏
<img width="237" alt="iShot2020-09-23 16 35 16" src="https://user-images.githubusercontent.com/64722054/93988503-61d0b180-fdbb-11ea-8aab-a9f381cf9e03.png">
图二为开启mos时，我特意将其拖到QQ和输入法中间以便对比
<img width="250" alt="iShot2020-09-23 16 35 35" src="https://user-images.githubusercontent.com/64722054/93988625-862c8e00-fdbb-11ea-9024-6ab1fc21e96c.png">
图三是在mos的偏好设置中隐藏了mos后的菜单栏，可以明显看到mos位置处占用了一个格子，且可按住command对这个“透明图标”进行拖动。
<img width="237" alt="iShot2020-09-23 16 42 46" src="https://user-images.githubusercontent.com/64722054/93988876-d146a100-fdbb-11ea-96d6-6998bdf069e4.png">

**System Info | 系统信息:**
 - OS: macOS 11.0 Big Sur
 -  Application Mos3.1.0

**Comment by wangchenxi005966** [comment]
对的，我也发现了这个问题

**Comment by craigary** [comment]
我也遇到了，之前已经反馈了 #297

**Comment by Chandler-Lu** [comment]
原来是mos的问题。。我就说总多了一个格子是啥，还点不到😂

**Comment by supreme429** [comment]
> **Describe the bug | 问题描述**
> 在Big Sur下，在mos的偏好设置中选中隐藏菜单栏图标，实际上并未完全隐藏，而是以透明形式占用一格，由于Big Sur空隙本身就比较大，所以出奇的显眼。
> 
> **Expected behavior | 期望结果**
> 希望能够真正隐藏mos的菜单栏图标，而不是变透明状态占用空间。
> 
> **Screenshots | 相关截图**
> 图一为未启动mos时的菜单栏
> <img alt="iShot2020-09-23 16 35 16" width="237" src="https://user-images.githubusercontent.com/64722054/93988503-61d0b180-fdbb-11ea-8aab-a9f381cf9e03.png">
> 图二为开启mos时，我特意将其拖到QQ和输入法中间以便对比
> <img alt="iShot2020-09-23 16 35 35" width="250" src="https://user-images.githubusercontent.com/64722054/93988625-862c8e00-fdbb-11ea-9024-6ab1fc21e96c.png">
> 图三是在mos的偏好设置中隐藏了mos后的菜单栏，可以明显看到mos位置处占用了一个格子，且可按住command对这个“透明图标”进行拖动。
> <img alt="iShot2020-09-23 16 42 46" width="237" src="https://user-images.githubusercontent.com/64722054/93988876-d146a100-fdbb-11ea-96d6-6998bdf069e4.png">
> 
> **System Info | 系统信息:**
> 
> * OS: macOS 11.0 Big Sur
> * Application Mos3.1.0

可以用bartender4完美解决

**Comment by Caldis** [comment]
已修复: https://github.com/Caldis/Mos/releases/tag/3.3.1
