### ISSUE TITLE
在 Big Sur 里 Minecraft 还是无法添加例外名单

### ISSUE THREAD

**Issue by Unichy** [Caldis/Mos#314]
**Describe the bug | 问题描述**
请查看[#112](https://github.com/Caldis/Mos/issues/112)
.jar文件无法添加进名单

**To Reproduce | 如何重现**
不好意思问这个问题添麻烦，但是在Big Sur里Minecraft的Java Process还是无法添加到外名单里，我不知道在Catalina里修没修好。

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
 - Version [e.g. v69]
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
Thanks for the feedback, sorry I don't know much about Minecraft, I tried the demo version downloaded from the official website and it is configurable after adding the Minecraft Launcher.app to the exception list, where could I get the JAR version of Minecraft?

**Comment by thomas-art** [comment]
链接: https://pan.baidu.com/s/1QYVYnLG_V3Pv1WlbvtgkuQ 提取码: j968 复制这段内容后打开百度网盘手机App，操作更方便哦

> Thanks for the feedback, sorry I don't know much about Minecraft, I tried the demo version downloaded from the official website and it is configurable after adding the Minecraft Launcher.app to the exception list, where could I get the JAR version of Minecraft?
> 
> 谢谢你的反馈，对不起，我对《我的世界》了解不多，我从官方网站下载了演示版本，在将《我的世界》的 Launcher.app 添加到例外列表后，它是可配置的，我在哪里可以得到《我的世界》的 JAR 版本？

**Comment by Unichy** [comment]
The launcher application for Minecraft is fine. However, it is impossible to set rules on the actual game. I am not sure, but I remember the issue being that the Minecraft game runs on the Java runtime and that it doesn’t have a bundle ID. This problem has to do with Java.

**Comment by Caldis** [comment]
新版本已修复 https://github.com/Caldis/Mos/releases/tag/3.3.1
