### ISSUE TITLE
Ability to set the animation duration to zero

### ISSUE THREAD

**Issue by ArttuLai** [Caldis/Mos#316]
### 这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.
I think it would be great if we could disable the smooth scrolling *animation.*

### 说说你的新点子 | Describe the solution you'd like
I'd like the ability to either slide the animation duration slider to zero, or have a checkbox that disables the animation altogether, under Preferences --> Advanced --> Duration. 

### 额外说明 | Additional context
I think it would be great if we could disable the animation, which could make the app lighter to run (right?), and have this option for people who prefer to have quicker and snappier scrolling. The app already runs lightly and I really think it's a great app, but this would just be a cherry on top.

**Comment by Caldis** [comment]
well... smooth scrolling without animation, why not just disable it ?

**Comment by ArttuLai** [comment]
> why not just disable it ?

Because then I’d lose the ability to "jump predefined number of pixels per one mousewheel tick" effect the app does.

...right? 😅

It might be called Smooth Scrolling but I look at it more like the ability to customize what my wheel does with every scrollwheel tick, and I kinda like the snappiness of animation-less jumpy scrolling (or at least one that's even quicker than what the current lowest duration setting allows).

It's really just nitpicking, the app is awesome!

**Comment by balthild** [comment]
Maybe you could try this: https://github.com/gavinlynch/scroll-sanity ?
