### ISSUE TITLE
Apple cannot check if this software is malicious

### ISSUE THREAD

**Issue by RafalLukawiecki** [Caldis/Mos#318]
It looks like the downloadable app does not have a valid signature:

<img width="418" alt="Screenshot 2020-10-20 at 19 58 09" src="https://user-images.githubusercontent.com/22912705/96631743-a2661100-130e-11eb-8e9d-f8d7616d0413.png">

Are there plans for this app to get signed, or are we on our own validating it for malicious code? Has any validation been done and reported?

**Comment by Caldis** [comment]
The app notarization process requires a valid AppleID that's enrolled in the dvelopeer program, which means you'll need to pay Apple $99 a year to keep the subscription in power to maintain the license. Instead, macOS will warn you, as you can see. The notarization can't block the malware, the only thing it can do is make the malware developers $99 less.
For the situation you meet. Just goto the SystemPreference->Security&Privacy->General and allow it.

**Comment by RafalLukawiecki** [comment]
Thank you for your reply @Caldis. While I disagree with your assessment of the value of the Apple Developer programme, I fully understand why you may not be able to join it.

Unfortunately, as there is a **lot** of software made in China that happens to be insecure, malicious, and even contains backdoors for the Chinese officials to spy on the rest of the world, I would feel more secure if Mos came with the blessing from Apple Developer Programme. In the absence of that all I could do is to do a security review the source code. Arguably, that would be the better option, but not one I have the time for at the moment...

Many thanks for your time and best of luck.

**Comment by Caldis** [comment]
I totally agree with you about the Chinese software.In fact, as a Chinese, I also hate all kinds of software distributed by large Chinese commercial companies that collect all kinds of user information with no regard for user privacy, probably due to the top-down censorship of speech by the CCP. But we as Chinese inevitably need to use them, and sadly they are now spreading internationally, taking their practices out of China, and there is nothing I can do about it.

Security is really one of the issues that users need to be concerned about with Mos as an application that listens for system events, and I'm glad you can see that and point out the problems.

Hopefully Mos has made you look at Chinese developers' software a little differently.

Translated with www.DeepL.com/Translator (free version)

**Comment by RafalLukawiecki** [comment]
I feel your frustration—I was born in Poland during an era when things were quite difficult.

In no way do I question _your_ motives: the issue of security, even for open source projects, like yours, is an important one. You have said it very well yourself.

I have worked with many intelligent, well-intentioned, very helpful people from all over the world, including many from China. My concern is about possible interference with the code, not about the developer... Maybe one day I will be able to review the source, but not now. In general, any software that sits so deep inside an OS should have more security and privacy-focused code reviews. This is not just about Mos, it is a bigger issue.

Thank you for your kind and balanced answer, I appreciate it.

**Comment by DerinChiu** [comment]
Caldis脾气是真的好～
一个免费的osc项目在这抱怨啥呢，让他每年捐赠100刀给你就不会弹窗了

**Comment by uahero** [comment]
Hi Caldis. Thank you for the great app that makes my Logitec G603 to work properly with the Mac. Great job!

Please consider enrolling in the Apple Developers program. I would be happy to pay for the app to cover your costs as I am sure many people will. One Time 2$-5$ would be reasonable.

Also, please release M1 ARM-compatible version.

**Comment by Caldis** [comment]
@uahero Thanks for your suggestion, i will consider to using some more transparent donation channels for the plan

btw the latest version already release now https://github.com/Caldis/Mos/releases/tag/3.3.1
