### ISSUE TITLE
与betterTouchTool某些功能冲突

### ISSUE THREAD

**Issue by whip1ash** [Caldis/Mos#319]
**Describe the bug | 问题描述**
跟betterTouchTool某些功能冲突，在开启BTT时无法使用command+scoll up/down 触发页面的放大和缩小。
**To Reproduce | 如何重现**
经过测试跟启动的顺序有关系，目测需要先启动BTT，再启动Mos，难道在macOS中鼠标事件的传递也是冒泡式的？
**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
 - Version [e.g. v69]
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by whip1ash** [comment]
经过测试，不是软件启动顺序的问题，发现只要mac睡眠后，再打开就无法通过BTT定义的command+scoll up/down 触发页面的放大和缩小，kill掉mos进程再重启即可恢复。

**Comment by Caldis** [comment]
谢谢反馈, 新版本应该已经修复这个问题 https://github.com/Caldis/Mos/releases/tag/3.3.1
