### ISSUE TITLE
開啟平滑滾動, 滾動Chrome開發者工具Elemtents經常卡死

### ISSUE THREAD

**Issue by stardussky** [Caldis/Mos#320]
**Describe the bug | 问题描述**
開啟平滑滾動, 滾動Chrome開發者工具Elemtents經常卡死, 網頁元素越多時發生機率越大, 把分頁關掉重開才會復原。
**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [Logitech M110s]
 - OS: [MacOS Catalina]
 - Browser [chrome]
 - Version [3.1]
 -  Application [chrome]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
不确定问题原因是什么... 我也经常有这个使用场景, 但是没有遇到过
你可以试试新版本有没有解决到问题
https://github.com/Caldis/Mos/releases/tag/3.3.1
