### ISSUE TITLE
按住 Shift 再滑动鼠标滚轮不会窗口里的内容不会左右滑动，只会上下滑动

### ISSUE THREAD

**Issue by Hanyuxiaoorz** [Caldis/Mos#323]
**Describe the bug | 问题描述**

在开启 MOS 后，按住 Shift 再滑动鼠标滚轮不会窗口里的内容不会左右滑动，只会上下滑动。

**To Reproduce | 如何重现**

打开程序，在横向内容足够宽且下方出现左右滑动条的内容中，按住 Shift 再滑动鼠标滑轮，其中内容依旧只会上下滑动。

目前发现问题的应用程序有：Chrome xmidn IDEA 有道云笔记等

**Expected behavior | 期望结果**

按住 Shift 后内容会左右滚动而不是上下滚动

**Screenshots | 相关截图**

暂无

**System Info | 系统信息:**
 - Mouse: 雷蛇蝰蛇
 - OS: macOS 10.15.7
 - Browser chrome
 - Version 86.0.4240.111
 -  Application chrome xmind egg...

**Additional context | 额外说明**

暂无

**Comment by Hanyuxiaoorz** [comment]
这个不是问题，在【高级】当中可以自行设计【转换】快捷键

**Comment by congzhou09** [comment]
> 这个不是问题，在【高级】当中可以自行设计【转换】快捷键

感谢大佬！！太棒啦！

**Comment by yfabc123** [comment]
我也出现了  请问下 "这个不是问题，在【高级】当中可以自行设计【转换】快捷键" 这个高级指的是?
