### ISSUE TITLE
无法翻转妙控鼠标

### ISSUE THREAD

**Issue by denyot** [Caldis/Mos#325]
**Describe the bug | 问题描述**
无法翻转妙控鼠标2
**To Reproduce | 如何重现**
使用妙控鼠标2，开启mos
**Expected behavior | 期望结果**
正常翻转妙控鼠标2
**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [妙控鼠标2]
 - OS: [macOS Big Sur 11.0.1 (20B28)]

**Comment by jaykwok** [comment]
妙控鼠标和触摸板的操作逻辑原本就是一样的吧

**Comment by Caldis** [comment]
妙控鼠标过来的事件特征值跟触控板一致...所以目前没法区别处理, 抱歉
