### ISSUE TITLE
Hiding status bar icon not really hides icon

### ISSUE THREAD

**Issue by ozguncagri** [Caldis/Mos#327]
**Describe the bug | 问题描述**

Instead of hiding it; it only removes visible icon but it is still there just like divider between my icons. I can even move it around using cmd + drag it.

**To Reproduce | 如何重现**

- Move icon between any two icons
- Check "Hide Status Bar Icon"

Now you should see extra space where mos icon was.

**Expected behavior | 期望结果**

It has to remove icon completely.

**Screenshots | 相关截图**

Visible:

<img width="203" alt="image" src="https://user-images.githubusercontent.com/946294/99160525-47e78700-26f9-11eb-9d8a-27834f759439.png">

Hidden:

<img width="179" alt="image" src="https://user-images.githubusercontent.com/946294/99160542-75343500-26f9-11eb-8f96-a314da235d03.png">

You can even move it around while its hidden:

![out](https://user-images.githubusercontent.com/946294/99160604-14f1c300-26fa-11eb-8118-fdc9143c3abb.gif)

**System Info | 系统信息:**
 - OS: MacOS Big Sur 11.0.1 (20B29) Stable
 - Version Mos 3.1.0

**Comment by kidonng** [comment]
#297

**Comment by Caldis** [comment]
Fixed in latest release https://github.com/Caldis/Mos/releases/tag/3.3.1
