### ISSUE TITLE
mos添加java为例外时闪退

### ISSUE THREAD

**Issue by thomas-art** [Caldis/Mos#328]
**Describe the bug | 问题描述**
我想把一个正在运行的java应用添加为例外，可是添加时mos崩溃
**To Reproduce | 如何重现**
打开我的世界java版，打开mos主界面，点击例外，点击左下角加号，点击运行中的应用程序，选择java，mos崩溃
**Expected behavior | 期望结果**
解决
**Screenshots | 相关截图**
![iShot2020-11-15 10 23 47](https://user-images.githubusercontent.com/60135827/99161393-d7f2f400-272c-11eb-8dcc-536af81d9fe1.png)

**System Info | 系统信息:**
 - Mouse: 【 罗技g304]
 - OS: [macos catalina黑苹果]
 - Browser [chrome]
 - Version [e.g. v69]
 -  Application [hmcl.jar java]

**Additional context | 额外说明**
望解决
java:java.com

**Comment by thomas-art** [comment]
链接: https://pan.baidu.com/s/1QYVYnLG_V3Pv1WlbvtgkuQ 提取码: j968 复制这段内容后打开百度网盘手机App，操作更方便哦
我的世界jar版的下载地址

**Comment by kidonng** [comment]
#314

**Comment by Caldis** [comment]
新版本已修复 https://github.com/Caldis/Mos/releases/tag/3.3.1
