### ISSUE TITLE
Cannot Open on M1 ARM

### ISSUE THREAD

**Issue by junlingf** [Caldis/Mos#336]
- 问题描述 | Issue description:

![image](https://user-images.githubusercontent.com/52867725/101440589-ed8eb000-38cb-11eb-9dc8-a75cd7279a79.png)
无法打开
Cannot Open Under macOS Big Sur 11.0.1, on M1 Mac-Mini 2020

- 如何重现 | How to reproduce it:
Tried to install with brew and .dmg file. Both are malicious.

- 系统版本 | System version:
Mouse: Logitech G304
OS: macOS Big Sur

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:

**Comment by Nomamuk** [comment]
直接在访达里右键打开

**Comment by junlingf** [comment]
> 直接在访达里右键打开
It works! Thx!
