### ISSUE TITLE
Dev版bug

### ISSUE THREAD

**Issue by qin9125** [Caldis/Mos#340]
![image](https://user-images.githubusercontent.com/32502941/102843675-a57f9980-4444-11eb-8b91-d1e2fc7623c9.png)
先感谢大佬搞出来这么好的软件，一直关注3.30版，每次代码更新都在bigsur11.1 Xcode12.3编译最新版，已经试过最少3版了吧，不知道是代码还没完成还是bug，早期的版本在可以选择的长菜单中阴影会不停的来回跳现在好转了但是鼠标右键菜单在qq选择的时候失效，右键@人的时候也是失效无法起作用，旧版3.10一切正常，希望能修复一下，谢谢

**Comment by Caldis** [comment]
谢谢反馈, 是已知问题, 已修复
https://github.com/Caldis/Mos/releases/tag/3.3.1
