### ISSUE TITLE
M1 芯片提示“无法打开“

### ISSUE THREAD

**Issue by nofishdesign** [Caldis/Mos#341]
**Describe the bug | 问题描述**
M1 芯片 Mac mini 无法打开，打开时报错
![231608737038_ pic_hd](https://user-images.githubusercontent.com/72636870/103012264-4b7ef100-4576-11eb-9e97-bd6090f6d733.jpg)

**Comment by levie-vans** [comment]
试试
sudo codesign -f -d -s - /Applications/Mos.app

**Comment by nofishdesign** [comment]
目前解决了！谢谢你
________________________________
发件人: levie-vans <notifications@github.com>
发送时间: 2020年12月27日 17:23
收件人: Caldis/Mos <Mos@noreply.github.com>
抄送: nofishdesign <gusijielife@outlook.com>; Author <author@noreply.github.com>
主题: Re: [Caldis/Mos] M1 芯片提示“无法打开“ (#341)


试试
sudo codesign -f -d -s - /Applications/Mos.app

―
