### ISSUE TITLE
Make a universal binary release

### ISSUE THREAD

**Issue by pxia** [Caldis/Mos#343]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**

None

**说说你的新点子 | Describe the solution you'd like**

It would be easier to install for apple silicon Macs if the release include a universal binary version. 

I compile for ARM on the new Xcode with no issues, so it's probably very easy to do.

**还有别的替代方案吗？ | Describe alternatives you've considered**

n/a

**额外说明 | Additional context**

n/a

**Comment by ArttuLai** [comment]
Yeah I've been running the dev branch on M1 Mac just fine for 2 weeks.

I have to mention I'm very noob at compiling apps (this was literally the 1st time I've done it or touched Xcode, but hey, I have the app running), and I'm pretty sure I didn't do it properly or something, but I'm having couple of issues: 
* the launch at login checkbox in the app crashes the app, but it works if I manually add it via settings to launch at login.
* the Block Key doesn't seem to work; I set a key that's supposed block smooth scrolling, but it doesn't block it. 

But I guess the point is that I can open it in Xcode, compile, and it works. I can provide feedback and test if we get a "proper M1 version."

**Comment by Caldis** [comment]
thanks for feedback, i already released the universal bundle, but i don't have any device to test it on, so if there are any bugs, just feel free to open an issue!
https://github.com/Caldis/Mos/releases/tag/3.3.1
