### ISSUE TITLE
big sur11.1 网易云歌单滑动bug

### ISSUE THREAD

**Issue by coldwarm7** [Caldis/Mos#345]
**Describe the bug | 问题描述**
刚打开网易云歌单时滑动时上下滚动方向会失效，需要隔一会才会是期望的滑动方向

**To Reproduce | 如何重现**
网易云歌单滑动

**Expected behavior | 期望结果**
和设置的滑动效果保持一致

**Screenshots | 相关截图**
无
**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master] 罗技g304
 - OS: [e.g. iOS] 11.1
 - Version [e.g. v69]
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
在 10.15.7 + 最新版本网易云没测试出问题, 可以用新版本试试, 不太确定问题是系统还是应用问题
https://github.com/Caldis/Mos/releases/tag/3.3.1
