### ISSUE TITLE
MOS faceless app window shortcuts

### ISSUE THREAD

**Issue by sealvessel** [Caldis/Mos#346]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**
Instead of using the mouse to press the x on the window, I would like to use the shortcut command-W to exit the application
我想使用快捷键-W退出应用程序，而不是使用鼠标在窗口上按x。
**说说你的新点子 | Describe the solution you'd like**
Set a shortcut, command-w to exit the app
设置快捷键Command-w退出应用

**Comment by Caldis** [comment]
Thanks for feedback, the bug come from hiding the icon from the dock, but I don't think it's a big deal because users rarely use the panel in daily usage..
