### ISSUE TITLE
Tab freezes in Google Chrome

### ISSUE THREAD

**Issue by malvese** [Caldis/Mos#349]
**Describe the bug | 问题描述**

Sometimes when I scroll an email in Gmail, the tab seems to freeze: I can't scroll or click anything. Sometimes the tab resumes working after a few seconds, often I have to close then re-open it.
It also happened a couple times on random sites, but it is frequent in Gmail.

**To Reproduce | 如何重现**

Scroll up and down rapidly in Gmail

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: Logitech M590
 - OS: macOS Catalina 10.15.7
 - Browser: Chrome
 - Version v87

**Comment by Caldis** [comment]
maybe fixed in latest versions, you can try it now
https://github.com/Caldis/Mos/releases/tag/3.3.1
