### ISSUE TITLE
Bug in Whitelist mode (scrolling tick box) is not being respected 

### ISSUE THREAD

**Issue by rochakagrawal** [Caldis/Mos#350]
- 我们不想将反馈问题的门槛抬得太高, 所以你不需要完全将下方的内容填完, 但是, 提供尽可能完整的内容可以让我们更快速地定位问题
- We don't want to make the feedback problem too complicated, so you don't need to completely fill out the content below, but providing content that is as complete as possible allows us to locate problems more quickly.

---

  感谢您的反馈, 请在提交前将上方文字删去 | Thanks for your contribution, please delete the text above before submitting

---

- 问题描述 | Issue description:
During your application exception mode, if you unselect smooth scrolling from an application, it still keeps smooth scrolling. It's not respecting that selection. However, the Mouse scrolling direction selection is being respected

- 如何重现 | How to reproduce it:

Add an application to the exception mode. Unselect smooth scrolling.  App will continue to have smooth scrolling

- 期望结果 | What is expected:
Smooth scrolling should have stopped !

- 实际结果 | What is actually happening:

- 软件版本 | Application version:
Latest macOS version and Mos app version.

- 系统版本 | System version:
macOS 11.1 on M1 silicon

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:

**Comment by Caldis** [comment]
Fixed in latest version
https://github.com/Caldis/Mos/releases/tag/3.3.1
