### ISSUE TITLE
这个软件太棒了，请问windows能实现这样的效果吗

### ISSUE THREAD

**Issue by bnnz1085199** [Caldis/Mos#353]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**

**说说你的新点子 | Describe the solution you'd like**

**还有别的替代方案吗？ | Describe alternatives you've considered**

**额外说明 | Additional context**

**Comment by Caldis** [comment]
谢谢建议, 不过目前没有开发 Windows 版本的计划

**Comment by linonetwo** [comment]
有windows的替代品推荐吗
