### ISSUE TITLE
希望原生支持Apple Silicon Mac | Add native support for Mac with Apple Silicon

### ISSUE THREAD

**Issue by denny2001** [Caldis/Mos#355]
现在的版本似乎只是Intel版本Mac适配的，在M1 Mac上能通过Rosetta运行。希望能增加原生适配ARM Mac的版本。
The current version seems to natively support only Intel Mac, although it can run normally under Rosetta. Waiting for a version with native ARM Mac support.

我不清楚，可能只需要重新Build一下？感谢开发者！
I'm not sure, but it may be possilbe that just rebuilding it will do the trick. Thank you all for the support.

**Comment by Caldis** [comment]
新版本已发布
https://github.com/Caldis/Mos/releases/tag/3.3.1
