### ISSUE TITLE
黑名单添加java闪退

### ISSUE THREAD

**Issue by Squaregentleman** [Caldis/Mos#357]
**Describe the bug | 问题描述**

黑名单添加java闪退

**To Reproduce | 如何重现**

打开java写的程序 例如 Minecraft

**Expected behavior | 期望结果**

添加java不闪退

**Screenshots | 相关截图**

无

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master] 杂牌鼠标
 - OS: [e.g. iOS] MacOs Big sur 11.2
 - Browser [e.g. chrome, safari] edge
 - Version [e.g. v69] 88.0.705.62
 -  Application [e.g. Safari, Chrome, Whole System] Java

**Additional context | 额外说明**

**Comment by Caldis** [comment]
新版本已发布, 解决了该问题
https://github.com/Caldis/Mos/releases/tag/3.3.1
