### ISSUE TITLE
Doesn't Work on Big Sur 11.2.1

### ISSUE THREAD

**Issue by runningcheese** [Caldis/Mos#358]
**Describe the bug | 问题描述**
安装好了，也勾选了隐私选项，但平滑滚动不起作用，是最新的 3.1.0 版本

**System Info | 系统信息:**
 - Mouse: [双飞燕无线鼠标]
 - OS: [macOS]

感谢开发者 Caldis！

**Comment by Caldis** [comment]
不确定问题原因, 不过你可以试一下新的版本是否有解决问题
https://github.com/Caldis/Mos/releases/tag/3.3.1

**Comment by tabris233** [comment]
macos big sur 11.2.1. 不工作+1
![image](https://user-images.githubusercontent.com/29500388/109394132-5da75200-7960-11eb-8074-1620ed456cfb.png)
