### ISSUE TITLE
Block Key doesn't work

### ISSUE THREAD

**Issue by ArttuLai** [Caldis/Mos#360]
### Describe the bug | 问题描述
In the Mos settings --> advanced, I can set Block Key. However, this setting does nothing.

### To Reproduce | 如何重现
Set Block Key to any of the keys it offers and try to scroll in any app. I can reproduce this 100% of the time.

### Expected behavior | 期望结果
While holding the Block Key, scrolling returns to normal, non-Mos scrolling. In my case, it doesn't.

### System Info | 系统信息
 - Mouse: Logitech MX Master 3
 - OS: macOS Big Sur 11.3 Beta 2
 - Device MacBook Air M1
 - Version: Mos v3.3.1
 - Application: Whole System

**Comment by Caldis** [comment]
Thanks for feedback, it seems only bug in BigSur

**Comment by Caldis** [comment]
Fixed: https://github.com/Caldis/Mos/releases/tag/3.3.2
