### ISSUE TITLE
brew install mos --cask    Error: SHA256 mismatch

### ISSUE THREAD

**Issue by augusl** [Caldis/Mos#361]
**Describe the bug | 问题描述**
Error: SHA256 mismatch
Expected: 718e6652b772ddaa73945d9b5170cade170b5810f12256e84e258997332164bd
  Actual: 9bbe5c44a4dae57ea6495adce56eb55fb5a7dcf81d8f7b0b6489ddf78f02cc9d
**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
 - Version [e.g. v69]
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment]
Since I found an issue that needs to be fixed, I updated the DMG file after the release resulting in a change to the SHA, so you may have to wait for the cask update

**Comment by Caldis** [comment]
fixed
