### ISSUE TITLE
Mos can't be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by couragelfyang** [Caldis/Mos#387]
**Describe the bug | 问题描述**
Mos can't be opened because Apple cannot check it for malicious software.**To Reproduce | 如何重现**

**Screenshots | 相关截图**
![image](https://user-images.githubusercontent.com/9023177/112718514-dafdbc80-8f36-11eb-9c9d-316fa9868132.png)

**System Info | 系统信息:**
 - OS: MacOS Big Sur 11.2.3
 - Browser Chrome

**Comment by chenop** [comment]
Got it - why it was closed?

**Comment by maverickdas** [comment]
Facing the same issue
