### ISSUE TITLE
能否在特定的網址下禁用

### ISSUE THREAD

**Issue by softbearlolz** [Caldis/Mos#389]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**
ＭＯＳ的平滑會造成部分網站以滾輪瀏覽時接收到過多的指令
如term.ptt.cc
滾一次大概會送20次指令出去
**说说你的新点子 | Describe the solution you'd like**
若能在該網址禁用為佳
**还有别的替代方案吗？ | Describe alternatives you've considered**

**额外说明 | Additional context**

**Comment by vimcaw** [comment]
这个问题同样也困扰这我，但是这个功能绝大部分同类软件都没有，因为其它软件读取不了浏览器当前访问的网址，要实现还要开发一个浏览器插件来跟软件通信，开发成本较高。

**Comment by Caldis** [comment]
@vimcaw 大概是这个道理... 感谢解答
