### ISSUE TITLE
在 Atom 编辑器里向下滚动会有向上的反弹

### ISSUE THREAD

**Issue by wyudong** [Caldis/Mos#39]
- MOS 1.6.1
- macOS 10.12.6
- Atom 1.21.1
- 鼠标 Microsoft Wireless Mobile Mouse 4000

我在 Atom 安全模式下录了这个[视频](https://mega.nz/#!hjoijShZ!pOII_0QWKJ_dQjIhKMU56bkp6sNJODIgHyHxLVDBYXQ)，向下滚动结束后会有一个反弹，尤其是滚动到最下方时，能很明显看到。向上滚动这个反弹现象不太明显。触控板的滚动则没有这个问题。

#28 似乎是一样的问题？

监控 log：[scrollEventLog.log](https://github.com/Caldis/Mos/files/1413152/scrollEventLog.log)

**Comment by Caldis** [comment]
看了一下, Atom 不知道哪个版本开始 Atom 将文本编辑器内的滚动方式改为 translate 了, 我得找一下他这块的算法是不是有什么特殊处理...

![2017-10-30 2 54 38](https://user-images.githubusercontent.com/3529490/32147166-af631866-bd1d-11e7-9a76-55992051ddda.png)

**Comment by Caldis** [comment]
估计是这个 https://github.com/atom/atom/pull/15487

可能是为了屏蔽鼠标滚轮的滚动值小于 100 时候的滚动事件响应, 防止编辑器抖动, 结果与 Mos 的平滑滚动冲突了

**Comment by wyudong** [comment]
我编译了 atom，把你说的那个 issue 提到的地方改回到原来的状态，的确没有问题了，但我没明白为什么。

**Comment by Caldis** [comment]
@wyudong 
大概就是某某人提了个BUG, 说是触控板慢慢滑动的时候 Atom 没反应, 原因是没有达到触发滚动的最小阈值, 于是逻辑改成了:
如果滚动数值小于阈值, 比如1.0, 就将滚动统一格式化为1.0, 可能原因就是这个

**Comment by wyudong** [comment]
atom 正式版还是有这个问题，我现在都是用自己编译的版本 :(

**Comment by Caldis** [comment]
@wyudong 不如试试新版本
