### ISSUE TITLE
Add support for non-app file in exception list

### ISSUE THREAD

**Issue by Enderhoang** [Caldis/Mos#392]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**
I can't add Minecraft (as a Java app) to the exception list because Java is not an .app file so whenever I want to play MC, I must quit Mos and launch it again when I needed it

**说说你的新点子 | Describe the solution you'd like**
Add support for non .app file on the exception list (like UNIX executable files)

**还有别的替代方案吗？ | Describe alternatives you've considered**
None

**额外说明 | Additional context**
None

**Comment by Caldis** [comment]
thanks the feedback, the latest version already support that
