### ISSUE TITLE
滚动条往下滚动时间歇性的会往上滚一下

### ISSUE THREAD

**Issue by lsaint** [Caldis/Mos#396]
这个不知道是Mac上用非自家鼠标时的特有问题还是我的鼠标有问题，我上一个鼠标也是这样，所以我怀疑是Mac固有的问题。那么问题来了，这个问题可以通过这个App的某种设置来避免掉吗？

**Comment by ddzy** [comment]
> 这个不知道是Mac上用非自家鼠标时的特有问题还是我的鼠标有问题，我上一个鼠标也是这样，所以我怀疑是Mac固有的问题。那么问题来了，这个问题可以通过这个App的某种设置来避免掉吗？

同样的问题，看来不是鼠标的问题

**Comment by Caldis** [comment]
应该是滚轮太灵敏导致的...
我有的鼠标也会有这种问题, 其实就是手指划到头往回拿的时候有可能会往反方向蹭到一下, 虽然是很轻微的动作但是滚轮会响应到

**Comment by wayone** [comment]
> 

应该是异常，因为之前用的同样的鼠标，是没有这个问题的。

**Comment by yqchilde** [comment]
我还以为是我鼠标坏了，京东都售后换新了，现在来看应该是系统问题，在win下没事

**Comment by BobbyCatty** [comment]
我也遇到同样的问题了，请问各位解决了吗？

**Comment by yangyanch** [comment]
我也遇到同样的问题了，请问各位解决了吗？
