### ISSUE TITLE
鼠标在窗口间切换时产生预期外结果

### ISSUE THREAD

**Issue by zzhzero** [Caldis/Mos#402]
**Describe the bug | 问题描述**
在A窗口滚动滚轮，在A窗口滚动尚未结束时将鼠标移至B窗口，B内容会滚动而A的滚动会立刻停止。
**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master]
 - Version [e.g. v69]
 -  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**
程序的工作原理是模仿鼠标行为？如果是的话，这似乎是预期内的现象？

**Comment by Caldis** [comment]
感谢反馈
新的版本行为已经有改动了, 目前滚动只会发生在产生的目标窗口内, 不会逃逸
