### ISSUE TITLE
Mos无法更新

### ISSUE THREAD

**Issue by dongdonglovic** [Caldis/Mos#406]
**Describe the bug | 问题描述**
之前安装的2.3.0版本 在状态栏隐藏了图标，现在想升级最新版本，但是安装的时候提示说Mos正在运行无法升级。但是之前已经在状态栏隐去了图标，请问如何关闭mos，或者在状态栏重新显示图标。

**Expected behavior | 期望结果**
关闭mos 或者在状态栏重新显示图标来关闭mos，以便升级到最新版。

**Comment by Caldis** [comment]
用活动监视器搜索 Mos 然后手动停止即可
