### ISSUE TITLE
Asepire or GIMP zoom is to sensitive.

### ISSUE THREAD

**Issue by potofpie** [Caldis/Mos#413]
**这个问题是否源自某个缺陷？如果是，可于此处描述一下 | Is your feature request related to a problem? Please describe.**
In some application like Asepire or GIMP you cannot zoom in with this application active. The scroll ends up zooming in way to much making the scroll wheel unuseable.

**说说你的新点子 | Describe the solution you'd like**
I would like a program blacklist.

**还有别的替代方案吗？ | Describe alternatives you've considered**
Turning it off when I am using the applications it doesn't work with or installing another product. 

**额外说明 | Additional context**

**Comment by hrvstr** [comment]
There already is a blacklist feature available. In the app settings go to the "exceptions" tab and disable smoothing or choose custom scroll speed etc.

**Comment by coheredigital** [comment]
The blacklist doesn't work in Aseprite FYI
