### ISSUE TITLE
Cannot open app because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by bpenda** [Caldis/Mos#415]
感谢您的反馈, 请在提交前将上方文字删去 | Thanks for your contribution, please delete the text above before submitting

---

- 问题描述 | Issue description: Cannot open app on macOS big sur 11.4

- 如何重现 | How to reproduce it: try to open app

- 期望结果 | What is expected: app opens

- 实际结果 | What is actually happening: system security dialog shows, saying "Mos.app” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information."

- 软件版本 | Application version: 3.2.2

- 系统版本 | System version: 11.4

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system: none
![image](https://user-images.githubusercontent.com/7737727/124633214-0c99f400-de53-11eb-8f89-226651c52ff5.png)

**Comment by xzifan** [comment]
Try to open it again and go to Settings - Security & Privacy - General 

 Next to the "Allow apps downloaded from" section, you'll see a button"Open any ways"

**Comment by bpenda** [comment]
> Try to open it again and go to Settings - Security & Privacy - General
> 
> Next to the "Allow apps downloaded from" section, you'll see a button"Open any ways"

that doesn't work on my work machine, clicking open anyway just shows the same dialogue. I assume my admin has that option locked down somehow?

**Comment by bpenda** [comment]
will close this since I was able to work around the issue by cloning and building the app myself, but it would be nice if it were correctly signed
