### ISSUE TITLE
请大佬去接管MacGesture的继续开发，也是Mac必备软件

### ISSUE THREAD

**Issue by varjay** [Caldis/Mos#42]
MacGesture的开发者太忙了，解决不鸟bug，GitHub有源码

**Comment by gonejack** [comment]
我感觉这个项目学生作品，很多设计和底层做得并不好，接管不如大佬直接新开项目以 Mac 版 Strokeit 为目标更好。

**Comment by Caldis** [comment]
MacGesture 用 OC 写的，暂时吃不动，而且现阶段也没有精力同时维护两个应用，见谅

各位大佬饶命 ~
