### ISSUE TITLE
Quicklook 中查看pdf文档滚动无效

### ISSUE THREAD

**Issue by chenjau** [Caldis/Mos#43]
如题, 在使用 Quicklook 查看 pdf 文档时, 正文区滚动一两次即失去反应. 侧边的页缩略图一栏可正常滚动.
os: sierra 10.12.6
mos: 1.7.0

**Comment by Caldis** [comment]
@chenjau 
感谢反馈，能否在正文区滚动的时候打开 **滚动监控** 看一下滚动曲线是否正常？

**Comment by chenjau** [comment]
页面没有反应的时候, 曲线是正常的.
