### ISSUE TITLE
最新版软件在monterey里，反转鼠标滚轮，在滑动过程中存在概率性突然反转失败的情况

### ISSUE THREAD

**Issue by liyuhaolol** [Caldis/Mos#447]
最新版软件在monterey里，反转鼠标滚轮，在滑动过程中存在概率性突然反转失败的情况

找一篇长文，慢慢向下滚动，存在概率性，突然向上滚一下。

一直向下滚动

**Comment by JasonLamv-t** [comment]
我一直存在这个问题，现在还是bigsur，软件版本是3.3.2，之前的版本也有这个问题，
表现为滚动过程中会短暂性反转失效导致反复回跳

**Comment by JasonLamv-t** [comment]
@liyuhaolol 你用的是啥鼠标，我发现用同事的罗技好像除了没那么丝滑外没啥问题，页面不会跳动或者停顿，我的雷柏750L就有问题

**Comment by tonynesss** [comment]
我的雷柏一样的问题，还以为鼠标的锅，不过关了mos好像也会，难道是系统问题？

**Comment by JasonLamv-t** [comment]
@tonynesss 我最近换了logi master3，这个问题解决了，可能真的是雷柏的问题

**Comment by tonynesss** [comment]
> @tonynesss 我最近换了logi master3，这个问题解决了，可能真的是雷柏的问题

最近用蓝牙连接的,好像又没啥问题了.

**Comment by zl0110** [comment]
罗技GPW2 一直有这个问题  会反转 一直以为鼠标坏了  发现关了Mos软件就正常了  关闭平滑滚动好像也不会有问题
