### ISSUE TITLE
OSX 10.12.6 (16G29)点击开机启动闪退

### ISSUE THREAD

**Issue by vmvn** [Caldis/Mos#45]
点击偏好设置尝试勾选开机启动时发生闪退。
附闪退gif截图，联系方式：345127857@qq.com
https://pan.lanzou.com/i07xj4d

**Comment by Caldis** [comment]
@vmvn 
感谢反馈，请问一下是什么机型
顺便查看一下位于：设置->用户与群组->登陆项，这里面是否添加了 Mos 的项
