### ISSUE TITLE
macOS 10.13 下，随着使用时间增加内存占用会显著增大

### ISSUE THREAD

**Issue by lunacory** [Caldis/Mos#46]
刚开机 Mos 的内存占用 290M 左右，不到300M；
我的Mac 一般不关机，持续开机使用几天后，Mos 内存占用能增加到 900多M，接近1个G了。

我的系统是 10.13.2，Mos版本最新的1.7.0，加速参数使用缺省设置，白名单模式，主要是针对几个浏览器和访达、预览。

**Comment by Caldis** [comment]
@lunacory 
感谢反馈，这个问题貌似是引入了 Charts 之后造成的，我在 2.0 版本会尽量改善这个问题
