### ISSUE TITLE
设定了例外程序之后的情况

### ISSUE THREAD

**Issue by wenheyuran** [Caldis/Mos#47]
我设置了Adobe Acrobat是例外，不启用平滑。但是之前我一直以为对于它没起作用，因为我滚动的时候还是平滑的。今天突然发现，如果我没有点击进acrobat里面，也就是任务栏不是acrobat的时候，滚动就会平滑，但是这时候被滚动的就是acrobat啊。然后我点进去之后，最小化了，不点Chrome，也可以滚动，但是这时候的滚动就是acrobat的非平滑滚动了。

额，我也不太清楚这算不算问题，主要的原因应该是系统允许程序不在前台就可以滚动吧。

**Comment by Caldis** [comment]
的确是这样的
因为一开始用的是指针位置检测，通过获取指针坐标然后获取对应的窗口，来检测是否需要禁用平滑
但是苹果提供的这个 API 有问题，不支持外接显示器的检测，所以只能采用检测前台窗口的方式
虽然不那么好用，但在外接显示器上至少能正常工作
