### ISSUE TITLE
建议在例外程序中反向滚动依然生效，或者可选生效！

### ISSUE THREAD

**Issue by dficonfont** [Caldis/Mos#48]
建议在例外程序中反向滚动依然生效，或者可选生效！

例外程序滚动是相反的，这个有点不合适，感谢作者的贡献

**Comment by Caldis** [comment]
@dficonfont 
例外程序中可以单独控制**禁用平滑**或**禁用反向**
如果你想在例外程序中**反向滚动**依然生效,取消☑️勾选即可
你先试试
