### ISSUE TITLE
在iterm2中滚动过快，最小step滚动半屏还多

### ISSUE THREAD

**Issue by wanzaiqidao** [Caldis/Mos#482]
问题描述：
使用默认配置，在iterm2中滚动过快。
滚轮稍微一动，一晃就滚动了一屏多的内容。

软件版本：3.3.2

复现方式：在iterm2中，对比下 mos 与 smoothscroll 的滚动效果，一目了然。

期望效果：在iterm2中可以正常滚动。多谢

**Comment by KURANADO2** [comment]
@wanzaiqidao Duplicate with #82

**Comment by wanzaiqidao** [comment]
> @wanzaiqidao Duplicate with #82
it works. thank you

**Comment by Wyz2927** [comment]
> > [@wanzaiqidao](https://github.com/wanzaiqidao) Duplicate with [#82](https://github.com/Caldis/Mos/issues/82)
> > it works. thank you

how do you fix this bug? run this code?

**Comment by Wyz2927** [comment]
> > > [@wanzaiqidao](https://github.com/wanzaiqidao) Duplicate with [#82](https://github.com/Caldis/Mos/issues/82)
> > > it works. thank you
> 
> how do you fix this bug? run this code?

/usr/bin/vim -c "set mouse=a" -c "set ruler" /usr/include/zlib.h
