### ISSUE TITLE
希望滚动速度可以针对单独 App 调整

### ISSUE THREAD

**Issue by millionart** [Caldis/Mos#49]
部分游戏下滚动速度过快，一下翻到页底，很难受

**Comment by wyudong** [comment]
不是可以添加例外的应用程序吗

**Comment by Caldis** [comment]
游戏内不建议开启，或者你也可以用白名单模式对特定应用启用
一般需要平滑的就是几个浏览器和一些需要滚屏的聊天软件或文档浏览器
