### ISSUE TITLE
发现一个小问题，不知是不是问题

### ISSUE THREAD

**Issue by foxzzu** [Caldis/Mos#5]
用了新版本，macOS 10.12触摸板流畅了。同时发现，最新版本鼠标滚轮滚动大于一定速度时，页面才开始流畅滚动，缓慢推动鼠标滚轮时，页面就不滚动。1.0.0版本，缓慢推动滚轮时，页面会缓慢滚动。感觉1.0.0这方面体验更好些。

**Comment by Caldis** [comment]
这个问题之前也有人提过，不过只在一部分鼠标上有这个问题，正在定位中

感谢反馈🙏

**Comment by Caldis** [comment]
请更新到最新版本1.4.0
https://github.com/Caldis/Mos/releases/tag/1.4.0

然后打开滚动监视器, 点击右下的 ▶️ 按钮来记录一下你的"缓慢滚动" 的鼠标事件, 然后将对应的log文件内容黏贴到这里.

谢谢🙏

**Comment by foxzzu** [comment]
鼠标罗技M220
[scrollEventLog.log.zip](https://github.com/Caldis/Mos/files/764415/scrollEventLog.log.zip)

**Comment by Caldis** [comment]
可以试试最新发布的 1.4.2, 我希望你的问题已经解决了 😂
https://github.com/Caldis/Mos/releases/tag/1.4.2

**Comment by foxzzu** [comment]
Log文件见附件，鼠标罗技M220

**Comment by foxzzu** [comment]
赞速度。试了一下，很好使啊，多谢作者的辛苦劳动 @Caldis

**Comment by Caldis** [comment]
不客气, 你提供的数据也有很大参考价值哈, 每格鼠标上报的数据不太一样, 之前没有什么样本也无法考虑太多情况
