### ISSUE TITLE
反馈一个问题

### ISSUE THREAD

**Issue by LisonFan** [Caldis/Mos#504]
系统里设置的滚动方向是自然
Mos 设置了鼠标反转
Windows 和 Mac 之间用 Synergy 同步键鼠（macOS 作为客户端）Mos 的鼠标反转不生效
Synergy 可以在这里下载 https://github.com/DEAKSoftware/Synergy-Binaries
不知道是否能处理下这个问题 @Caldis

**Comment by captainnx** [comment]
楼主最后怎么解决的....求方案
