### ISSUE TITLE
更新MacOS 13后，在PDF Expert中滚动反向时会出现震荡

### ISSUE THREAD

**Issue by WinnieJiangHW** [Caldis/Mos#538]
**Describe the bug | 问题描述**

在PDF Expert中滚动反向时会出现震荡
- 连续向一个方向滚动不会出现
- 在其他App中没有出现
- 仅在更新MacOS 13后才发现这个问题

**To Reproduce | 如何重现**

**Expected behavior | 期望结果**

**Screenshots | 相关截图**

https://user-images.githubusercontent.com/57868812/198519741-5ce356b4-fb92-4fe9-9175-8383507af9fe.mp4

**System Info | 系统信息:**

 - Mouse: Logitech MX Anywhere 3
 - OS: MacOS 13
 -  Application: PDF Expert

**Additional context | 额外说明**

上面的视频进行了慢放处理，可以发现在向下滚动鼠标时，它先向上滚动了一点点，才再向下滚动，造成了视觉上的震荡

**Comment by Caldis** [comment]
能否用滚动监控查看一下曲线是否有异常 ? 
理论上这种情况不应由版本升级引起吗, 我用旧款 MX Anywhere 的时候倒会经常因为触发了 MagSpeed 导致滚轮会有反向的抖动...

**Comment by WinnieJiangHW** [comment]
您好，我用滚动监控重新录制了视频

https://user-images.githubusercontent.com/57868812/200333611-f7bce287-0807-44b3-a80d-85f99863b3ec.mp4

通过逐帧播放发现确实出现了反向滚动

<img width="1040" alt="iShot_2022-11-07_22 21 48" src="https://user-images.githubusercontent.com/57868812/200334134-a109f67f-2474-4a05-be99-3ad8d4055106.png">

这是监控截图

<img width="1040" alt="iShot_2022-11-07_22 22 09" src="https://user-images.githubusercontent.com/57868812/200334475-a4920d69-bda3-43c5-91a0-5de545670a17.png">

虽然在视频中看着并不明显，但实际用的时候感知还挺强的（如查阅文档时频繁上下滚动）。我在想难道是由于Logitech Options+的更新引起的？毕竟这是除了系统更新外唯一的变量了

**Comment by icekylin** [comment]
大概率是罗技的鼠标或驱动造成的, 现在换了个雷蛇没有出现这种情况

1. 罗技 G Pro 一代、二代同样存在这个问题
2. 同时插上雷蛇 + G Pro 两个鼠标使用时都会出现 "震荡"
3. 单独连接雷蛇鼠标, 滚轮正常

之前用一代的时候还因为这个原因找京东退换了新货来着 😢
