### ISSUE TITLE
咦，我好像不生效啊，连全局模式都没有翻转滚动的效果

### ISSUE THREAD

**Issue by lijxse** [Caldis/Mos#54]
如题啦。
![image](https://user-images.githubusercontent.com/20184046/37866054-256d3dc4-2fc0-11e8-9e01-d3eacdfcc07e.png)

不会跟其他程序有冲突吧。

我只想让 PS 的反人类滚动变的和 SKETCH 一样而已。

**Comment by Caldis** [comment]
能否提供详细信息, 包括但不限于

软件版本:
系统版本:
鼠标型号:
是否黑苹果:
无效程序或全局无效:

**Comment by lijxse** [comment]
软件版本:1.70就是最新的
系统版本:10.13.3
鼠标型号:鼠标是苹果二代
是否黑苹果:macbook pro 2015款
无效程序或全局无效:全局无效，白名单只弄 PS 也无效。

我第一次用，也可能我不会用吧

**Comment by lijxse** [comment]
但我昨天装过Scroll Reverser，忘了有没有卸载，不知道跟他有没有关系，也是翻转滚动的，但是那个软件我没开。

**Comment by Caldis** [comment]
用模拟器测试时的苹果鼠标报上来的数值跟触控板是一样的, 所以区分不出来, 也就没法做独立处理
这个问题我目前貌似也没啥方法解决, 改天借个鼠标来测测

话说 Scroll Reverser 对你的鼠标有效吗?

**Comment by lijxse** [comment]
有效啊，他可以让触控板和鼠标分开滚动，但是，他居然没有针对 APP 的黑白名单，只能全局。所以对我没用。触控板我貌似也无效啊。然后监控上并没有数据。

**Comment by lijxse** [comment]
![image](https://user-images.githubusercontent.com/20184046/37866158-ac4c96c2-2fc1-11e8-8fb8-54d37ea57643.png)
![image](https://user-images.githubusercontent.com/20184046/37866159-b3b93c44-2fc1-11e8-827a-7c5971c9f411.png)

我这样设置应该没错吧。

**Comment by Caldis** [comment]
设置没问题, 监控上没数据的话应该是兼容性问题或者是与其他软件冲突

方便的话, 你可以尝试一下新建一个用户, 然后登入后运行 Mos 试试

**Comment by lijxse** [comment]
嗯嗯，OK，我先自测一下。感谢大佬，辛苦了。

**Comment by Caldis** [comment]
不客气 感谢反馈问题
