### ISSUE TITLE
2.0.0 无法启动

### ISSUE THREAD

**Issue by g1084164986** [Caldis/Mos#55]
2.0.0 无法启动 下载源码后编译，在Mos/AppDelegate.swift中第21行读取配置文件时抛出异常(Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value)，将此行注释掉则可以正常打开。

**Comment by Caldis** [comment]
应该是我调试的时候有默认配置所以没测出这个问题
谢谢反馈，晚上回去修正下
