### ISSUE TITLE
关于非商业性使用协议版权问题

### ISSUE THREAD

**Issue by bioqxu** [Caldis/Mos#555]
请问[非商业性使用协议](http://creativecommons.org/licenses/by-nc/3.0/cn/)是否意味着我不能在公司的电脑上使用该软件？谢谢！

**Comment by womeimingzi11** [comment]
你可以，你只是不能以任何形式进行销售 Mos 或者宣传 Mos

**Comment by womeimingzi11** [comment]
> 你可以，你只是不能以任何形式进行销售 Mos 或者宣传 Mos

不能以商业为目的宣传 Mos

**Comment by bioqxu** [comment]
谢谢您的回复！
