### ISSUE TITLE
用户评价收集

### ISSUE THREAD

**Issue by Caldis** [Caldis/Mos#56]
这里想收集一些用户的反馈与评价信息, 如果您觉得 Mos 好用且对您带来帮助, 欢迎留言 !

将来我们会摘取一些精彩的留言放在首页 ~

如果您觉得是问题或需要修复的 BUG, 请单开一单 ISSUE, 谢谢

非常感谢大家捧场

**Comment by gonejack** [comment]
感谢作者的贡献和突出的审美力。

重构之后平滑效果的确很有改善，但改进空间依旧是有的，起步加速这一点依旧有些激烈。

**Comment by lunacory** [comment]
之前旧版一直用的默认设置，挺习惯的。但升级了新版，还是默认设置，感觉加速有点突兀啊

调了一会儿也出不来原先的效果了，看来得适应适应

**Comment by Caldis** [comment]
@darkhandz 😂 那个是 bug

**Comment by darkhandz** [comment]
@Caldis 感觉新版对类似MX Master那种可以切换滚动模式的鼠标友好了很多（可以滚得飞快）

**Comment by wyudong** [comment]
但是有些应用里滚得飞快不是很好，比如 [Audacity](https://www.audacityteam.org/download/)。如果有时间，请 @Caldis 下载试试。用滚轮缩放音轨的时候，由于滚得太空，基本缩放不到想要的地方。1.7.0 没有这个问题。

**Comment by lunacory** [comment]
@Caldis   现在比较适应新版的加速了，但发现例外是不是有bug？ 好像添加了不起作用

**Comment by Caldis** [comment]
@lunacory  例外需要窗口为激活时才会生效

**Comment by Zonz-Ly** [comment]
還在用 1.60 的時候，我的 Surface Arc 2 是可以左右滑動的（雖然不流暢）。
今天升級到了 2.20，左右滑動功能消失了，手指左右滑變成了上下滑動。現在需要按下 Shift 鍵才能實現左右滑動。

**Comment by gonejack** [comment]
2.20，调整启动加速后，真的好用了太多👍

**Comment by xixihaha134** [comment]
如丝般顺滑~
但，如果我不看issue,根本不知道 mx master 还要在logitech options 里禁用 平滑滚动。
所以，建议再开一个 各鼠标 优化建议和设置建议issue，大家分享各自 丝滑的设置。

**Comment by Caldis** [comment]
@xixihaha134 哈哈这个可能每个人喜好不一, 没有太多共性
不过不同软件之间的冲突肯定是存在的, 这个只能靠用户自己留意了

**Comment by UnleashHell** [comment]
经常莫名其妙就失效了，要重新启动才行，版本2.2.2

**Comment by UnleashHell** [comment]
10.12系统

**Comment by Caldis** [comment]
@UnleashHell 能否新开一单 Issue

**Comment by Caldis** [comment]
太多人在这单里反馈 Issue 了，故关闭
