### ISSUE TITLE
Mos doesn't work

### ISSUE THREAD

**Issue by Rodney-Zhu** [Caldis/Mos#563]
I installed the app Mos and it can't be opened:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/5578125/214703308-c22ab452-bde4-4b15-9dd2-4d1149e7fab8.png">

![image](https://user-images.githubusercontent.com/5578125/214703409-3d9309f5-1a27-4763-b03a-81338cda1bae.png)

**Comment by ianyepan** [comment]
This is a common pattern for 3rd party apps on macOS. Remember to go to System Preferences -> Security & Privacy -> General. Find the place towards the bottom where it says Mos was. Click "Open Anyway" and you're good to go.

**Comment by ianyepan** [comment]
![image](https://user-images.githubusercontent.com/36686900/214783832-652792d3-c6e6-4746-98ef-31a7750e7e1f.png)

**Comment by Rodney-Zhu** [comment]
Got it, it worked, thanks so much!

I'm relatively new to Macs coming over from Windows.
