### ISSUE TITLE
鼠标滚轮速度过快

### ISSUE THREAD

**Issue by zsj0723** [Caldis/Mos#569]
mos中最短步长、速度增益以及持续时间均已设置为最低。

启用mos前使用鼠标在PS中使用滚轮缩放，滚动速度都处于正常速度，滚动一下从42.1%放大到43.2%；
启用后，在PS中滚动一下滚轮直接从42.1%放大到441%；

希望启用后可以持平原先的滚动速度。

**System Info | 系统信息:**
 - Mouse:mopospeed
 - OS:MAC
 -  Application [Adobe全家桶]

**Comment by donniean** [comment]
可以关闭「平滑滚动」试试
