### ISSUE TITLE
“隐藏位于状态栏的图标”的台词

### ISSUE THREAD

**Issue by wyudong** [Caldis/Mos#57]
隐藏图标的提示有些小问题，建议改成这样：

### 隐藏位于状态栏的图标

**不过，即便 Mos 的状态栏图标被隐藏，其依然会在后台默默为你平滑鼠标滚动**

一旦隐藏了状态栏图标，就无法打开偏好设置了。如果想要显示被隐藏的图标，请在活动监视器里结束 Mos 进程，然后重新运行，在出现的桌面通知里点击“显示图标”即可。

**Comment by Caldis** [comment]
哈哈，谢谢建议，我吸收一下
