### ISSUE TITLE
【文字勘误】官网的版本，显示为undefined

### ISSUE THREAD

**Issue by cooper1x** [Caldis/Mos#575]
**Describe the bug | 问题描述**
官网的版本，显示为undefined。
[MOS | 一个用于在 MacOS 上平滑你的鼠标滚动效果或单独设置滚动方向的小工具, 让你的滚轮爽如触控板](https://mos.caldis.me/#)

**Screenshots | 相关截图**
<img width="823" alt="image" src="https://user-images.githubusercontent.com/9080789/221725835-23cf0d82-cf69-4c4c-a5d7-ebfc4c66530c.png">

**Comment by Caldis** [comment]
感谢提醒
