### ISSUE TITLE
Preference settings are lost after upgrade from 1.7.0 to 2.0.0

### ISSUE THREAD

**Issue by laggardkernel** [Caldis/Mos#58]
macOS 10.12.6. Setting is reset to default after upgrade. 
- "Start at Login" is unchecked;
- Exception list is cleared;

**Comment by Caldis** [comment]
This is normal, because 2.0 rewrites the code of the Setting, so it is not possible to migrate Setting items from 1.0. I hope it won't inconvenience you too much.
