### ISSUE TITLE
关于白名单模式

### ISSUE THREAD

**Issue by iTedding** [Caldis/Mos#59]
``macOS 10.12.6``
**“启用白名单模式后， mos仅会对包含在下方列表内的程序启用，其他的则不受任何影响。”**
现在的情况是：
- 勾选白名单，Mos会针对例外列表中的程序，不启用平滑。（其中单独定义的平滑与反转也不生效）
- 不勾选白名单，Mos会忽略例外列表的存在，对所有程序生效。

**Comment by Caldis** [comment]
怎么关闭了?

**Comment by iTedding** [comment]
因为 我重启了程序和系统几次之后发现，在勾选checkbox 完成之后，需要关掉对话框，切换到别的窗口，重新激活名单里对应的窗口，然后设置就生效了。所以，我就关闭了issue。
在 2018年3月31日，下午6:02，Caldis <notifications@github.com<mailto:notifications@github.com>> 写道：


怎么关闭了?

**Comment by Caldis** [comment]
是这样的, 因为现在检测窗口的方式是基于 ActiveWindow, 原本使用动态监测指针下方窗口而不需要激活窗口的方式, 但是在检测外接屏幕时有点问题, 所以只能折中采用了普通的方式
