### ISSUE TITLE
只能在一次滚动完成后才能继续下一次

### ISSUE THREAD

**Issue by 599316527** [Caldis/Mos#6]
拨一下滚轮，再拨一下，会经历 加速-减速-停止-加速-减速 这几步，如果是 trackpad 的话是没有停止这一步的

**Comment by Caldis** [comment]
如果可以的话请提供一下您的使用环境:
系统版本
黑/白果
是否在某些软件中才有这个问题? 还是都有?

最后如果方便的话可以用监控抓一份数据上来, 不然我这边也不太好分析.

**Comment by 599316527** [comment]
重启了一下app好像没法复现了，再出现时我提供下具体的数据吧

**Comment by 599316527** [comment]
又出现了一次，页面刷新后症状消失

https://youtu.be/gH2kXvVMHL8

10.12.4 Beta

**Comment by Caldis** [comment]
@599316527 谢谢反馈, 不过暂时没这个版本的系统环境来给我调试.
等 10.12.4 正式版发布了我再看看能否修复, 到时也麻烦您那边留意一下还能否复现哈

**Comment by Caldis** [comment]
10.12.4 测试通过, 个例问题无法复现
