### ISSUE TITLE
Mos 2.0在Mac休眠后无效，必须重启才能解决问题

### ISSUE THREAD

**Issue by hfzzztz** [Caldis/Mos#61]
在Mac休眠后，唤醒Mac后，顺滑滚动效果消失，滚轮反向效果消失，必须重新启动Mos才能解决问题。多谢作者辛勤劳动。

**Comment by Caldis** [comment]
@hfzzztz 谢谢反馈, 能否补充一下系统相关信息

**Comment by hfzzztz** [comment]
昨天遇到问题后，我换成了Mos 1.7，1.7中并没有问题，今天切换回2.0，并没有能够重现问题。
