### ISSUE TITLE
Can not install/run MOS

### ISSUE THREAD

**Issue by shikhar360** [Caldis/Mos#630]
**Describe the bug | 问题描述**
Tried to run the MOS by installing it from brew and the website as well . Showing some mac error
**To Reproduce | 如何重现**
Download it form the website or brew , open the dmg file and drag it into the applications folder
**Expected behavior | 期望结果**
Should open the MOS
**Screenshots | 相关截图**
<img width="256" alt="Screenshot 2023-12-30 at 4 32 46 PM" src="https://github.com/Caldis/Mos/assets/98407930/e4d80636-07be-4833-a447-1b162d64deda">

**System Info | 系统信息:**
 - Mouse: [e.g. Logitech MX Master] Hp gaming mouse
 - OS: [e.g. iOS] ios
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. v69] mos 3.4.1
 -  Application [e.g. Safari, Chrome, Whole System] whole system

**Additional context | 额外说明**

**Comment by Bokai-Zhang** [comment]
Open in finder, and right click on the application, try to open it in the drop down bar. This is a Mac OS issue, forcefully open it would fix the issue.

**Comment by VladimirCo** [comment]
the solution is [https://github.com/Caldis/Mos/issues/628#issuecomment-1837470717]here

**Comment by VladimirCo** [comment]
> **Describe the bug | 问题描述** Tried to run the MOS by installing it from brew and the website as well . Showing some mac error **To Reproduce | 如何重现** Download it form the website or brew , open the dmg file and drag it into the applications folder **Expected behavior | 期望结果** Should open the MOS **Screenshots | 相关截图** <img alt="Screenshot 2023-12-30 at 4 32 46 PM" width="256" src="https://private-user-images.githubusercontent.com/98407930/293457046-e4d80636-07be-4833-a447-1b162d64deda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTA0ODgsIm5iZiI6MTcwNDAxMDE4OCwicGF0aCI6Ii85ODQwNzkzMC8yOTM0NTcwNDYtZTRkODA2MzYtMDdiZS00ODMzLWE0NDctMWIxNjJkNjRkZWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA4MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMTAxMzY0ZTAyYjEwYmNhZGMxZjRmMzc3MjBkMGIxYzkwMzk2OTI1ZjU4OWEzMjQ4YjMxOTgwNzYyODFiYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pwc9Aoeie8M5VxuKbxs-cnp_cXw92KvfHynEUE5G2W0">
> 
> **System Info | 系统信息:**
> 
>     * Mouse: [e.g. Logitech MX Master] Hp gaming mouse
> 
>     * OS: [e.g. iOS] ios
> 
>     * Browser [e.g. chrome, safari] chrome
> 
>     * Version [e.g. v69] mos 3.4.1
> 
>     * Application [e.g. Safari, Chrome, Whole System] whole system
> 
> 
> **Additional context | 额外说明**

the solution is [here](https://github.com/Caldis/Mos/issues/628#issuecomment-1837470717)

**Comment by shikhar360** [comment]
got it thank you soo much ✨
