### ISSUE TITLE
使用PowerPoint翻页的时候一次翻很多页

### ISSUE THREAD

**Issue by JeremyGuo** [Caldis/Mos#66]
- 问题描述 | Issue description:
使用PowerPoint翻页的时候一次翻很多页

- 如何重现 | How to reproduce it:
打开你的PowerPoint随便开个PPT你就知道了

- 期望结果 | What is expected:
我希望像正常的一样鼠标滑一个格子翻一页

- 实际结果 | What is actually happening:
翻了很多页

- 软件版本 | Application version:
2.2.0

- 系统版本 | System version:
10.13.4

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:
Karabiner(没有对鼠标进行修改，只改了键盘)

**Comment by Caldis** [comment]
添加到例外应用中，取消勾选平滑滚动即可，或滚动时按住禁用键（默认为command）

**Comment by millionart** [comment]
建议增加一个默认列表……

**Comment by Caldis** [comment]
难以统计有哪些应用需要禁止平滑，而且本身例外功能也需要获取辅助权限才能使用
