### ISSUE TITLE
遇到金山词霸时出现平滑滚动停止

### ISSUE THREAD

**Issue by gaofengg** [Caldis/Mos#70]
- 问题描述 | Issue description:
我经常使用金山词霸,但是每当我打开金山词霸的生词本时,一滚动生词列表,mos的平滑滚动就停止了,此后使用其他软件,如chrome浏览网页,都没有平滑滚动,只能重新启动mos,不知道这种情况是否是我的个例?

- 如何重现 | How to reproduce it:

- 期望结果 | What is expected:

- 实际结果 | What is actually happening:

- 软件版本 | Application version:
2.2.0

- 系统版本 | System version:
  系统版本：	macOS 10.13.4 (17E199)
  内核版本：	Darwin 17.5.0
  启动宗卷：	MacOS
- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:

无

**Comment by Caldis** [comment]
感谢反馈，我测试一下

**Comment by Caldis** [comment]
生词本的界面, 用鼠标滚轮滚动的话, 我这边就算不开 Mos 也会很卡
@gaofengg  你那边也是这样吗?

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/releases/tag/2.2.2
