### ISSUE TITLE
Word2016下滚轮缩放操作有bug

### ISSUE THREAD

**Issue by linzehui** [Caldis/Mos#74]
- 问题描述 | Issue description:
首先非常感谢作者的劳动。在使用过程中发现一个小问题，不知道是不是我自己的操作有误。在Mac High Sierra下，使用Word2016，在利用滚轮对页面进行缩放过程中，和我期待的缩放是反过来的。即按下ctrl键+滚轮上翻，应该是放大，结果是缩小；ctrl键+滚轮下翻，导致放大。希望作者能够为我解答，多谢！😅

**Comment by Zonz-Ly** [comment]
我也遇到了同樣的問題，不過不是這個軟件。
希望可以增加一個按住 control／command 鍵禁用反向滾動的。

**Comment by Caldis** [comment]
我没有安装 Word2016, 不过请问一下在不开启 Mos 的情况下, 滚轮的放大缩小行为也是与正常方向相反的吗?

**Comment by linzehui** [comment]
首先感谢作者的回复。尝试了一下，在关闭Mos的情况下，滚轮放大缩小的逻辑是正常的，即control+滚轮上翻 是放大。😅我想可能是Mos没有考虑到这种情况吧。

**Comment by Caldis** [comment]
在启用了翻转滚动方向的情况下，放大缩小的逻辑肯定也肯定会被翻转

要解决这个问题，即使添加了按住 control／command 鍵禁用反向滾動，感觉也不是一劳永逸的方案，毕竟不同的软件的放大缩小的快捷键还不一样，只能让热键也做到按应用区分才行，
按住 control／command 鍵禁用反向滾動之后会加上，热键级别的按应用区分可能就没那么快咯，暂时就只能麻烦诸位习惯一下啦
