### ISSUE TITLE
偶尔用着用着翻转方向就失灵了

### ISSUE THREAD

**Issue by aiddroid** [Caldis/Mos#77]
- 问题描述 | Issue description:
偶尔用着用着翻转方向就失灵了，程序没有崩溃也没有退出，是不是整个软件都失灵了尚不清楚。但是频率挺高的，一周遇到好几回。

- 如何重现 | How to reproduce it:
不知道

- 期望结果 | What is expected:
正常使用

- 实际结果 | What is actually happening:

- 软件版本 | Application version:
2.2

- 系统版本 | System version:
macOS highSerria 10.13.4 (17E202)
MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports)

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:
没有

**Comment by Caldis** [comment]
请更新 2.2.2 试用一下

**Comment by aiddroid** [comment]
新版用了两周，没发现问题

**Comment by Caldis** [comment]
👌😄
