### ISSUE TITLE
平滑滚动偶尔会失效，需重启应用

### ISSUE THREAD

**Issue by UnleashHell** [Caldis/Mos#78]
- 问题描述 | Issue description:

平滑滚动失效，但是滚轮方向调整和横向滚动有效。

- 如何重现 | How to reproduce it:

由于是突发性无法刻意重现，但如需要提供系统debug数据可以配合提交。

- 期望结果 | What is expected:

平滑滚动一直有效

- 实际结果 | What is actually happening:

偶尔平滑滚动失效

- 软件版本 | Application version:

2.2.2

- 系统版本 | System version:

10.12.6

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:

Logitech options，但鼠标不是mx master

**Comment by Caldis** [comment]
失效的时候有没有运行什么高占用的软件？

**Comment by UnleashHell** [comment]
@Caldis 应该没什么突然占用很高的，我是双屏幕不知道跟这个有没有关系，然后就是用的jetbrains的IDE

**Comment by Caldis** [comment]
奇怪，如果平滑失效了，那方向调整应该也会失效的，也有可能是例外应用检测出现了问题？

想了解一下你的例外应用是如何设置的

**Comment by UnleashHell** [comment]
没有添加任何例外的程序。。 但是确实会感觉到失效了，重新启动程序就好了

**Comment by acoldfox** [comment]
我也会偶尔出现这个问题，出现的时候所有程序都会失效，只能重启解决。如果这点能改进，我觉得就完美了，比SmoothScroll好多了

**Comment by UnleashHell** [comment]
或许可以考虑增加一个显示日志功能，方便把运行信息提供给你？

**Comment by acoldfox** [comment]
一天大概会失效四五次，偶发性，没找到复现办法，失效后，scroll monitor 还是能正常统计的，但是点点之间间隔很大不平滑，这时候再进设置里调参，也是完全无效的,只能重启

**Comment by Caldis** [comment]
@UnleashHell @acoldfox 
谢谢反馈，我感觉可能还是代码效率较低导致，因为最近这个版本增加了很多检测项
下个大版本着重优化性能，如果还有这个问题的话，我再考虑加入日志输出

**Comment by Caldis** [comment]
可以尝试一下新版本 https://github.com/Caldis/Mos/releases/tag/2.2.6
稍微优化了一下占用，应该能降低失效几率

**Comment by UnleashHell** [comment]
辛苦了，但是用了两天新版本发现还是会有失效的情况

**Comment by shigeyxs** [comment]
感谢开发者，小白用户使用这个软件后普通的鼠标也感觉很方便。

**Comment by easyaspi314** [comment]
I still get this problem on version 2.2.6.

我仍然在2.2.6版本中遇到这个问题。

macOS 10.13.4
MacBook5,2

**Comment by Caldis** [comment]
@UnleashHell @easyaspi314 @acoldfox 
我猜想有可能是禁用键被误判导致，可以试试先暂时将高级设置中的禁用键设为不使用
I suspect that it may be caused by a misjudgment of Block Key. Try to temporarily disable the Block Key in advanced settings.

**Comment by easyaspi314** [comment]
I'll give it a try.

我会试一试。

**Comment by UnleashHell** [comment]
关了禁用键后一天多没出现了，感觉应该没问题了

**Comment by UnleashHell** [comment]
用了快一周了，禁用后没失效过

**Comment by UnleashHell** [comment]
@Caldis 好，有结果了我在这里回复

**Comment by Caldis** [comment]
@UnleashHell 感谢

**Comment by UnleashHell** [comment]
@Caldis 测试了，失效的时候按一次不好使，但是滚动的时候按住禁用键是可以平滑滚动的。

**Comment by Caldis** [comment]
@UnleashHell 了解了, 那应该就是我猜测的那个原因, 着手修复中

**Comment by millionart** [comment]
休眠时间过长会有几率出现相关问题，不是完全失效，而是每次滚动的第一下会失效，之后正常，建议暂时增加一个重启功能
