### ISSUE TITLE
开启hidpi后使用mos cpu占用过高

### ISSUE THREAD

**Issue by Vtamins** [Caldis/Mos#79]
- 问题描述 | Issue description:
最近买了台2K的显示器，由于字体太小，就开启了hidpi使用1080Phidpi进行显示，这时候发现如果开了mos进行滑动时cpu使用率会明显提高。尤其是Visual studio code以及Pycharm。目前发现这两个应用中的滑动时cpu占用十分高。关闭Mos平滑则滑动时不明显。
初步认为是hidpi会造成窗口滚动时CPU的使用，而平滑滚动进行窗口滚动的时间过长，因此当开启mos的平滑滚动时，进行窗口滚动的时长比未开启时区别明显，因此会产生明显cpu使用区别。

- 如何重现 | How to reproduce it:
找台2K显示器，开启1080P hidpi，开启mos平滑，打开vscode  开始滑动。

- 期望结果 | What is expected:
期望平滑滚动能够优化一下，如缩短平滑滚动的时间，来降低cpu使用。

- 实际结果 | What is actually happening:
等待答复

- 软件版本 | Application version:
2.2.0

- 系统版本 | System version:
macos 10.13.2

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:
无

**Comment by Caldis** [comment]
占用高指的是 VSCode 的占用，还是 Mos 本身的占用，还是整体的占用？

关于修改滚动的时延的选项，你可以在设置面板中找到

平滑滚动会增加 CPU 占用是一定的，不过 Mos 本身的占用并不高，处理滚动时根据频度和机器配置，其本身占用大约在1%-8%之间跳动。如果你觉得占用高到真的无法接受，建议针对性禁用。
