### ISSUE TITLE
在滚动过程中，移动鼠标会影响目标窗口的滚动状态

### ISSUE THREAD

**Issue by 599316527** [Caldis/Mos#8]
使用中发现：在滚动过程中，当鼠标从 A 窗口移动到 B 窗口时，A 窗口的滚动立刻停止，B 窗口开始滚动剩余量。

正确的行为应该是，整个滚动过程都应该归属于被触发的那个窗口。

**Comment by wyudong** [comment]
很有趣的发现，我这里也是相同的现象。但不怎么影响使用。

**Comment by Caldis** [comment]
是这样的,  因为处理逻辑是:
截获鼠标事件 -> 根据鼠标滚动事件计算插值曲线 -> 在一段时间内连续发送鼠标滚动事件

而在这个过程中是没有对事件的目标窗口进行判断的, 因为原生的 CGEvent 并不能指定发送的目标窗口
如果要做的话, 成本比较高, 如果你觉得缓动效果经常会影响其他窗口, 你可以试试把高级设置里面的动画时间尽量调短.
