### ISSUE TITLE
chrome滚到异常？！

### ISSUE THREAD

**Issue by yaozaiyu** [Caldis/Mos#80]
- 问题描述 | Issue description:
chrome使用的时候，滚轮反复小幅度来回滚动的时候，画面停止滚动

- 如何重现 | How to reproduce it:
反复小幅度来回滚动

- 期望结果 | What is expected:
期望和Safari一样

- 实际结果 | What is actually happening:
？！

- 软件版本 | Application version:
2.2.2

- 系统版本 | System version:
13.4

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:
steerMouse

**Comment by Caldis** [comment]
请问必现吗？还是偶发

**Comment by yaozaiyu** [comment]
必先

**Comment by Caldis** [comment]
会不会是与某些插件冲突？

**Comment by Caldis** [comment]
试试新版 https://github.com/Caldis/Mos/releases/tag/2.2.6

**Comment by yaozaiyu** [comment]
暂时正常了
