### ISSUE TITLE
Feature request: hide menu bar icon

### ISSUE THREAD

**Issue by hrvstr** [Caldis/Mos#81]
Hello, would it be possible to add the option to hide the menu bar icon? The options could be opened by simply running the app again like BetterTouchTool does it. I really don't need the icon all the time and screen space is precious :).

![bildschirmfoto 2018-06-02 um 12 17 31](https://user-images.githubusercontent.com/4610008/40873356-065f4d5c-665f-11e8-89ca-442b648a9ed9.png)

**Comment by richardmuhler** [comment]
Thanks! This is pretty much what I wanted! Could you add a checkbox to hide the Popup after boot?
![bildschirmfoto 2018-06-13 um 10 54 09](https://user-images.githubusercontent.com/34336238/41340645-2352c56e-6ef8-11e8-956d-22be48d4489c.png)

**Comment by Caldis** [comment]
You can mute the notification of Mos in your system preferences panel, when you want it show again, just unmute it.😄

**Comment by richardmuhler** [comment]
Fair enough, problem solved. Thank you very much for this great app!
