### ISSUE TITLE
出现 2 个启动项

### ISSUE THREAD

**Issue by millionart** [Caldis/Mos#83]
- 问题描述 | Issue description:
使用 CleanMyMac 3 
扩展——登录项
右边有2个 Mos.app 登录项，虽然是不影响使用，不过总觉得怪怪的

PS:
Workspaces.app 也有2个登录项，而其他 APP 没有这种情况，所以猜测是不是开机启动规范方面的问题？

- 软件版本 | Application version:
2.2.6

- 系统版本 | System version:
10.13.5

**Comment by Caldis** [comment]
可能是版本号变了，然后系统认为是两个，还没找到规避方式

问题倒是不大，删掉一个就行了

**Comment by millionart** [comment]
那就好，起码还能移除，Workspaces.app 根本不能移除（哭）

**Comment by wyudong** [comment]
刚刚也看了一下，我有三个 Mos，不过可以删除。

**Comment by styxschip** [comment]
我也遇到了这个问题，每次重启或者关机再开机后，启动项里就会多一个无效的Mos，而且Mos也没有启动。

**Comment by qkzsky** [comment]
此问题会导致在打开系统任意密码输入框（安全设置的解锁、邮件app的密码输入等）后导致系统崩溃重启
系统版本：10.14.6
mos版本，2.4.0-beta

通过安全模式移除用户启动项后解决
