### ISSUE TITLE
希望能在未来加入的功能【可以在状态栏中隐藏图标】

### ISSUE THREAD

**Issue by openviso** [Caldis/Mos#84]
FEATURE: 
希望能在未来加入的功能：可以在状态栏中隐藏图标

#

**Comment by chenjau** [comment]
1. 隐藏后启动时重复提醒.
2. 隐藏后, 通过双击 Mos.app 无法开启设置面板. 必须杀进程然后启动应用从提醒窗进入面板. 感觉可以改进下?

**Comment by Caldis** [comment]
@chenjau
1. 在系统设置中禁用Mos的通知就行，如果需要时候再手动开一下
2. 暂时只能想到这个解决方案，如果有更好的建议欢迎告知👏
