### ISSUE TITLE
笔记本适用的话有些冲突

### ISSUE THREAD

**Issue by HappyLeiLei** [Caldis/Mos#86]
- 我们不想将反馈问题的门槛抬得太高, 所以你不需要完全将下方的内容填完, 但是, 提供尽可能完整的内容可以让我们更快速地定位问题
- We don't want to make the feedback problem too complicated, so you don't need to completely fill out the content below, but providing content that is as complete as possible allows us to locate problems more quickly.

---

  感谢您的反馈, 请在提交前将上方文字删去 | Thanks for your contribution, please delete the text above before submitting

---

- 问题描述 | Issue description:
在笔记本中使用会和触控板有些冲突 触控板滑动时候滑动速度回加倍

- 如何重现 | How to reproduce it:
在笔记本上使用即可重现

- 期望结果 | What is expected:
能兼容触控板

- 实际结果 | What is actually happening:

- 软件版本 | Application version:
2.26

- 系统版本 | System version:
笔记本型号 ThinkPad E550 
MacOS 10.13.5

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:
无

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/issues/12

**Comment by HappyLeiLei** [comment]
好的 谢谢 这个插件非常👍 支持你

**Comment by Caldis** [comment]
@HappyLeiLei 谢谢
