### ISSUE TITLE
Feature Request: Set Step/Speed/Duration per Application

### ISSUE THREAD

**Issue by emongev** [Caldis/Mos#88]
- 问题描述 | Issue description:
Great application! I was wondering if we could set Step/Speed/Duration per application on the exceptions list?

- 软件版本 | Application version:
2.2.6

- 系统版本 | System version:
10.13.5

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:
None.

**Comment by Caldis** [comment]
@emongev 
Good suggestion ! I planned to develop this feature long ago, but it has been put on hold due to lack of time.

**Comment by ilcorsaronero** [comment]
Hi there, thanks for the amazing software! I'm as well looking forward for a per-app customisation of scroll speed, that would be amazing, especially in combination with Blender! Would be okay for me to have a simple text-based configuration file for this advanced option, even without a GUI.

**Comment by Caldis** [comment]
https://github.com/Caldis/Mos/issues/207
