### ISSUE TITLE
[Bug] Horizontal Scroll with SHIFT+Scroll is disabled in some applications with MOS running

### ISSUE THREAD

**Issue by BartoszKaszewczuk** [Caldis/Mos#89]
- 问题描述 | Issue description:
With a mouse, you can shift scroll direction in macOS from vertical to horizontal by holding Shift however with MOS running this behaviour is cancelled out and does nothing in some applications such as Numbers or Safari tabs. It works fine in some however such as IntelliJ.

- 如何重现 | How to reproduce it:
1. Launch Numbers.app which sheet wide enough for horizontal scroll
2. Hold Shift + Scroll with mouse
3. Nothing happens

- 期望结果 | What is expected:
Should scroll document horizontally 

- 实际结果 | What is actually happening:
Nothing. No scroll in either direction.

- 软件版本 | Application version:
2.3.0

- 系统版本 | System version:
10.13.5 (17F77)

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system:
EvoluentAgent.app - Mouse Driver for Evoluent Mice

**Comment by Caldis** [comment]
You can specify a toggle key in Preferences like this

<img width="562" alt="screen shot 2018-07-11 at 8 38 08 pm" src="https://user-images.githubusercontent.com/3529490/42571720-661efe0e-854a-11e8-884d-30dd7e77ad2a.png">

**Comment by BartoszKaszewczuk** [comment]
You're right. I assumed it was a bug since it worked just fine out of the box in IntelliJ. Thanks for prompt reply!
