### ISSUE TITLE
【一点不成熟的小建议】可以增加一个将鼠标滚轮转化为放大缩小的选项

### ISSUE THREAD

**Issue by Zonz-Ly** [Caldis/Mos#90]
想起之前也有朋友提到，在 Word 中，使用滚轮缩放，会反向的问题

昨晚突然想到一个办法，增加一个按住某个键，比如 Windows 下大家熟悉的 Control 键，加上鼠标滚轮，就可以很轻松地实现页面缩放的功能。

其实不只是在 Word 中，使用滚轮缩放会反向而已，还有很多其他的应用，有的正常，有的不正常。

但这还不是最可怕的，最可怕的是，有些应用使用 control+滚轮缩放（主要是微软的应用），有些应用使用 option+滚轮缩放（比如 MindNode），还有些应用使用 command+滚轮缩放（挺多的），还有些应用根本不支持按键+滚轮缩放（主要是苹果官方应用，不方便死了）。而很不幸的是，这些应用同时存在我电脑中，我有点快被折腾疯了。

而且，我也希望，按键加滚轮缩放时，平滑参数可以单独设定，因为和正常滚动平滑的参数一样的话，用于缩放会又些飘……

所以，增加一个这个功能，会真的很有用、很方便，这也可以成为这个软件超越其他众多同类软件的一个特色吧！

一如既往地资瓷作者，我对比了几乎所有的同类软件，这个是做得最吼的！比西方那些国家做的不知道高到哪里去了！

**Comment by Caldis** [comment]
关于缩放功能我想不想资瓷, 那当然是想的. 但是也要考虑到历史的行程.

这个中央...哦不, 系统的硬件事件层呢, 实际上是像流水管线, 前面的系统处理事件之后就交给之后一层, 上一层就无权管理了. 放大缩小这个事情呢, 实际上一律是由软件自己决定的, 系统给他的信号仅仅是 Control 键按下和鼠标滚轮移动的信号, 软件自己可以任意解读成放大缩小或是左右滚动, 又或者直接不处理都可以. 而系统本身又没有提供放大/缩小这样子的事件信号, 自然也没有权利统一软件的缩放行为了.

但按下滚轮缩放时调节平滑参数确实是个好建议, 等我有空了再加上

**Comment by foisonocean** [comment]
@Caldis 
不知道能否模拟触摸板上的两指缩放手势呢？如果可以的话，这个应该会很有用吧！

**Comment by wayone** [comment]
> @Caldis
> 不知道能否模拟触摸板上的两指缩放手势呢？如果可以的话，这个应该会很有用吧！

很需要这个！！！👍

**Comment by Caldis** [comment]
@foisonocean @wayone 
官方并没有开放相关的接口来在让用户在屏幕上通过 API 来模拟手势... 这块应该不需要抱太大期望..

**Comment by joeljhou** [comment]
Mos是目前最好用的了，就缺少了鼠标滚轮缩放

**Comment by Zonz-Ly** [comment]
> Mos是目前最好用的了，就缺少了鼠标滚轮缩放

https://github.com/alphaArgon/ScrollToZoom
我男朋友把这个功能做出来了
