### ISSUE TITLE
与浏览器 vivaldi  的 win + 滚轮放大缩小页面的快捷键冲突

### ISSUE THREAD

**Issue by leyle** [Caldis/Mos#91]
- 问题描述 | Issue description:

与浏览器 vivaldi  的 win(super) + 滚轮放大缩小页面的快捷键冲突

- 期望结果 | What is expected:
不要有这个快捷键，或者默认可以不启动这个不知道在哪里设置的有什么用的快捷键。让用户选择是否要在 Mos 里面使用 win(super) + 鼠标滚轮。

**Comment by Caldis** [comment]
不知道你在说什么, 什么快捷键 ?
高级设置里面有, 目前默认是不启用的

**Comment by leyle** [comment]
chrome 这样的浏览器，放大缩小页面用的是 command(win/super) 这个键和 +- 这两个键组合起来。
vivaldi 浏览器除了用这套键盘按键外，还可以用 command(win/super) 这个键配合鼠标中键滚动来放大缩小网页。

现在情况是，用了 Mos 后，command(win/super) 键和鼠标滚轮的配合就不是放大缩小网页了，还是在上下滚动液面。

**Comment by Caldis** [comment]
好的我晚上测试一下，谢谢反馈
