### ISSUE TITLE
After locking and then unlocking Mac, mouse wheel scrolling stops working

### ISSUE THREAD

**Issue by FutureSharks** [Caldis/Mos#93]
- 问题描述 | Issue description: After locking and then unlocking Mac, mouse wheel scrolling stops working. After restarting Mos app, it works again.

- 如何重现 | How to reproduce it: Lock Mac then unlock.

- 期望结果 | What is expected: Scrolling works

- 实际结果 | What is actually happening: scrolling with mouse wheel stops completely

- 软件版本 | Application version: 2.3.0 & 2.2.0

- 系统版本 | System version: 10.13.4

- 您系统中的其他鼠标管理软件 | Other mouse management application in your system: No

**Comment by FutureSharks** [comment]
Actually, after more testing, the scroll wheel is still working but for horizontal scrolling. Very weird.

**Comment by Caldis** [comment]
May be caused by a misjudgment bugs in the "Preferences -> Advanced -> Toggle Key", you can try setting it to Disabled. 
I will fix this problem later, thanks for your feedback

**Comment by FutureSharks** [comment]
OK I set both toggle and block keys to disabled and now the problem is fixed.

So it's a known bug?

**Comment by Caldis** [comment]
@FutureSharks Yep but i still finding way to rewrite the detect module of hotkey

**Comment by mkowalczuk** [comment]
I'm experiencing the same (scroll doesn't work after unlock, sometimes it works as horizontal scroll). 

Additionally, scroll wheel left/right buttons (on MS Sculpt Ergonomic Mouse) don't work at all after unlock. To fix it I need to restart Mos.

**Comment by mkowalczuk** [comment]
Sometimes, not always. I didn't figure out the rule yet.

**Comment by Caldis** [comment]
@mkowalczuk That's so weird, in normal circumstances they should be down together.

**Comment by mkowalczuk** [comment]
Disabling toggle/block keys fixed scroll up/down (it's now working after screen unlock), but didn't help for scroll left/right buttons.

BTW, I'm also using Karabiner-Elements (I don't have any modifications for mouse defined) and BetterTouchTool (I have some shortcuts that include scroll left/right).

**Comment by HuangJianlang** [comment]
> Disabling toggle/block keys fixed scroll up/down (it's now working after screen unlock), but didn't help for scroll left/right buttons.
> 
> BTW, I'm also using Karabiner-Elements (I don't have any modifications for mouse defined) and BetterTouchTool (I have some shortcuts that include scroll left/right).

I have the same issue. I set some hot keys in BetterTouchTool including scroll left/right.And after unlocking/waking the mac or quitting the screensaver the scroll left/right function must be invalid. I need to relaunch the Mos to solve the issue.

**Comment by HuangJianlang** [comment]
> Disabling toggle/block keys fixed scroll up/down (it's now working after screen unlock), but didn't help for scroll left/right buttons.
> 
> BTW, I'm also using Karabiner-Elements (I don't have any modifications for mouse defined) and BetterTouchTool (I have some shortcuts that include scroll left/right).

I believe the Mos may overwrite the custom functions that we have set on other tools(e.g BTT) into the original scroll left/right.

我认为在每次唤醒或者解锁之后，Mos可能覆盖了我们在其他地方设定的关于左右滑动键的快捷键。如果可以添加一个开关，关闭左右滑动可能会解决问题。 @Caldis
