### ISSUE TITLE
辅助功能启用后，应用依旧无法使用

### ISSUE THREAD

**Issue by huhuhang** [Caldis/Mos#95]
**Describe the bug | 问题描述**

辅助功能启用后，应用依旧无法使用。

**To Reproduce | 如何重现**

根据提示正常打开辅助功能选项。并以确认多次反复开启无效，重新安装应用无效，重启电脑安装应用且重新打开依旧无效。

**Screenshots | 相关截图**

![wx20180720-150706](https://user-images.githubusercontent.com/5147530/42988383-daf383e0-8c2e-11e8-85f6-a280cf77bce8.png)

**System Info | 系统信息:**
 - OS: macOS 10.13.6 正式版

**Comment by Caldis** [comment]
谢谢反馈, 之前也有用户反馈过类似问题, 但也不好定位是检测模块出现了问题还是系统冲突
如果方便的话, 可以方便新建一个用户然后测试一下授权能否正常监测到吗?

**Comment by huhuhang** [comment]
我之前是卸载之后重启电脑，再次安装无效。但看了 #68 之后，安装应用再重启就正常了。

**Comment by wr-fenglei** [comment]
问题：监控、平滑等所有对鼠标的调整都不可用，尝试过反复安装和重启
设备：MacBook Pro (15-inch, 2018)
系统：macOS 10.14.1
鼠标：Magic Mouse 2
Mos 版本：2.4.0-beta 、2.0.0

**Comment by xiaoxiongke** [comment]
软件~改一个版本号就行了...=.=

**Comment by musenl** [comment]
在辅助功能-隐私中，点-删除Barrier，再点+重新添加应用程序中的Barrier，并勾上✅
