### ISSUE TITLE
持续时间 不能分辨鼠标所处位置 而导致滚轮（持续时间内）作用于别的界面

### ISSUE THREAD

**Issue by hintheshell** [Caldis/Mos#96]
**Describe the bug | 问题描述**
举例 Chrome下浏览网页 滚轮往下翻看网页 滚轮停止后 mos的持续时间功能使得这个滚动的效果在我移出Chrome界面之后继续作用于其他app 
由于滚轮绑定了窗口全屏事件 在滚动页面后 鼠标移到标签页上想关闭页面常常触发窗口全屏

**To Reproduce | 如何重现**
同上

**Expected behavior | 期望结果**
期望持续时间只作用于目的区域（比如我只想滚动浏览器页面 在我鼠标移出界面的时候 不作用于其他app，页面在持续时间范围内仍然继续滚动）

**System Info | 系统信息:**
 - OS: [macOS]
 - Browser [chrome]
 - Version [2.3.0]

**Comment by Caldis** [comment]
好提议, 有空加上
