### ISSUE TITLE
可以参考 PopClip，平时隐藏菜单栏，点击图标的时候再显示

### ISSUE THREAD

**Issue by Phishion** [Caldis/Mos#98]
**Describe the bug | 问题描述**
A clear and concise description of what the bug is. | 清晰简洁的问题描述问题所在

平时菜单栏的图标就够满了

**Expected behavior | 期望结果**
A clear and concise description of what you expected to happen. | 简单描述问题解决后您所希望的结果

希望增加隐藏状态栏图标选项，点击图标后状态栏出现设置界面，差不多下面的意思

<img width="153" alt="2018-08-05 01 00 32" src="https://user-images.githubusercontent.com/3078873/43678701-09cb55bc-984b-11e8-82b3-236984a8d05a.png">

**Comment by Phishion** [comment]
按住 option 隐藏实在是太难找到了，恢复状态栏图标的方法有些“硬核”，您可以参考下 PopClip

**Comment by Zonz-Ly** [comment]
请使用 Bartender，谢谢。

**Comment by Phishion** [comment]
主要是用户体验问题，第一个隐藏图标功能太难找，普通用户很难发现，再一个隐藏之后的恢复方法太过繁琐。

**Comment by wyudong** [comment]
@xxmmllqqqqccqq kill Mos 的进程，比如可以用活动监视器关闭 Mos，再重新运行，点击通知中出现的 “显示图标”。
